### ISSUE TITLE
Decks should be automatically (or via prompt) assigned to the right archetype

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1003]
Not just the macro archetype chosen in Gatherling.

**Comment by silasary** [comment]
Alternatively, if a deck is assigned to one of the macro-archetypes, show a prompt on the deck page, and add it to some kind of moderation queue.  (Yay, more infrastructure)

**Comment by bakert** [comment]
The real issue here, I guess, is that some decks truly belong in Aggro and should not be prompting us to do anything because they are a one-off and don't have enough siblings to have an archetype added. Whereas some decks are in Aggro just because they were assigned to that on Gatherling and truly belong in Mono W Heroic. I don't like the idea of adding a flag "reviewed" or similar but that is one way to do it. Even if the machine guesses an archetype we probably still want it to be manually checked so maybe we do need a reviewed flag.

**Comment by bakert** [comment]
Couldn't think of a better way so added reviewed column and use it in 9b7bcb7.
