### ISSUE TITLE
Price grabber creation of cache table is very slow and may be causing site slowness and bot issues

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1083]
Specifically this is taking minutes or even longer:

    INSERT INTO cache (`time`, name, price, low, high, week, month, season)
    SELECT
        MAX(`time`) AS `time`,
        name,
        MIN(CASE WHEN `time` = 1500254967 THEN price ELSE 999999 END) AS price,
        MIN(price) AS low,
        MAX(price) AS high,
        SUM(CASE WHEN `time` > 1499650167 AND price = 1 THEN 1 ELSE 0 END) / SUM(CASE WHEN `time` > 1499650167 THEN 1 ELSE 0 END) AS week,
        SUM(CASE WHEN `time` > 1497835767 AND price = 1 THEN 1 ELSE 0 END) / SUM(CASE WHEN `time` > 1497835767 THEN 1 ELSE 0 END) AS month,
        SUM(CASE WHEN `time` > 1499995767 AND price = 1 THEN 1 ELSE 0 END) / SUM(CASE WHEN `time` > 1499995767 THEN 1 ELSE 0 END) AS season
    FROM low_price
    GROUP BY name;

We should either make it faster or do it another way or sacrifice some granularity or older data.

**Comment by bakert** [comment]
As of right now I've turned OFF price grabbing. So if everything becomes great starting now we know we've found our culprit. If nothing has improved in 24 hours I'll start looking elsewhere. I think it's ok to miss 24 hours of pricing date to find out easily.

**Comment by bakert** [comment]
Already feels like this was definitely the case.

**Comment by bakert** [comment]
From this: 

https://stackoverflow.com/questions/45176506/how-to-improve-performance-of-an-insert-into-select-x-from-y-group-by-z-mysql/45176852#45176852

I got a >6x speedup on local (from 1m 17s to 13s). Prod takes 8m to do the query local takes 77s so the implication is this would take the runtime down to 80s on prod. That might be good enough.

**Comment by bakert** [comment]
Production speedup is >16x! Woo!

Query OK, 15684 rows affected (8 min 59.61 sec)
=>
Query OK, 15684 rows affected (33.94 sec)

Restarting price grabbing on prod and we'll keep an eye on it!

Woop!

**Comment by silasary** [comment]
Awesome
