### ISSUE TITLE
Record failed searches (and all commands?) for review

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#109]

**Comment by bakert** [comment]
The bot could even log the channel and archive it somewhere. Don't know how useful that is.

**Comment by silasary** [comment]
Not sure that's worthwhile.

**Comment by bakert** [comment]
My guess is that we're not going to do this. Closing.

**Comment by silasary** [comment]
It's not as valuable now that people can just explicitly report things that don't exist.
