### ISSUE TITLE
Don't reuse input for scryfall search string, instead form a canonical string representation that will always work

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#110]
For example if we receive:

"F:pd    SET:EMN"

we should emit:

"f:pd e:emn"

This allows us to support alternate keys like "set" without it breaking scryfall links that we send out.

**Comment by bakert** [comment]
This should possibly be scryfall or pennydreadfulmagic.com ...

Edit: changed to scryfall which we now use.

**Comment by silasary** [comment]
If we implement our own search page, we should definitely use that.

Does Scryfall show PD legality now?

**Comment by bakert** [comment]
Yup!

**Comment by bakert** [comment]
When I wrote this up we were veering away from magidex syntax. Scryfall actually supports a lot of the extra syntax we were adding. My example ("F:pd SET:EMN") actually works perfectly in scryfall. So (1) this wouldn't do as much as it would have done when we were linking to magidex and (2) we haven't added much that scryfall doesn't support. So I'm going to close this out.

**Comment by silasary** [comment]
Scryfall has also been really great with supporting stuff.  The main place this would show up is in the `is:grouping` shortcuts, and I feel that if we ended up having one that they don't, there's a decent chance we could just ask them to support it.
