### ISSUE TITLE
Support mana: and mana=

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#111]
: means "has these symbols in the mana cost".

= means "the mana cost is exactly this"

Probably no need to support {1}{B}{B} but must support 1BB.

Note: this works on magiccards.info but not on magidex.

**Comment by silasary** [comment]
Support for "{1}{B}{B}" probably isn't that useful, but The moment people start searching for more complex symbols {W/B}, etc, it becomes useful to support that syntax.

**Comment by bakert** [comment]
Added by b877d57. All sane syntaxes supported, I think.
