### ISSUE TITLE
Fix the issues at https://www.codacy.com/app/clockwork-singularity/Penny-Dreadful-Tools/issues

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1154]

**Comment by bakert** [comment]
This is tricky because we don't have a way to run the same checks locally. I looked at installing the npm module but its available default sets of rules didn't seem to line up very well with what codacy is checking.

**Comment by silasary** [comment]
I'll go through the codacy control panel, and make an .eslintrc file that lines up with the enabled patterns

**Comment by bakert** [comment]
This is suggesting, amongst other things, that we use ES6 shorthand method declarations which don't work in IE and never will. So we'd want to tweak these rules if at all possible.

**Comment by bakert** [comment]
I think we've decided not to pursue this. If codacy lets us merge we're ok.
