### ISSUE TITLE
Rewrite squash_people to work with MySQL

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1155]
#TODO: Rewrite SQL for squash to work on MySQL
    return
    # partials = person.load_people('mtgo_username is NULL')

    # for p in partials:
    #     source = p.decks[0].source_name
    #     tapped_username = p.name
    #     guess = person.load_people('LOWER(mtgo_username) = "{0}"'.format(tapped_username))
    #     print("{0}: {1}".format(tapped_username, len(guess)))
    #     if len(guess) == 0 and source == "Tapped Out":
    #         raw_data = tappedout.scrape_user(tapped_username)
    #         if raw_data['mtgo_username'] is not None:
    #             guess = person.load_people('LOWER(mtgo_username) = "{0}"'.format(raw_data['mtgo_username']))

    #     if len(guess) > 0:
    #         print(guess[0].name)
    #         squash(guarantee.exactly_one(guess), p)

**Comment by silasary** [comment]
This is important again, now that we have mtggoldfish usernames as well.

**Comment by bakert** [comment]
What should this do? Just assume people with the same username on two different services are the same person? What if it's "pokemon" or "winner"?

**Comment by silasary** [comment]
The automated code would just take people with identical names and squash them. (Which is important for when people access `/people/<name>/`)

Squashing people with dissimilar names (For example, `igotbored` / `igotbored_`), is something that can be done by hand, and only really relevant if people want to be squashed.

**Comment by silasary** [comment]
The important thing is that we never have two different entries in `person` who have the same `name`.

**Comment by bakert** [comment]
The problem I see is when we do that and it isn't correct. But I guess it's pretty undo-able if it happens, we can just separate all the decks from source X into another person entry. Cool.

**Comment by bakert** [comment]
e43e8d6c. Leaving this open to run it on prod. Unless it's already scheduled?

**Comment by silasary** [comment]
If it's set up as a maintenance task, it'll be folded into the existing once every 24 hours cron.
