### ISSUE TITLE
Smoke test is failing

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1161]

**Comment by bakert** [comment]
Fails to connect to MySQL. Possibly a config.json issue. 'decksite_database'.

**Comment by bakert** [comment]
On SQLite we get:

shared.pd_exception.DatabaseException: Failed to execute `CREATE DATABASE cards` because of `(1044, "Access denied for user 'travis'@'%' to database 'cards'")`

So it's probably a permissions issue for the user `travis`.

@silasary can you remedy?

**Comment by bakert** [comment]
I removed the reference to /people/bakert99 (which won't necessarily exist) from the smoke test to see if that makes it work.

**Comment by bakert** [comment]
Working out if this is still a problem is contingent on fixing #1195. I'll look at this again when that is in a better state.

**Comment by silasary** [comment]
Yep, this was fixed.
