### ISSUE TITLE
Travis build blocked on db error in multiverse (MySQL)

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1195]
shared.pd_exception.DatabaseException: Failed to execute `INSERT INTO face (search_text, starter, text, mana_cost, hand, cmc, life, loyalty, card_id, toughness, position, name, name_ascii, type, image_name, power) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)` with `['Reveal a card from your hand. Search your library for a card with the same name as that card, reveal it, put it into your hand, then shuffle your library.\nHellbent — If you have no cards in hand, instead search your library for a card, put it into your hand, then shuffle your library.', None, 'Reveal a card from your hand. Search your library for a card with the same name as that card, reveal it, put it into your hand, then shuffle your library.\nHellbent — If you have no cards in hand, instead search your library for a card, put it into your hand, then shuffle your library.', '{1}{B}', None, 2, None, None, 1, None, 1, 'Infernal Tutor', 'Infernal Tutor', 'Sorcery', 'infernal tutor', None]` because of `(1452, 'Cannot add or update a child row: a foreign key constraint fails (`cards`.`face`, CONSTRAINT `face_ibfk_1` FOREIGN KEY (`card_id`) REFERENCES `card` (`id`))')`

**Comment by bakert** [comment]
https://travis-ci.org/PennyDreadfulMTG/Penny-Dreadful-Tools/jobs/259988528

**Comment by bakert** [comment]
E   _mysql_exceptions.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`cards`.`face`, CONSTRAINT `face_ibfk_1` FOREIGN KEY (`card_id`) REFERENCES `card` (`id`))')

**Comment by silasary** [comment]
Oh dear.  What have you done now?

**Comment by silasary** [comment]
This appears to have happened after you turned on the warnings as errors.

**Comment by silasary** [comment]
It appears to be failing because of this:
https://travis-ci.org/PennyDreadfulMTG/Penny-Dreadful-Tools/jobs/260130471#L671-L697

```
E   CREATE TABLE IF NOT EXISTS deck (
E       id INTEGER PRIMARY KEY AUTO_INCREMENT,
E       person_id INTEGER NOT NULL,
E       source_id INTEGER NOT NULL,
E       identifier VARCHAR(200) NOT NULL,
E       name TEXT NOT NULL,
E       created_date INTEGER NOT NULL,
E       updated_date INTEGER NOT NULL,
E       competition_id INTEGER,
E       url TEXT,
E       archetype_id INT,
E       resource_uri TEXT,
E       featured_card TEXT,
E       score INT,
E       thumbnail_url TEXT,
E       small_thumbnail_url TEXT,
E       wins INTEGER,
E       losses INTEGER,
E       finish INTEGER,
E       FOREIGN KEY(person_id) REFERENCES person(id),
E       FOREIGN KEY(source_id) REFERENCES source(id),
E       CONSTRAINT deck_source_id_identifier UNIQUE (source_id, identifier)
E   )` with `[]` because of `(1071, 'Specified key was too long; max key length is 767 bytes')`
```

**Comment by silasary** [comment]
At a guess, this is a regression caused by converting the table to uft8mb4?

**Comment by silasary** [comment]
fixed!
