### ISSUE TITLE
Support formats other than pd in search

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#120]
With banned lists we can do Vintage and Legacy.

For Standard we have the release dates and whatsinstandard info already which is probably sufficient?

For Modern (and maybe for Standard too) we'll need to know which sets are "supplemental" and not legal in those formats. Not sure if that is in mtgjson's output but it probably is.

**Comment by silasary** [comment]
If we pull AllCards-x MtgJson will provide card legalities :)

**Comment by bakert** [comment]
Thanks for the suggestion. I did this in #122.
