### ISSUE TITLE
[Archetype admin panel] Clicking suggested archetype should prefill the dropdown, not navigate to page.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#1204]

**Comment by bakert** [comment]
What if you want to go look at the other decks in the archetype/common cards/etc. in order to check if the deck belongs there?

Maybe the best thing to do would be to start the dropdown on the suggested archetype?

**Comment by bakert** [comment]
I wonder if this was inspired by trying to set archetypes on a phone. On desktop it's a simple matter of typing a few letters but it is awkward on a phone. Defaulting to suggested archetype feels a bit dangerous so I'm going to leave this for now. Feel free to reopen if it's really pissing you off.
