### ISSUE TITLE
Show Tournament times in user's local time.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#1209]
https://pennydreadfulmagic.com/tournaments/ currently shows a shotgun of timezones, (eg `4pm Pacific, 7pm Eastern, Midnight UK, 1am Europe`).  

This is not particularly helpful for people who don't fall neatly into one of these timezones. (like me)

We should use the browser's local timezone to show a Start Time that is useful to the reader.

**Comment by bakert** [comment]
I feel like for 95%+ of English-speaking Magic players one of these times makes sense. But your idea is nice too :)

**Comment by bakert** [comment]
Let's also show "Next tournament: PDT in 7 hours" or similar.

**Comment by bakert** [comment]
22bd3c6 does this.
