### ISSUE TITLE
Improve rendering time of /cards/

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1217]
is there any way to improve the rendering time of cards - even offline it takes ages, it's browser time

**Comment by silasary** [comment]
XHRs?

**Comment by bakert** [comment]
We do a kind of hiding thing with decks that works pretty well and it fades in just after loading. Maybe we can just use that. I'll investigate.

**Comment by bakert** [comment]
Time taking using this method on a slow-ish internet connection is actually long enough that it feels like it'd need a spinner. Hm.

**Comment by bakert** [comment]
Fade in behavior currently attached to .fade-repeats on &lt;table&gt;.

**Comment by bakert** [comment]
I cut a lot of the data here and much reduced the server time. I also cut some expensive javascript. And the image previews. And added a spinner. It's still not a snappy page but it's respectable enough that I'm closing this ticket.
