### ISSUE TITLE
Decide end of season prize structure for tournament series and (probably) split PDM and PDS into separate series with or without the aid of longtimegone

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1220]

**Comment by silasary** [comment]
They should definitely be a separate series.

As it currently stands, people who can't compete in both do terribly on the season leaderboard.

**Comment by bakert** [comment]
I think we need a more general think about how we want end-of-season to go.

Nathaniel and I have an open question on what we're doing at the end of season and I should nail that down with him.

PDT used to have the following structure:

1st: 14 bot credits
2nd: 10 bot credits
3rd: 8 bot credits
4th: 6 bot credits
5th: 5 bot credits
6th: 4 bot credits
7th: 2 bot credits
8th: 1 bot credit

I'll try and square getting triple that from Nathaniel (now there are three tournaments) but it's possible he'll want to stick to the same commitment instead of triple.

PDT use(d|s) the following points system:

Entering the tournament: 2 point
Playing in a round: 1 point
Winning a round: 3 points
Receiving a bye: 1 point
1st: 11 points
2nd: 8 points
3rd-4th: 5 points
5th-8th: 2 points

Options I see (not necessarily mutex) are:

(1) Apply this system to each system individual tournament series and pay out at season end.
(2) Apply a simpler system (3 * wins + draws, probably) to each individual tournament series and pay out at season end.
(3) Use the additional credit for a higher payout "final" (open, with byes for top performers probably)  or "invitational" (top performers only) tournament at the end of each season.
(4) Combine all the tournaments into a single leaderboard. Maybe factor in the league. Give prizes or invites or byes to top performers as above.

It comes down to what we want to incentivize. I'd say we want to maximize the total number of tournament entries both via total number of people entering and total number of times each person enters. The former more important than the latter. Keeping the series separate is motivational for people that permanently can't make one of the tournaments. Combining might make people give up who can't compete because they can only make one. Perhaps we should literally just add up "matches played" at season end and divide the credit. That rewards success, and rewards any form of participation, and never becomes pointless because you can always earn more credit by playing the remaining tournaments (assuming there are enough to get up to 1 more tik). That might not be as exciting/motivational as a true leaderboard though.

**Comment by bakert** [comment]
Prizes are 3x normal tournament prizes and go to top 8 finishers.

Point per entry, point per win. Largely this works out as "players with most wins" but it does vary from that a little.

Code is b3a0b9cc.

**Comment by bakert** [comment]
The code can easily be used to get leaderboards for past seasons but I haven't added that yet.
