### ISSUE TITLE
Dross Hopper and Hero of Iroas are not marked as legal in Legacy/Vintage

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#123]
Needs investigation. Could be an mtgjson data issue.

**Comment by Pseudodude** [comment]
Where are you seeing this? The legality information looks right in AllCards-x.json version 3.6.2, !search f:legacy iroas / !search f:legacy hopper include the respective cards in the search results, and card_legality looks correct in my local db.

**Comment by bakert** [comment]
This magically went away. I was not drunk I swear.
