### ISSUE TITLE
The database should know as much as it can about data to catch issues early

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#13]
- Because of the way we create the card table every column ends up nullable but some (like name) should not be.

**Comment by bakert** [comment]
The set of columns that can be marked as not nullable is:

card: layout, name, type.
set: name, code, release_date, border, type
printing: system_id, rarity, artist

**Comment by bakert** [comment]
Additionally face.name should be UNIQUE

**Comment by bakert** [comment]
I added this capability just now and marked the not nullable columns as such. I'm going to leave this open to add UNIQUE to face.name.

**Comment by bakert** [comment]
UNIQUE constraints are in 3b64f91.
