### ISSUE TITLE
Store everything from mtgjson.com

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#136]
From AllSets-x.json we already store format legality but there's also ...

**rulings** [ { "date" : "2003-04-15",
"text" : "Does not tap." } ]  The rulings for the card. An array of objects, each object having 'date' and 'text' keys.
**foreignNames**  [ { "language" : "Italian",
"name" : "Wurm Devastatore",
"multiverseid" : 200475 } ] Foreign language names for the card, if this card in this set was printed in another language. An array of objects, each object having 'language', 'name' and 'multiverseid' keys. Not available for all sets.
**printings** [ "ICE", "CHR" ]  The sets that this card was printed in, expressed as an array of set codes.
**originalText**  "{8}: Do 4 damage to any target." The original text on the card at the time it was printed. This field is not available for promo cards.
originalType  "Mono Artifact" The original type on the card at the time it was printed. This field is not available for promo cards.

There's also booster information under 'booster' but we don't do anything with it.

Also we have not accounted for 'variations' on card - an array of variant versions of a card by multiverse id (like Fallen Empires multiple arts). Also all the fields in "extras".

**Comment by bakert** [comment]
I guess we have printings via AllSets.json.

**Comment by silasary** [comment]
Rulings and Original Text are probably the only ones we care about.
And even then, Original Text might be a bit of a stretch.

**Comment by bakert** [comment]
If we want these we can add them in the future.
