### ISSUE TITLE
The CMC of a land is 0 not NULL

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#138]
I'm not sure about Planes or Avatars, NULL kind of makes sense there. But a land doesn't have an undefined CMC. It has a well-defined CMC of 0.

This is a bug in the mtgjson data. They have a ticket open that has not been particularly well received: https://github.com/mtgjson/mtgjson/issues/118

This ticket is to prompt us to either (best) fix upstream or add a workaround.

**Comment by bakert** [comment]
Actually, I already work around this is cmc<2 and cmc>=0 etc. so it's not really worth having our own ticket. Ignore.

**Comment by silasary** [comment]
This has been resolved upstream (3.10.2).  We should remove our workaround.

**Comment by bakert** [comment]
There's still two NULL CMC faces.

     mysql> SELECT name FROM face WHERE cmc IS NULL;
     +---------------------------+
     | name                      |
     +---------------------------+
     | Westvale Abbey            |
     | Ormendahl, Profane Prince |
     +---------------------------+
     2 rows in set (0.00 sec)

I've logged https://github.com/mtgjson/mtgjson/issues/435

**Comment by bakert** [comment]
Diff to remove our hack when we're ready is just:

    diff --git a/magic/multiverse.py b/magic/multiverse.py
    index 895f5851..afba5e49 100644
    --- a/magic/multiverse.py
    +++ b/magic/multiverse.py
    @@ -91,8 +91,6 @@ def update_database(new_version):
         for _, s in sets.items():
             insert_set(s)
         check_layouts() # Check that the hardcoded list of layouts we're about to use is still valid.
    -    # mtgjson thinks that lands have a CMC of NULL so we'll work around that here.
    -    db().execute("UPDATE face SET cmc = 0 WHERE cmc IS NULL AND card_id IN (SELECT id FROM card WHERE layout IN ('normal', 'double-faced', 'flip', 'leveler', 'token', 'split'))")
         rs = db().execute('SELECT id, name FROM rarity')
         for row in rs:
             db().execute('UPDATE printing SET rarity_id = ? WHERE rarity = ?', [row['id'], row['name']])

**Comment by bakert** [comment]
I commented on the task I created with a probably-good idea of how to fix it. If the mtgjson team don't respond I'll send a pull request.

**Comment by bakert** [comment]
Submitted a PR for this https://github.com/mtgjson/mtgjson/pull/486

**Comment by bakert** [comment]
PR was merged and released.

412abf5 removes our workaround.
