### ISSUE TITLE
/ Running out of disk space (2.4G)

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1405]
I dropped the price table which got us to 2.4G (we were at 1.2G free) but we probably need to do something about it sooner rather than later.

**Comment by silasary** [comment]
Big Query.

**Comment by bakert** [comment]
This became serious again today. Deleted a 2.4G backup of prices sqlite and dropped the price table (and recreated empty) which got us 1.8G because the backup deletion didn't seem to recognize that the file was gone??

**Comment by bakert** [comment]
Now down to 1.5G after latest deletion. We no longer record all prices so regular deletion should get less important.

**Comment by bakert** [comment]
```/dev/root        45G   24G   19G  56% /```

Woop!

@silasary do you want me to send you some money?
