### ISSUE TITLE
Request: put page numbers on the /cards page

### ISSUE THREAD

**Issue by Rooby-Roo** [PennyDreadfulMTG/Penny-Dreadful-Tools#1412]
Would reduce page loading time considerably, or so I would think. I opened every main page of the site simultaneously, and /cards was by far the longest-loading one, due to the sheer mass of text on the page. Even if you just had the page list the first 100 cards or so each, that would reduce the lag considerably.

**Comment by bakert** [comment]
I sped up this page from its previously terrible load time to 5s to load. It doesn't finish rendering for a few seconds after that, though, and remains a bit unwieldy (sort by column pauses before doing its job, that kind of thing).

**Comment by bakert** [comment]
This page currently takes a few seconds of server time, then quickly gets to a "Loading" spinner, but takes a long time (10s) to render the page. It's not ideal but it's workable.

If at all possible I want to keep all the cards in one page to allow sorting of all cards by each column. If we do change this we'll do it as part of a perf drive. Closing this for now.
