### ISSUE TITLE
Always @mention when saying "No matches"

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#143]

**Comment by silasary** [comment]
No it doesn't.

> [2:47 AM] DIEGO "Janky" BRANDO: [Ghirapur ]
> [2:47 AM] BOTmtgbot: Ghirapur Aether Grid :white_check_mark:, Ghirapur Gearcrafter :white_check_mark:, Ghirapur Guide :no_entry_sign:, Ghirapur Orrery :no_entry_sign:
> 
> [2:47 AM] Tom (bakert99): we're debating adding a fuzzy matching to the card name thing so you can say [Cirricular Logic] or [Define Bloodlord] and still get a sensible response
> [2:47 AM] BOTmtgbot: No matches.

That was in response to you.

**Comment by bakert** [comment]
Oh. I thought we @mentioned in that case. I guess that's only for searches and we should potentially add it for []?

**Comment by bakert** [comment]
I did this.
