### ISSUE TITLE
functional_test is slow but fires first when running all unit tests

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#145]

**Comment by silasary** [comment]
Feel free to rename the files if you feel it's worth it.

**Comment by bakert** [comment]
It's also in my `make push` that I run when sending things to github so I'm going to spend time speeding it up rather than moving it around I think.

**Comment by bakert** [comment]
Fixed this by excluding updateprices. Now back to a couple of seconds.
