### ISSUE TITLE
Update README.md with the additional capabilities of the bot

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#149]
Would be nice to do this from !help maybe even automatically (??)

**Comment by bakert** [comment]
post-commit hooks, man

**Comment by silasary** [comment]
Or Jenkins can do it.

**Comment by bakert** [comment]
That is probably better.

**Comment by silasary** [comment]
Ok.  We have a generate_readme.py,  and it can be called via `make readme`.

Due to the fact that jenkins checks out individual commits, rather than the branch proper, trying to get it to automatically run the script turned out to be harder than it should be.

**Comment by bakert** [comment]
Perfection.
