### ISSUE TITLE
Establish color palette norms for badges, leaderboards, errors, hover states (CSS)

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1491]
We are currently using mtg G mana color, opacity gradations of #0f0 for the first two and #f00 for the last two. None of these things is great or has been particularly considered.

**Comment by silasary** [comment]
Preferably something colourblind friendly- Let's use one of the [Brewer Palettes](http://colorbrewer2.org)

**Comment by bakert** [comment]
I removed the lime green from the leaderboard in favor of positions markers in the margin.

Hover states are done.

Errors are still #f00 red which is ok but not great. They are very noticeable at least.

Badges are still magic-card green which we definitely don't want.

**Comment by bakert** [comment]
Badge is now just a floating number. I wouldn't use it across the site, I don't think, but it's fine for admins. All bad use of color is gone now. Not sure about red but leaving it in.
