### ISSUE TITLE
TTL for whatsinstandard, legal cards, bugs and mtgjson can be much longer

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1498]
Or at the very least we can use cache if we fail to scrape rather than failing. Would help with offline dev.

**Comment by bakert** [comment]
A little local experimentation shows me that CacheControl will not re-use the cache between python runs. I don't know to what extent this affects the uwsgi processes but I wonder if this is why we seem to fetch it so often. Or maybe we only fetch it a lot in dev where the webserver restarts all the time. It's set to live 14 days in the code.

**Comment by bakert** [comment]
See also https://stackoverflow.com/questions/28900091/what-can-go-wrong-if-i-use-simplecache-in-my-flask-app.

We should probably be using Redis here?

**Comment by bakert** [comment]
https://pythonhosted.org/Flask-Cache/ has support for Redis

**Comment by silasary** [comment]
We are using redis for What's in Standard. 
Have been since I needed to do dev on my flight across the Pacific a couple months back 😉

**Comment by bakert** [comment]
what's in standard is the one that used to really bug me so I'm going to close this as it's now cached in redis for 24 hours.
