### ISSUE TITLE
Bug page doesn't include name in description in some places where it should

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1500]
Example: "'s cost reduction doesn't consider split cards that are discarded" would be better with the name repeated at the beginning of the description (Hollow One).

**Comment by bakert** [comment]
This is coming from whatever generates bugs.tsv as it has the same behavior. Names in the middle of text are preserved. I've asked @silasary how bugs.tsv is generated.

**Comment by bakert** [comment]
Katelyn fixed this.

**Comment by silasary** [comment]
This leaves some things to be desired where names are now included where they really shouldn't be, but I'll try to reword the descriptions in a way that the card name is now part of the sentence, rather than being a data prefix.
