### ISSUE TITLE
PDM thinks Penny Dreadful Saturdays 6.02 had 9 people in the top 8.

### ISSUE THREAD

**Issue by BackAlleyG** [PennyDreadfulMTG/Penny-Dreadful-Tools#1539]
For some reason in [Penny Dreadful Saturdays](https://pennydreadfulmagic.com/competitions/242/) pdm thinks metalatog also made top 8 and is one of the 3/4 position people which makes 9 people. [Here](http://gatherling.com/eventreport.php?event=Penny Dreadful Saturdays 6.02) is the actual order/placing in gatherling for reference.

![incorrect saturday](https://user-images.githubusercontent.com/31076829/32421718-0ff4a942-c269-11e7-93cc-cf879ab1274b.PNG)

**Comment by bakert** [comment]
Three people dropped with records that would get them in to top 8 to cause this fun and games. Updated manually but if we ever re-scrape from Gatherling this will return. Doesn't seem worth making special code for as it should be rare!
