### ISSUE TITLE
Create some kind of schedule to update and test versioned libraries

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1546]
Python, MySQL, jQuery, everything in footer.mustache, everything in requirements.txt can all fix security holes, become faster, get better, etc. And big migrations are much harder than small ones. We should make a schedule to regularly update to latest stable versions and test.

**Comment by bakert** [comment]
We should also fix our versions in requirements.txt with == to avoid usual devs having working envs but everything exploding when a new dev tries to set up.

**Comment by silasary** [comment]
In addition to the above commit, I've set up requires.io to automatically monitor the dependencies, and create PRs when any of them updates.

As for mysql, python, and other distro packages, I already do a full `zypper update` once per month (usually on the 30th).

The server runs OpenSUSE Tumbleweed (rolling release), so we don't need to worry about doing dist-upgrades or any of that silliness.

**Comment by bakert** [comment]
This is awesome :D
