### ISSUE TITLE
Better About Page(s)

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1595]
About PD needs to be something like –

Penny Dreadful is

   AN ULTRA-BUDGET MAGIC ONLINE FORMAT

   WITH MORE THAN 10,000 LEGAL CARDS

   INCLUDING HYPERGENESIS, CHAIN LIGHTNING AND CRUEL ULTIMATUM

   WITH FOUR WEEKLY TOURNAMENTS

        Prizes

   A 24/7 LEAGUE COMPETITION

        Current League
        etc.

   SUPPORT ON MAJOR SITES

        Scryfall
        Magidex
        etc.

   A LIVELY AND FRIENDLY COMMUNITY

        Discord

        Subreddit

What are you waiting for?

    Discord

    League

    How to Get a Game

    Getting Started with Magic Online

**Comment by silasary** [comment]
Is this for pdmtgo.com?

**Comment by bakert** [comment]
We have /about/ right now that does a little sales job on pd. I was gonna spruce it up. If we worked up something great I could see us putting it on the front of pdmtgo.com or ... something. Not quite sure how to reconcile the two sites even if we were given control of both. I guess have one become a non-canonical alias for the other eventually??

**Comment by bakert** [comment]
#1605, which I'm going to close, is one idea.

**Comment by bakert** [comment]
We have /about/ and /about/pd/ and the intro box now. We are all good.
