### ISSUE TITLE
Intro to MTGO

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1624]
A complete guide to getting started with PD assuming no knowledge of MTGO.

CynicalElephant –
"I bought a MODO account for the express purpose of playing this format. But I found MODO's learning curve in terms of acquisition of cards and actually playing the game to be so frustrating, I stopped trying. This is a lot to ask, but if I could follow a step by step guide from first turning on the game, to playing in these tournaments, that would get me playing the game and enjoying the format!"

Also Evil_hechman in response:

"I'm in the same position and would love this. This format has everything I want. Brewing potential and meta diversity"

https://www.reddit.com/r/magicTCG/comments/7bwv7j/penny_dreadful_november_update_ultrabudget_mtgo/

We should do this or at least coral some existing resources and link them.

**Comment by stash86** [comment]
I'll try to do this

**Comment by stash86** [comment]
Please check the updated guide. I have add the capabilities for viewer to be able to comment on the guide

https://docs.google.com/document/d/1GGvhaISyESrrvPAkauP5LWKAixh6rcH1Q2jfbfpUOoA/edit?usp=sharing

**Comment by bakert** [comment]
Oh, nice!

I'll update the link text!

**Comment by bakert** [comment]
Updated.
