### ISSUE TITLE
Performance checker should not log the same issue a zillion times

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#1818]
An interesting idea is when it finds and issue and then logs it to log nothing faster than that until that issue is closed. That's a bit weird though.

I'd like to be able to tell it "log the slowest thing in a given time period as a github issue"

Something that stops it spamming github anyway. Just "no more than one ticket an hour/day" would be ok.

**Comment by bakert** [comment]
In particular I can imagine the google crawler opening a few thousand issues in one visit ...

**Comment by bakert** [comment]
We could store a timestamp and the title in flask.g and check for it being logged in the last hour and if so not do so. That would fail to tell us with quite the same urgency if the site were failing on one important page constantly. But it would solve some of the spamming.

Better would be to store a reference to the issue alongside the timestamp and update the issue (and the timestamp) when we receive an additional report. That would still be a lot of emails but it wouldn't be a lot of issue numbers.

**Comment by bakert** [comment]
Upgrading to a bug because the site going down caused us to get rate-limited by the github API we sent so many. We really need to not do that :)

**Comment by jgabrielygalan** [comment]
Some ideas: 
- If the issue can be identified uniquely by the perf parameters (kind + detail), then we could store it in a table linked to the issue. How to track and update this table? If the issue is closed and then the problem happens again, we could check the status of the stored issue and open a new one if it was closed.

- Another option would be to use github's API to search for such open issue, instead of storing it anywhere.

Both options would require that kind+detail is a suitable identifier.

**Comment by silasary** [comment]
For 500 errors, we can hash the stacktrace.  Not sure how to deal with perf stuff.

**Comment by bakert** [comment]
A simple approach that would give us 80% of what we want is to take the
subject line of the error and if there's an open ticket with that title
append a +1 of some kind to that ticket instead of opening a new one.

**Comment by bakert** [comment]
We worked around this by just sending them elsewhere and I cope in email. Closing.

**Comment by bakert** [comment]
Reopening for backlog.

**Comment by bakert** [comment]
We are happy with the current state of affairs with the separate repo for perf.
