### ISSUE TITLE
We need virtual cards for full split card data

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#185]
Unfortunately, populating this is messy.

**Comment by silasary** [comment]
Discussion from Discord:

> [10:29 PM] Katelyn (Silasary): I'm messing with Split cards again - Hopefully getting them working in a better way for commands(edited)
> [10:29 PM] Tom (bakert99): split cards are so fucked
> [10:30 PM] Tom (bakert99): I'm not even sure what the right thing is
> [10:30 PM] Tom (bakert99): Is Fire // Ice a multicolored card?
> [10:30 PM] Katelyn (Silasary): I think it's a per context problem
> [10:30 PM] Tom (bakert99): I think it is
> [10:30 PM] Tom (bakert99): but nothing else does
> [10:30 PM] Tom (bakert99): not either of the sites
> [10:30 PM] Tom (bakert99): not mtgjson
> [10:30 PM] Tom (bakert99): plus the fact that maro has said R&D is undecided on whether they could print "Fire" or not and that they might one day. As a single card. Makes everything more complicated.
> [10:30 PM] Tom (bakert99): It's like the actual truth is that it's undecided
> [10:31 PM] Tom (bakert99): c!urm should find Fire/Ice though I'm sure
> [10:31 PM] Tom (bakert99): and it doesn't anywhere :smiley:
> [10:31 PM] Tom (bakert99): Am I wrong?
> [10:31 PM] Katelyn (Silasary): Not sure
> [10:31 PM] Katelyn (Silasary): I think c!urm shouldn't, but ci!urm should?
> [10:32 PM] Katelyn (Silasary): But that's even more messy
> [10:32 PM] Tom (bakert99): i mean if i'm searching for targets for Supply / Demand
> [10:32 PM] Tom (bakert99): i want to find Fire / Ice because I can search for it
> [10:32 PM] Tom (bakert99): or whatever the mulitcolored search is
> [10:32 PM] Tom (bakert99): right so Fire // Ice can be found with Demand
> [10:32 PM] Katelyn (Silasary): Yeah, that's right
> [10:32 PM] Katelyn (Silasary): Maybe?
> [10:33 PM] Tom (bakert99): so that says to me that Fire // Ice is a multicolored card
> [10:33 PM] Katelyn (Silasary): Hmm.
> [10:33 PM] Tom (bakert99): but none of our sources agree
> [10:33 PM] Tom (bakert99): and neither does our code :smiley:
> [10:33 PM] Tom (bakert99): I also feel like Fire // Ice should be one entry in card not two
> [10:33 PM] Tom (bakert99): It's not simple though
> [10:33 PM] Katelyn (Silasary): Hmm.
> [10:34 PM] Katelyn (Silasary): I'm going to make a second pass that finds all split cards and creates new 'fake' entries of the combined card.
> [10:34 PM] Katelyn (Silasary): Because that's the only way to solve this, I think
> [10:35 PM] Tom (bakert99): then we'll get double hits, though :smiley:
> [10:35 PM] Katelyn (Silasary): I'm ok with that.
> [10:35 PM] Tom (bakert99): in some sense Fire // Ice should show for c!r
> [10:35 PM] Tom (bakert99): yeah maybe double hits is ok
> [10:35 PM] Tom (bakert99): i'm not sure
> [10:35 PM] Katelyn (Silasary): We can always fix that with uniquify :stuck_out_tongue:
> [10:35 PM] Tom (bakert99): it's weird to say "how many red cards are there" and get a number bumped by 1 as the answer
> [10:36 PM] Tom (bakert99): What goes wrong if we combine before inserting into card and never have separate entries for each side?
> [10:36 PM] Tom (bakert99): We dont' get Fire for c!r
> [10:36 PM] Tom (bakert99): but I am ok with that
> [10:36 PM] Tom (bakert99): Does it create any other problem?
> [10:36 PM] Katelyn (Silasary): But sometimes that's ok.
> [10:37 PM] Tom (bakert99): I guess the problem is where does the Oracle text go
> [10:37 PM] Tom (bakert99): all jumbled in one entry
> [10:37 PM] Tom (bakert99): all of this apllies to DFCs to a lesser extent, too
> [10:38 PM] Katelyn (Silasary): I think the right answer is to create a virtual card, then uniquify flattens all three copies of a split card if they come up.
> [10:38 PM] Tom (bakert99): Makes things like COUNT(_) complicated, though.
> [10:38 PM] Katelyn (Silasary): In what sense?
> [10:38 PM] Tom (bakert99): COUNT(_) WHERE color is red
> [10:38 PM] Tom (bakert99): will lie
> [10:39 PM] Tom (bakert99): unless it is legit to count Fire and Fire // Ice separately
> [10:39 PM] Tom (bakert99): which I don't think it is
> [10:39 PM] Tom (bakert99): What goes wrong if we only store "Fire // Ice" in card and not the halves?
> [10:39 PM] Tom (bakert99): c!r doesn't find Fire any more but I think that's ok
> [10:39 PM] Tom (bakert99): Anything else?
> [10:40 PM] Katelyn (Silasary): For deckbuilding I sometimes do count them separately though.
> I run [[Well]] in a deck with no Green sources.
> [10:40 PM] Tom (bakert99): It complicates DFCs because then they should NOT have an entry and should be in a subtable. But we could do that.
> [10:41 PM] Tom (bakert99): But if you run Well you are running a multicolored card that contains a color your deck doesn't produce. It is complicated for search.
> [10:41 PM] Tom (bakert99): Hmmmmm. Argh.
> [10:41 PM] Tom (bakert99): And don't get me started on Devoid :smiley:
> [10:41 PM] Tom (bakert99): "castable with" needs to be a thing potentially
> [10:41 PM] Katelyn (Silasary): If I'm looking for cmc<3 lifegain spells in !wb,  I expect to find Well.
> [10:41 PM] Tom (bakert99): which would need us to store something special about split cards
> [10:41 PM] Tom (bakert99): yeah I agree
> [10:41 PM] Tom (bakert99): sigh
> [10:42 PM] Tom (bakert99): ok let's go with entries for the sides AND for the whole card and see how much we hate it?
> [10:42 PM] Tom (bakert99): (i have caught up with you :D)
> [10:42 PM] Tom (bakert99): my objection to that is mostly theoretical
> [10:42 PM] Tom (bakert99): practically the problem would be the cards showing up twice
> [10:42 PM] Tom (bakert99): cmc<3 lifegain spells in !wg is now Alive // Well and Alive // Well and Alive // Well :stuck_out_tongue:
> [10:43 PM] Tom (bakert99): but uniqify hides that as you say
> [10:43 PM] Tom (bakert99): assuming we make uniqify know about this madness
> [10:45 PM] Tom (bakert99): if we pass everything through fuzzy names and a good uniqify as a matter of course we should be good?
> [10:45 PM] Tom (bakert99): and if we ever write anything that does COUNT(*) from card it'll just have to know about this
> [10:45 PM] Tom (bakert99): fuzzy matching would probably make Alive/Well match Alive // Well, too, so we don't really need to even do anything about the various ways to write split cards
> [10:45 PM] Tom (bakert99): Well // Alive won't though :smiley:
> [10:45 PM] Tom (bakert99): complicated

**Comment by silasary** [comment]
Here's what my current aim is:
`name: card_name[1] // card_name[2]` (Hopefully in the right order?)
`cmc: [1]+[2]` (This is what the cmc would be when cast as fused)
`text: [1]\n[2]` Just concatinate the two.
`type: [1] [2]` (In case we end up with an "Instant Sorcery")
`mana_cost: ?`  Naive approach is to concatenate. We might end up with {1}{M}{M}{3}{M}{M} though.
`color: [1] & [2]`
`color_identity: [1] & [2]`

All other properties can be copied from [1]?

**Comment by silasary** [comment]
@bakert Does this look right to you?

**Comment by bakert** [comment]
We talked about this on Discord. We're thinking about card and face tables to distinguish between these things. Most cards would have one entry in face but DFCs, flip cards (maybe?) and split cards would have multiple entries. So CMC in card for a split card would be sum, CMC in face table would be for each individual part. Oracle text will only appear in face, probably. More TBD.

**Comment by bakert** [comment]
I did this. Whether it was wise or not remains to be seen. But we now have separate `card` and `face` tables.

**Comment by bakert** [comment]
Note that name is derivable from faces + layout. And cmc is derivable from faces. So there's actually basically nothing in `card` apart from the card's id and the historical pd_legal column which we can remove soon in favor of card_format entries.
