### ISSUE TITLE
Search feature "playable with _ mana"

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#198]
phyrexian mana, twobrid, devoid, regular hybrid

playable with W returns Gitaxian Probe and Reaper King.

**Comment by bakert** [comment]
This request essentially relates to how color identity and color don't quite describe what you actually want when deckbuilding. You don't want to see Herald of Kozilek for your Mono G deck because it's colorless and you do want to see Gitaxian Probe even though it's Blue. Color identity is better than color but it's ultimately tied to the Commander notion and not practical deckbuilding.

**Comment by bakert** [comment]
(There's an open question of how valuable this is given that `ci` or `c` get you most of the way there and magidex/magiccards don't support this other notion.)

**Comment by silasary** [comment]
Considering that we're starting to build a website, I'm thinking we may end
up having our own card search site in the near future.
If that happens, I'm not sure how much it matters whether magidex supports
syntax or not.

**Comment by bakert** [comment]
I still think this is an interesting feature. If I know my deck has R and G mana in it I would like to be able to say `o:"draw a card" playable:rg` and get back Gitaxian Probe as well as Zap and Elvish Visionary. There's nothing in any search engine's existing syntax for this, I don't think.

**Comment by bakert** [comment]
Implenting this is a little tricky. You can't sensibly play Mistmeadow Witch in a mono-U deck but you CAN play Kaleidostone in a mono-U deck. Are we going so far as to detect costs before/after the colon in activated abilities? I think not, I think this should say Mistmeadow Witch IS playable in a mono-U deck. So we're really talking about these things:

  * Don't count Phyrexian Mana as being a color.
  * Hybrid cards are in either of their colors.
  * Twobrid cards are playable in anything.
  * Lands and colorless artifacts are playable in anything.
  * Devoid cards are only playable in the colors of their top-right mana symbols.

And I think that's it. So we can do a `mana:` query but perform some trickery on mana cost to elide phyrexian mana and turn twobrid into colorless. That will also get us the devoid. We have to also match empty string/colorless only after the trickery as those are playable in any deck. Not totally sure how we will handle hybrid.

**Comment by bakert** [comment]
I'm really torn between adding this feature in full and switching over to scryfall altogether. I'm going to try and talk to them about this and about split cards (which is another longstanding ticket of ours that they handle better than us but not perfectly) and see if that pushes me one way or the other. I really want better split card support, support for `tix:` and this. If we could get them all from there and abandon `!search` I'd be happy. Having to split your searches between `!scry` and `!search` depending on what behavior you want is silly.

**Comment by bakert** [comment]
In the broadest possible sense something like this might be featured in Scryfall's (high priority) deckbuilder which in turn would probably have an API. All a bit maybe. I think maybe I push ahead with this and `tix` too and anything else we need for parity with Scryfall until such time as they make our search look embarrassing. But I'm still pondering the switchover.

**Comment by silasary** [comment]
At this point, I think we should improve our own, if only for speed reasons.

**Comment by bakert** [comment]
45721064.
