### ISSUE TITLE
Providing the full name of Split Cards [Fire // Ice] doesn't work

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#2]
- Split cards. The bot expects one half [Fire] or the other [Ice] but the image server expects both. So either the bot doesn't respond or if it does it doesn't get an image. We should support: [Fire], [Fire / Ice] and [Fire // Ice] and variations ignoring whitespace.

**Comment by silasary** [comment]
- Card names have an order (the composite card is Fire / Ice not Ice / Fire) which we do not store currently.

**Comment by bakert** [comment]
I'm gonna work on this if no one else is. If you've got this fixed on local already let me know soon!

**Comment by bakert** [comment]
I didn't actually do this in the end.

**Comment by bakert** [comment]
I'm taking the assignment to mean you're working on this @silasary. LMK if not.

**Comment by silasary** [comment]
Yeah, I'm working on it.  And I kinda got distracted by fixing up oracle in the process.
