### ISSUE TITLE
We should report 5xx errors on the site to github as we do slow pages and failures in the bot

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#2052]

**Comment by bakert** [comment]
This is pretty easily done with:

    repo.create_issue('500 error', str(e), 'decksite')

in main.internal_sever_error

BUT that code is never called because we run in debug mode on prod.

If we stop running on debug mode it will be called. We should perhaps consider that. Would it stop code reloading working without a restart?

**Comment by bakert** [comment]
I added this. We need to move to uwsgi for it to really do anything though (so we get 500 hot code swap without being in debug mode).

**Comment by silasary** [comment]
6eaf9547299fb0b9b0c82060d9a822f5fc6a574c
