### ISSUE TITLE
Menu should work differently on mobile/narrow screens

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#2057]

**Comment by bakert** [comment]
But let's use [MENU] and not the hamburger symbol because research.

And maybe leave top level menu items visible.

Or push the menu to the bottom of the page as per: https://lmjabreu.com/post/why-and-how-to-avoid-hamburger-menus/

**Comment by bakert** [comment]
4c397840 is a start but I expect still quite unpleasant to use on mobile.

**Comment by jgabrielygalan** [comment]
+1 to this, although I can't help much. In the phone, if I want to go to a submenu I have to click super quickly or I'll go to the first link in the submenu.

**Comment by bakert** [comment]
It's pretty criminal that I haven't done this yet :/

**Comment by bakert** [comment]
fdc3e3f5 is an "all inline" version with scroll to content when using links within the site. Not sure how I feel about it but it's better than the current menu on mobile so shipping it.
