### ISSUE TITLE
Implement strict canonicalization of cards names throughout the codebase

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#216]
And what the in-memory and in-database representation of card names should be.

This includes the in-memory list of legal cards and storage in name and name_ascii columns.

**Comment by bakert** [comment]
(I changed the in-memory legality from lowercase to mixed case in a recent commit. I think storing as lowercase but still keeping diacritical marks makes no sense although I may have introduced bugs.)

**Comment by bakert** [comment]
Current thinking:

A card _has_ a canonical English name including case and diacritics. 'Séance' is called 'Séance' and not 'seance'. Having 'seance' or even 'seanec' match the card Séance is a decision that should be made at query time. Maybe you're making a comparison with the aliases list and you don't want any fuzzy matching.

So I think that `name` in the database, entries in the aliases list, and legal_cards in memory should all store the correctly cased and accented version.

pdmtgo.com/legal_cards.txt is served as text/plain with no Content-type header. Going strictly by the RFC this means we should treat it as US-ASCII. It's not, however, it's utf-8. I think this is a recent change because we used to decode it as latin-1 (Cc @binarySwordsman). Regardless, we end up with case-respecting and diacritic-having values like 'Séance' when we are done. Another argument for mixed case with diacritics as the internal canonical representation of a card name.

Argument against:

`pdmtgo.com/legal_cards.txt` lists 'Jotun Grunt' and 'Jotun Owl Keeper' not 'Jötun'. If we removed diacritics and lowercased as soon as we received this list we would match the unaccented and lowercased version of face.name and these would be correclty marked as legal. Using a simplified form as the canonical representation and then making sure face.name is correct for display purposes defends us against other people's bad data.

**Comment by bakert** [comment]
OK mtggoldfish just punts on accents altogether listing Séance as Seance and Jötun Grunt as Jotun Grunt.

legal_cards.txt is inconsistent in its use of diacritics.

And this stuff is generally painful.

SO I now think the canonical representation of a card name should be database.unaccent(s).lower().replace(' ', '_')

Any input we receive should be converted to this representation at the earliest opportunity and it's all we should use inside the program for comparisons.

We will maintain the canonical names only in the name column of the face table and select it out at the last second for display only.

This means we will even form split card names like 'research_//_development' for comparison on oracle.search and elsewhere.

**Comment by bakert** [comment]
The work to do here includes:

(1) Canonicalize legal_cards.txt as soon as we fetch it and before updating legality.
(2) Canonicalize names in base_select().
(3) Change name_ascii to canonical_name and store the canonical name in that column.
(4) Change queries that use name_ascii to use canonical_name.
(5) Change canonicalize to do this exact transformation.
(6) Include a display_name (probably just called name) as well as canonical_name in base_select().
(7) Use name/display_name (result only) and canonical_name (comparison only) in the right places in base_select and other queries.

**Comment by silasary** [comment]
Yep.  The EMN legality list was stored as latin-1 (and would crash if
attempted to decode as utf-8)
If the Kaladesh list is now encoded as UTF-8, we should change our code,
but this is something I'm weary of doing until @BinarySwordsman gives a
definitive answer on what the encoding should be.

**Comment by bakert** [comment]
@binarySwordsman moved the re-accenting of cards like Séance into his code for season 2 which made the file he emits no longer latin-1. I've updated our code to read it as utf-8.

His re-accenting is on a case-by-case basis as far as I can tell which I think is a strong argument for canonicalizing this input (uncaccent(s.strip().lower()).replace(' ', '_') or something similar) upon receiving it and using that to make comparisons.

The alternative is to keep the official WotC English language name as the canonical name and flag issues with legal_cards.txt to @binarySwordsman when encountered.

Under the former scheme we'd currently be showing Jotun Grunt as legal but we might not have flagged that magidex has the wrong legality for it. I'm torn.

**Comment by bakert** [comment]
Canonicalizing to a simple format also defends against Aether-style changes, possibly. That was probably a one-off though.

**Comment by bakert** [comment]
Merging in a price issue. We can't find "Jotun Grunt" OR "Jötun Grunt" with !price because mtgg gave us "Jotun Grunt" and we stored it but fuzzy matching gives us "Jötun Grunt" which is not in the price table.

Possible solutions:

(1) Transform mtgg's "Jotun Grunt" to "jotun_grunt" and store that against price. Have cards know this form of their name and use that in price searches.

(2) Use fuzzy matching on mtgg input before storing in the db and store the result against price. This is maybe 60,000 selects every time we grab the prices but it doesn't happen on user time.

(3) Load the jotun_grunt-style representation of every card into memory when doing the mtgg parsing in a dict like this:

```
 { 'jotun_grunt': 'Jötun Grunt', 'dark_ritual': 'Dark Ritual', ... }
```

then transform the mtgg input in a similar fashion and do a lookup in this table to find the true card name to store in price.

(4) Store the jotun_grunt-style representation in card (like/instead of name_ascii) and post-process prices in some fashion after initially storing jotun_grunt-style.

I think I favor (2) here but someone let me know if I am hanging on to "the canonical card name is the canonical name in data" long after it has ceased to be worth it. I have my suspicions.

**Comment by bakert** [comment]
Prices works, legal cards works.

We are probably set up to encounter issues again with input that we _could_ have parsed to this_form but will be unable to parse to Thîs Förm and when we do I'll think about this again and kick myself. For now all is well and 'Jötun Grunt' is our official in-database and in-memory representation of that card.
