### ISSUE TITLE
It would be nice to have the github link in the bot's description

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#22]

**Comment by silasary** [comment]
I put it in the `Playing` field, which feels terrible, or we can make an `!help` command, which feels better.

**Comment by bakert** [comment]
Yeah, there doesn't seem to be an obvious place. I assume the Notes are per-User so if we add something there it doesn't show up for everyone else. I'm surprised there isn't something we can add that will show up when someone right-clicks the bot and choose profile. But perhaps there is not. !help or !about or both sounds like a good idea.

**Comment by silasary** [comment]
Implemented in #50
