### ISSUE TITLE
Several flip cards missing from db because of upstream issue

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#221]
(Discovered in the course of making Séance show up as legal.)

We should:

(1) Defend against this. Explode if we pdmtgo.com/legal_cards.txt and len(our legal cards) are not the same.

(2) Fix the issues causing this.

Currently we are missing:

Found 9809 pd legal cards in the database but the list was 9822 long
{'Jotun Grunt', 'Student of Elements', 'Kitsune Mystic', 'Ifh-Bíff Efreet', 'Cunning Bandit', 'Faithful Squire', 'Nezumi Graverobber', 'Orochi Eggwatcher', 'Initiate of Blood', 'Hired Muscle', 'Bushi Tenderfoot', 'Midnight Scavengers', 'Jotun Owl Keeper'}

Issues are: 

(a) No umlaut on Jötun in legal_cards.txt
(b) Flip cards have been deleted upstream ~~probably based on how the name is formed~~.
(c) Midnight Scavengers (but NOT Bruna/Gisela) seem to have some kind of meld-based problem again probably based on name.
(d) Ifh-Bíff Efree does not show up in search results because it has two aliases ~~weird accent probably causing issues.~~

**Comment by bakert** [comment]
Flip cards issue is because of https://github.com/mtgjson/mtgjson/issues/240

So we don't even acknowledge them as cards, let alone as legal cards.

**Comment by bakert** [comment]
mtgjson has 'Ifh-Bíff Efreet' and we have 'Ifh-Bíff Efreet' in the db. When decoded as utf-8 legal_cards.txt also yields 'Ifh-Bíff Efreet'. Not sure what is going on there.

**Comment by bakert** [comment]
Meld issues are to do with storing all parts of the melded card against the same card_id and are now tracked in #196.

**Comment by bakert** [comment]
I added logging (but no exploding because of the ongoing issues) in 4fc961c.

**Comment by bakert** [comment]
The Jötun Grunt issue will be fixed by #216.

This ticket continues to track the upstream problem with flip cards and the as-yet-undeciphered issue with Ifh-Bíff Efreet.

**Comment by bakert** [comment]
The issue with Ifh-Bíff Efreet is something to do with its presence in aliases. Now that we theoretically match all accented searches with unaccented searches it's probably sufficient to remove it from aliases but I'll investigate further.

**Comment by bakert** [comment]
The combination of the GROUP_CONCAT to form name and `LEFT OUTER JOIN card_alias AS ca ON c.id = ca.card_id` means that you will get 'Name // Name' as the name of a card with two aliases. And more for more than 2. So base_select will have to change to accommodate the possibility.

**Comment by bakert** [comment]
One correct answer here is GROUP_CONCAT(DISTINCT face_name, ' // ').

Unfortunately sqlite does not support DISTINCT and a custom delimiter at the same time. The default delimiter is a comma which appears in card names so is not very useful.

**Comment by bakert** [comment]
`REPLACE(GROUP_CONCAT(DISTINCT face_name), ',', ' // ')` will work because currently no cards whose official name is compound (aka split cards) have a comma in the name of any of the faces. It's a hack but it's probably a hack we can live with. Chances are either sqlite will implement GROUP_CONCAT(DISTINCT {column}, {delimiter}) (and ORDER BY!) or WotC will never print a split card with a comma in the name.

**Comment by bakert** [comment]
Bleurgh this also means face names and aliases may not contain commas or those things get messed up. Rethink required.

**Comment by bakert** [comment]
Aliases moved to fuzzy and this whole mess mostly-solved in 30d593.

Leaving this open for the upstream flip cards issue. I don't think we want to workaround this in our code as it will surely be fixed soon (?)

**Comment by bakert** [comment]
This is the cause of tappedout scraper failing to import Nezumi Graverobber, too.

**Comment by bakert** [comment]
We have to either fix this or work around it for decks v1. It's currently breaking the tapped out scraper.

**Comment by bakert** [comment]
I am going to hardcode fake this for decks v1. It's gross but very un-doable when mtgjson is updated.

**Comment by bakert** [comment]
35fd6cb contains the faking of the front face of the missing pd-legal flip cards. No attempt at completeness in printings, etc. is made. Should stop things blowing up, though.

**Comment by bakert** [comment]
Removing bug label while we wait for perfection from mtgjson as we have worked around this for now.

**Comment by bakert** [comment]
This is now fixed upstream so we should remove our hack.

**Comment by bakert** [comment]
b328654 removes our hack.

**Comment by silasary** [comment]
The whole hack, or just the flip cards?
Because I was using the same mechanism to add Gleemox to the DB.

**Comment by bakert** [comment]
I returned gleemox to working order before merging - thanks for letting me know!
