### ISSUE TITLE
Don't fetch from the internet unnecessarily

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#24]
Check the timestamp of legal_cards.txt and don't refetch if it's less than an hour old. Same for AllCards.json.

**Comment by silasary** [comment]
Thanks to #100, legal_cards.txt will only be grabbed if it's been updated server side since last time it was grabbed.

Due to the small size of mtgjson's `version.json`, I don't feel the need to expand this functionality to any other fetcher methods right now.
