### ISSUE TITLE
Multiverse ID is not correctly populated

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#25]
multiverse_id = cards[0].multiverse_id is not working with cards retrieved from the db so fallback images will fail. Multiverse id doesn't seem to be populated in the db.

**Comment by silasary** [comment]
It's not currently populated in the source JSON itself.

**Comment by bakert** [comment]
I'm pretty sure magicthegathering.io is built on top of mtgjson.com and that was able to retrieve multiverse id so there's something weird going on here ...

**Comment by bakert** [comment]
multiverse_id is in AllSets.json. It is NOT in AllCards.json. We should probably build the db from AllSets.json.

**Comment by bakert** [comment]
This is now in the `printing` table.
