### ISSUE TITLE
Meld cards behave strangely in prod but not on local

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#258]
The text is two names concatenated and the image is wrong (possibly just cached)

Cannot repro with master on local.

Weird.

**Comment by bakert** [comment]
@Pseudodude confirms this works for him on master. @silasary can you investigate on the prod server?

Repro is just:

[Brisela]

or any meld search. Names and images should be separate not a single Gatherer fallback image and weird concatenated name.

**Comment by silasary** [comment]
I clean installed the bot to a new directory.
Whatever it was caching is gone now.
