### ISSUE TITLE
Shorthands for less typing

### ISSUE THREAD

**Issue by zserdely** [PennyDreadfulMTG/Penny-Dreadful-Tools#279]
Some ideas for quicker use:

```
!s -> !search
!p -> !price
!o -> !oracle
!h -> !help
!res = !resources
```

There are no collisions yet in the most frequently used commands. 

Another idea is `!p ^` and `!o ^` which would give you the price/oracle of the last card you requested with `[]`. This could be extended to last card requested with `!p` and `!o` as well, but I don't think that's necessary. 
A common use case for the use of this would be checking if a card is legal and if not, then checking its price to see how close it is to rotating in.
Another useful application is seeing the oracle text of an old nonsense card after querying it.

**Comment by bakert** [comment]
I guess the generalized scheme here should be to take the provided command and scan to see if it unambiguously starts any of the known commands and if so treat it as if that command had been invoked. We could also do fuzzy matching for all the times people type `!proce` and `!prcie`. The bot doesn't really have destructive operations so being overeager to match what you say seems ok?

**Comment by bakert** [comment]
7a23ca8. No fuzzy matching.
