### ISSUE TITLE
I removed the use of insert_inventory even though I don't know what it is

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#288]
```
# if blob.get("inventory") is not None:
#     insert_inventory(blob['slug'], blob['inventory'])
```

The code for insert_inventory is still there.

**Comment by silasary** [comment]
This was to do with getting deck details via the resource_uri

We're currently doing it with the decklist export instead, so that code isn't required.

**Comment by bakert** [comment]
Removed in 6eb3c04.
