### ISSUE TITLE
Codacy won't let any code through

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#2924]
It reviews and passes a new gate – "Codacy PR Quality Review" but the old "codacy/pr" stays open forever.

<img width="713" alt="captura de pantalla 2017-11-29 a las 4 10 52 p m" src="https://user-images.githubusercontent.com/1541/33406050-eba79d00-d51f-11e7-98cb-88d7c7e4517a.png">

<img width="434" alt="captura de pantalla 2017-11-29 a las 4 08 05 p m" src="https://user-images.githubusercontent.com/1541/33405995-a0739276-d51f-11e7-9c04-d4570c105709.png">

**Comment by bakert** [comment]
Hoping @silasary can shed some light here but also fairly likely codacy just went crazy.

**Comment by silasary** [comment]
They renamed their hooks, and broke everything.

Should be fixed now
