### ISSUE TITLE
Do we want to allow comments on decks (and anything else)?

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#2927]

**Comment by bakert** [comment]
Opens the door to spam but we can insist on Discord verification to help with that a little.

Possibly makes the site feel less polished and more like a crapfest. Might generate interesting discussions. Might increase engagement with the site and pd in general.

I lean towards allowing comments with Discord auth.

**Comment by silasary** [comment]
Killing this
