### ISSUE TITLE
add_deck should possibly update the deck and it's updated_date instead of just returning deck_id when sent an existing deck

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#293]

**Comment by bakert** [comment]
Although there's an open question on whether a sufficiently updated deck is a new deck. What if someone "updates" their deck for the new season? Do we want to lose their old one?

It may not be worth doing this as the most high value decks (tournament decks) are set in stone and will never be updated. Tracking tappedout updates may be low value.

**Comment by silasary** [comment]
I feel like it should only do this on sources that are malleable, and haven't been updated in a while (24h?)

Pulling every deck every hour is too much.

**Comment by bakert** [comment]
The computer doesn't mind.
