### ISSUE TITLE
config.json.example needs updating

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#298]

**Comment by bakert** [comment]
We need tapped out login info? Although mine are empty and it seems to work?

**Comment by silasary** [comment]
Some of the APIs use them where possible I want to avoid those methods, but
it theoretically might be needed.

**Comment by silasary** [comment]
The original use was for retrieving the additional deck details (including
deck lists).

But you switched to calling the txt export, which didn't use that.

**Comment by bakert** [comment]
We're using it again now to get date_updated so we should add this to config.json.example.

**Comment by bakert** [comment]
a9c18e7.
