### ISSUE TITLE
Normalize Image sizes

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#3]
- EMN and other smaller images look stupid when joined. Normalize size before joining on the image server.

**Comment by bakert** [comment]
This now affects CN2 and KLD and EMN is ok (because magiccards.info updated with EMN images). But this will be an ongoing thing as magiccards.info trails Gatherer by weeks/months.

**Comment by bakert** [comment]
Improved from:

<img width="463" alt="screen shot 2016-09-29 at 8 04 27 am" src="https://cloud.githubusercontent.com/assets/1541/18944107/68a40fd2-861b-11e6-8abd-fa60cc0d86b5.png">

to:

<img width="877" alt="screen shot 2016-09-29 at 8 04 34 am" src="https://cloud.githubusercontent.com/assets/1541/18944108/68a61570-861b-11e6-8f05-9e86247665f6.png">

I'm still in discussions about making the all-singing, all-dancing MTG image solution.
