### ISSUE TITLE
Either complete the Add Deck form or remove it

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#300]

**Comment by silasary** [comment]
I'm inclined to change it to just a single text input taking a URL to the decklist, and pass that URL to the relevant scraper.

**Comment by silasary** [comment]
It's worth noting that TappedOut's "Latest Decks" is based on deckcycling, not on creation or updated dates.

There are a significant number of decks that are currently invisible.

**Comment by bakert** [comment]
I was thinking we might want to add interesting decks from weird places as one-offs. But we could just add it to tapped out if we want that, I suppose.

Interesting point about invisible decks. Maybe it's back to HTML scraping for tapped out ... :(

**Comment by silasary** [comment]
HTML scraping wouldn't help either.
Unless we scrape individual user pages of people we know play PD.

**Comment by silasary** [comment]
I'm thinking the bot might want to listen in discord for TappedOut links, and automatically POST them to `/add`.

Because most people who don't deckcycle will at least post them in chat.

**Comment by bakert** [comment]
Not a bad idea.
