### ISSUE TITLE
Implement full URL scheme

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#309]
First draft:

URL scheme:

- [x] GET /
homepage with list of most recent decks, competitions, and maybe people

- [x] GET /decks/
paginated list of all decks

- [x] GET /decks/<slug>
view of an individual deck

- [x] GET /decks/<id>
view of an individual deck

- [x] GET /competitions/
paginated list of all competitions

- [x] GET /compeititons/<slug>
view of an individiual compeition

- [x] GET /compeititons/<id>
view of an individiual compeition

- [x] GET /people/
pagingated list of all people

- [x] GET /people/<mtgo username>/
view of all decks from a specific person

- [x] GET /add/
form to add a deck to the db

- [x] POST /add/
add a deck to the db

- [x] GET /archetype/
list of archetypes

- [x] GET /archetype/<archetype>
show all aggro/combo/control decks

- [x] GET /decktype/
list of all decktypes

- [x] GET /decktype/<decktype>
show all s2 ub control lists, all s2 ooze combo lists, etc.

- [x] GET /search
search for decks by card, user, archetype, etc.

**Comment by bakert** [comment]
Only thing left to do here is search. Search should be fuzzy and work on mtgo usernames, deck names, archetype names and card names at least.

**Comment by silasary** [comment]
Did we decide not to do /decktype/?

**Comment by bakert** [comment]
Everything in earth refers to decktype as archetype. So I'm going to use
that name and complicate from the broad categories we have right now into
more specific archetypes.

**Comment by bakert** [comment]
Site search is e36c01. We are done here!
