### ISSUE TITLE
There is some kind of general problem with Aether.

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#31]

**Comment by silasary** [comment]
I'm gonna blame Kaladesh

**Comment by bakert** [comment]
Quite right.

**Comment by bakert** [comment]
We talked about potentially applying something like 'standardize' to all mtgjson, legal_cards and user input as soon as we have the names and forming canonical names like 'seance' and 'aether spellbomb'. That would go a long way towards solving issues like this. The image server already does this with input it receives.

Example standardize (in PHP):

function standardize($string) {
    // Mirror of Cards.standardize in ruby
    $key = $string;
    $key = str_replace("’", "'", $key); // curly apostrophe
    $key = str_replace('“', '"', $key); // curly open quotes
    $key = str_replace('”', '"', $key); // curly close quotes
    $key = unaccent($key);
    $key = utf8_decode($key);
    $key = strtolower($key);
    $key = trim($key);
    $key = stripslashes($key);
    $key = str_replace(' // ', ' / ', $key);
    return $key;
}
unaccent is:

// http://stackoverflow.com/questions/2758736/multibyte-strtr-mb-strtr
// You need html_entity_decode wrapped around it to prevent &quot; and similar r
emaining.
function unaccent($string) {
    return html_entity_decode(pregreplace('~&([a-z]{1,2})(?:acute|cedil|circ|gr
ave|lig|orn|ring|slash|th|tilde|uml|caron);~i', '$1', htmlentities($string, ENT
COMPAT, 'UTF-8')));
}

**Comment by silasary** [comment]
We already have an unaccent() function that we use for creating safe filenames.

**Comment by bakert** [comment]
Gatherer has now updated to be 100% Aether and 0% with the ligature so while we may want to support the ligature as an input this ticket can be closed once mtgjson updates and we rebuild the db for the prod bot. mtgjson still has ligatures as of this comment.

**Comment by bakert** [comment]
mtgjson updated. I had to fiddle with the Aether test when I updated the db just now.

We support "Aether Spellbomb" bot NOT "Æther Spellbomb" right now.

I think that's ok? So closing.

**Comment by silasary** [comment]
Note that Yet Another Æther Vortex has not been updated.
But that's an edge case I'm not overly fussed about.
