### ISSUE TITLE
Process deck names to give them some uniformity

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#310]
Penny Dreadful UB Control
PD Dimir Control
U/B Control

are all the same deck.

We can probably be pretty smart and achieve a reasonable amount of uniformity.

This is separate from the work of grouping archetypes (you can't stop someone calling their UG deck "Ooey Gooey Madness" but you can see that they're playing 4 Arrogant Wurm and 4 Wild Mongrel).

**Comment by bakert** [comment]
I did this.

**Comment by bakert** [comment]
Why does wafflebot keep removing the decks label I wonder.

<img width="473" alt="screen shot 2016-10-31 at 11 18 01 am" src="https://cloud.githubusercontent.com/assets/1541/19843293/b84fbc3a-9f5b-11e6-9311-dd652241a479.png">

**Comment by silasary** [comment]
I assume it's because it's moving them out of the relevant column, and into the "Completed" column.

It's not ideal behaviour, but it's also only applying to completed issues.  I'll file a bug report upstream.
