### ISSUE TITLE
Individual Deck Page

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#316]
Possible features:
- ~~Name~~
- ~~Pilot/Author~~
- ~~Colors~~
- ~~Legality~~
- ~~Cards by maindeck/sideboard~~
- ~~Sort cards by creature/noncreature then cmc in initial view~~
- ~~Cards by type~~
- ~~Legality in other formats~~
- Chart of colors used
- Chart of colors produced
- Chart of card types
- ~~Chart of mana curve~~
- ~~"Buy on Cardhoarder/MTGO Traders"~~
- ~~Similar decks~~
- ~~Deck type~~
- ~~Archetype~~
- Comments
- ~~Export (MTGO, others)~~
- ~~Source link~~
- ~~Competition(s)~~
- ~~Finish~~
- ~~Wins/losses~~
- ~~Created date/updated date~~
- Visual view
- ~~Other decks from the same tournament~~
- Suggested cards
- Sort maindeck/sideboard by rarity/color/cmc/type/type-cmc

**Comment by bakert** [comment]
This is wotc's visual view:

<img width="798" alt="captura de pantalla 2017-06-23 a las 8 40 08 am" src="https://user-images.githubusercontent.com/1541/27489501-9e647bc4-57ef-11e7-9b47-1853be58ae62.png">

It's from mtgg:

<img width="1247" alt="captura de pantalla 2017-06-23 a las 8 41 19 am" src="https://user-images.githubusercontent.com/1541/27489537-c3a2f35c-57ef-11e7-8c33-1affcfd64447.png">

**Comment by silasary** [comment]
This is one of the things I'm planning on doing as part of StackIt's featureset.

It might be worth just doing it there, and calling it as an external tool?

**Comment by bakert** [comment]
Using StackIt, even as-is, would be pretty sweet. But there's something up with the typography and mana symbols in those images. Is it because I have a retina display or do they look jagged/low-res to you too?

<img width="772" alt="captura de pantalla 2017-07-23 a las 12 11 53 pm" src="https://user-images.githubusercontent.com/1541/28498874-2fa4ca0e-6fa0-11e7-9cd8-aa5e8f94babc.png">

It's not the fonts bundled in the app (see screenshot) but something about the manipulation of them in StackIt.

**Comment by bakert** [comment]
I spent some time on StackIt today and improved the quality, especially if we export larger images and resize them in the browser. Will try and get that working without having to produce larger images.

Before:

<img width="270" alt="captura de pantalla 2017-07-23 a las 6 21 05 pm" src="https://user-images.githubusercontent.com/1541/28504405-6a958612-700e-11e7-8a89-e48657dc2d77.png">

After:

<img width="270" alt="captura de pantalla 2017-07-23 a las 6 15 16 pm" src="https://user-images.githubusercontent.com/1541/28504409-75ea9188-700e-11e7-9871-424b417c7ff6.png">

In particular the mana symbols look a lot less jagged.

So we can consider using this in some kind of "visual view". Or some expansion of it.

**Comment by bakert** [comment]
The "buy on Cardhoarder" link on mtggoldfish is actually pretty sweet and useful. You can post-hoc remove things you don't need like forests and alter numbers:

<img width="1440" alt="captura de pantalla 2017-07-24 a las 1 25 27 am" src="https://user-images.githubusercontent.com/1541/28504435-edbe032a-700e-11e7-98ff-c2cab301ab56.png">

I'd want to avoid the suspicion that any money was changing hands, though, or making pdm look like a commercial enterprise so maybe not worth it for those reasons.

**Comment by bakert** [comment]
I messaged Cardhoarder about this and their affiliate program and expanding sponsorship to PDM!

**Comment by bakert** [comment]
Hmm ...

<img width="1137" alt="captura de pantalla 2017-07-25 a las 10 36 12 pm" src="https://user-images.githubusercontent.com/1541/28594926-9e55eaba-7189-11e7-8d80-7bb8b5053424.png">

Maybe ...

<img width="1360" alt="captura de pantalla 2017-07-25 a las 10 37 36 pm" src="https://user-images.githubusercontent.com/1541/28594973-cc9ca184-7189-11e7-9909-c4742ac4d0b9.png">

It's kind of the same information as the main list so it should probably either replace it (bad?) or be a link/pop-up/clickthrough.

**Comment by silasary** [comment]
[Hex TCGBrowser](https://hex.tcgbrowser.com/#!/deck=238989) uses a badly signposted button.

![image](https://user-images.githubusercontent.com/194254/28607049-607c62e8-721d-11e7-9b5b-23f3b14640db.png)

Maybe just do something like this? 
![image](https://user-images.githubusercontent.com/194254/28607223-33965724-721e-11e7-9e78-c4e49db07f06.png)

**Comment by bakert** [comment]
Cardhoarder agreed to sponsor all three tournaments so definitely going ahead with a buy on cardhoarder button.

Referring customers to our deck editor
If you provide decklists on your website or application, we highly recommend using our deck editor integration. Most affiliates that send customers to our deck editor benefit from very high conversion rates and large orders.

When linking to our deck editor, there are three key pieces of information you will need to communicate for each item in the decklist:

id MTGO ID
quantity Quantity
is_sideboard Is it in the sideboard?
This information should be bundled into a POST request, and sent to https://www.cardhoarder.com/decks/upload.
Here is an example of how that request should be formatted:

    <form method="POST" action="https://www.cardhoarder.com/decks/upload?affiliate_id=mtgtop8">
      <input type="hidden" name="data[Deck][cards][0][id]" value="20920" />
      <input type="hidden" name="data[Deck][cards][0][quantity]" value="10" />
      <input type="hidden" name="data[Deck][cards][0][is_sideboard]" value="0" />

      <input type="hidden" name="data[Deck][cards][1][id]" value="58796" />
      <input type="hidden" name="data[Deck][cards][1][quantity]" value="15" />
      <input type="hidden" name="data[Deck][cards][1][is_sideboard]" value="0" />

      <input type="hidden" name="data[Deck][cards][2][id]" value="46737" />
      <input type="hidden" name="data[Deck][cards][2][quantity]" value="2" />
      <input type="hidden" name="data[Deck][cards][2][is_sideboard]" value="1" />

      <button type="submit">Buy on Cardhoarder</button>
    </form>
  
In this example, our deck is only three cards: 10x Relentless Rats, 15x Swamp, and a couple Pack Rats in the sideboard. For each of these items, we need to have the MTGO ID, which can be found in our price file.

Try it out!

Buy on Cardhoarder
 with auto-optimize
Auto-Optimize Feature

Pass the "optimize" flag to automatically process your decklist and replace items with the cheapest, in-stock alternative. You can include it as follows:
<input type="hidden" name="data[Deck][optimize]" value="1" />

Use Card Names (rather than IDs)

We also support a URL-only deck integration that uses card names rather than MTGO IDs. This feature is a little less robust, since it does not support sideboard or specific card versions, but it can be easier to setup. You just need to setup your deck URL as shown below, with the quantity and card name, and separating each item with a double-pipe, ||.

https://www.cardhoarder.com/decks/upload?affiliate_id=mtgtop8&deck=10 Relentless Rats||15 Swamp||2 Pack Rat
 Try it

**Comment by silasary** [comment]
Can you link me to the mentioned price file?
Hopefully it won't be too hard to integrate CatIDs.

**Comment by bakert** [comment]
We left price file for "down the road". They've been pretty generous so I want to tread lightly :) I'll circle back about prices soon-ish?

**Comment by silasary** [comment]
Sounds good :)

**Comment by bakert** [comment]
"Buy on Cardhoarder" is 60cd7468.

Next challenge: how to declare StackIt as a dependency in requirements.txt.

**Comment by silasary** [comment]
Oh dear.  I'm going to need to package StackIt up as a pip package, aren't I?

**Comment by silasary** [comment]
poppu-mtg/StackIt#65

**Comment by bakert** [comment]
created date is f6450cd3.

**Comment by bakert** [comment]
PRs to poppu-mtg/StackIt https://github.com/poppu-mtg/StackIt/pull/76 followed by https://github.com/poppu-mtg/StackIt/pull/55 will get us in a place where we can use this for decklist image generation. Although the quality will still not be as good as it could be. I'll try and figure that out.

**Comment by bakert** [comment]
Additional charts now filed separately as #2926.

**Comment by bakert** [comment]
All other oustanding work here now logged in separate tickets as #2928, #2929 and #2930.
