### ISSUE TITLE
Standardize on types.SimpleNamespace or dict or something else as style of dataholding objects

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#318]
This is across the monolith.

Deck(dict) and Card(types.SimpleNamespace) currently disagree about how we do this.

**Comment by bakert** [comment]
What I'd really like it to be able to say:

```
blah.id()
```

and have it do the right thing rather than choosing between:

```
blah.id
```

and

```
blah['id']
```

but I'll take the former (supported by types.SimpleNamespace) over the latter I think? It's "quite pythonic" to just reach out and touch member variables?

I'd really like to hide whether it's a method call or a variable though. deck.cards might want to really be deck.maindeck + deck.sideboard for example.

Maybe I'm stuck in too ruby of a mindset and I should rethink these things altogether.

**Comment by bakert** [comment]
There's also an argument that our classes should be more structured with getters and setters and what not but that seems like too java of a mindset and if there's too-anything-of-a-mindset I don't want to be it's java :)

**Comment by bakert** [comment]
The other option is just not to expose objects to the world until they are fully built as a philosophy. And then allow direct attribute access. This seems to be the most pythonic of all the possibilities.

**Comment by silasary** [comment]
Dict allows us to call json.dumps(), so I'm inclined to go to that one.

**Comment by bakert** [comment]
`json.dumps(instance.__dict__)` will work if we keep the SimpleNamespace objects as dumb as a dict and prefer the c.id syntax to c['id']. (Which I definitely do!) Not as nice as json.dumps(dict) but probably good enough.

**Comment by bakert** [comment]
It seems like the python community is fairly united in their belief that overriding `__getattr__` to do deviant things is unpythonic so I'll probably make the contract that these objects have to be built out of public view and returned complete and don't have any magic behaviors or methods. But I do think I'll go with SimpleNamespace over dict just because of the typing/line noise. Unless you have big objections.

**Comment by bakert** [comment]
There's also Bunch which is a subclass of dict that allows dot notation.

https://pypi.python.org/pypi/bunch/1.0.1

**Comment by bakert** [comment]
Went with Bunch in a5d6092. We'll see how we progress. json.dumps and c.id both work with Bunch.
