### ISSUE TITLE
Some "smaller" way to check legality

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#325]
Sometimes I want to know if a card is legal when I already know what it does.

Maybe include legality in !price?

Maybe a !legal command.

**Comment by silasary** [comment]
Yeah, including it in price seems like the best option

**Comment by zserdely** [comment]
It'd be very useful to see it in !price. I'd also suggest including in !oracle. 
The !legal command could be useful too, I don't think there are any downsides to having it.

**Comment by bakert** [comment]
Added `!legal` in 92f05f3 and included legal emoji at start of `!price` and `!oracle` responses.
