### ISSUE TITLE
Performance of deck insertion is so slow that it's probably worth worrying about now

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#332]
As much as premature optimization is the root of all evil.

**Comment by silasary** [comment]
We could probably separate the deckcycle scraping and the retrieval of
decklists into separate actions.
And we should definitely try to ignore decks that have been imported too
recently.

Do tappedout decklists give Last Modified headers?

**Comment by bakert** [comment]
This is in a good enough state that I'm going to close it.

It's certainly true that a lot of what we do loading decks from the db, scraping and a bunch of other stuff is way less efficient than it could be but we'll worry about it when we see issues.
