### ISSUE TITLE
Penny Dreadful League

### ISSUE THREAD

**Issue by PaulPatrick22** [PennyDreadfulMTG/Penny-Dreadful-Tools#3362]
I recently completed my first league for Penny Dreadful but I didn't receive any bot credit on MTGO Traders, is there something in specific that I need to do to earn the credit?

**Comment by bakert** [comment]
The details for the November league went out to MTGO Traders today. If you completed the run in December then I'm waiting on permission to send them in as they happen rather than at the end of the month from now on but not sure if that's going to happen or not.

**Comment by PaulPatrick22** [comment]
thank you!
