### ISSUE TITLE
decksite.database.setup would apply SQL migrations out of order if the os returned them in that way?

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#367]

**Comment by silasary** [comment]
It might.
This would become an issue when we hit `10.sql`

We should check and fix if needed.

**Comment by bakert** [comment]
We could name them by date 2016-11-01.sql?

**Comment by silasary** [comment]
We'd need to do a conversion to an integer (probably epoch time), but yeah, I like that.
