### ISSUE TITLE
I broke something to do with closing cursors in Flask app context with my db refactor

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#372]
Katelyn will not be pleased.

Error is 'The cursor has been closed'.

Steps to repro:
- Start the webserver.
- Click around a bunch.

**Comment by bakert** [comment]
Vague intuition here from reading Katelyn's code is that we need to reattach the db context to the flask context and make sure it is closed and not closed at the right times by hanging it off `g` as it was before.

But decksite.database should continue to function for the Gatherling and Tapped Out scrapers.

Hm.

**Comment by bakert** [comment]
@silasary I am a bad person and broke your fix because I didn't understand it and it didn't seem to be happening to me. And now it is. Justice!

**Comment by bakert** [comment]
I think I just confused myself because I only partially removed it. Completely removed everything seems fine. I'm sure you'll explain to me what I've actually broken tomorrow :)

**Comment by silasary** [comment]
Ok, so this is a problem that isn't obvious.

It'll run fine without reattaching under normal circumstances.

The problem occurs when flask hot-reloads the site after source files change on disk. 

If it does that, sqlite will complain about being accessed across a thread boundary.

I'm not sure if this still occurs with apsw.

**Comment by silasary** [comment]
So yeah, it might be a problem, it might not.  I dunno.

**Comment by bakert** [comment]
Ah, thanks. We can keep an eye on it and find a way to put it back in but still keep db working for standalone scrapers if it still happens. Thanks!
