### ISSUE TITLE
When retiring a deck, we should not show a 404 deck page

### ISSUE THREAD

**Issue by jgabrielygalan** [PennyDreadfulMTG/Penny-Dreadful-Tools#3779]
When you retire a deck and the deck didn't have any match, it's actually deleted and the deck_id doesn't exist anymore. Then the page tries to redirect to the deck page, which fails with a 404. We should redirect somewhere else.

**Comment by jgabrielygalan** [comment]
As per Tom's comment, we should redirect to the signup page.

**Comment by jgabrielygalan** [comment]
Should we redirect to the signup page regardless, or only in the delete case?

**Comment by bakert** [comment]
In any case. They came here to retire which implies they want to play with a different deck.
