### ISSUE TITLE
Flip cards show the same image twice

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#382]
It's trying to be smart a la Meld cards or DFCs but it's being too smart.

**Comment by bakert** [comment]
_Might_ just be a flip-cards-are-broken-in-mtgjson problem but I don't think so.

**Comment by silasary** [comment]
If it showed the card upside down it might be useful.
Right now, I'm inclined to blame mtgjson.

**Comment by bakert** [comment]
I think you're right. The only case I've actually seen in Nezumi Graverobber. Budoka Pupil does the right thing.

**Comment by bakert** [comment]
Checked some others and they were all fine. Closing and assuming forthcoming flip card fix up will get the rest.
