### ISSUE TITLE
Maybe use monkeytype to set typehints for all our code

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#3820]
https://engineering.instagram.com/let-your-code-type-hint-itself-introducing-open-source-monkeytype-a855c7284881

**Comment by bakert** [comment]
We have .pyi files with stubs of functions in that @silasary did but needs tightening up and moving into the actual code.

**Comment by silasary** [comment]
I'd still like to get monkeytype working, if at all possible.  Handwritten typehints are a pain to do.

**Comment by bakert** [comment]
Much improvements in this area. Do we still need this ticket?

**Comment by bakert** [comment]
I think we're done here as we've moved on to a near-fully-explicitly-typed world.
