### ISSUE TITLE
Better league info in lists of decks

### ISSUE THREAD

**Issue by jgabrielygalan** [PennyDreadfulMTG/Penny-Dreadful-Tools#3824]
In the list of decks for a player, when the source is League it would be nice to know which one exactly, so differentiate December decks from November decks.

**Comment by bakert** [comment]
Why do you want to know? To see which decks are old/new at transition? Does the 'target' symbol for active decks not do that?

The word "League" does link to the competition, and the date is something of a giveaway. We don't have all that much real estate to play with.

"Nov League" or "November League" or "League November 2017" are all options but they all take more pixels.

We hide source altogether in anything but the full screen width (currently 1120px+).

For Gatherling this becomes more problematic. "Gatherling" or "Penny Dreadful Thursdays 6.10" or "PDT 6.10" or "PDT".

Thinking.

**Comment by jgabrielygalan** [comment]
I was once counting how many runs I had I'm the current league, or how many 5-0, and around the cut date there were several decks with 2 weeks ago. I couldn't tell where the cut was. It's not a very important feature. Maybe more aggregated stats about each league would be even nicer, so you don't need to count things looking at the people page

**Comment by jgabrielygalan** [comment]
Maybe something like this, with proper colors?

![decks_by_league](https://user-images.githubusercontent.com/247560/34892433-8ff810d4-f7d9-11e7-9666-39c7e4e55d50.PNG)

**Comment by jgabrielygalan** [comment]
This is just a bad hack to show what I mean. Proper background colors, or even just a slight border around. In this example I've split the table in three that's why the below ones are not aligned, so that's bad. I'll make another try with the tr's background color:

![decks_by_league2](https://user-images.githubusercontent.com/247560/34892767-cf366ff6-f7da-11e7-9db8-a1a960ae52c9.PNG)

**Comment by silasary** [comment]
How does this look for someone who also also played in Gatherling Events?

**Comment by jgabrielygalan** [comment]
Good point. Maybe then something even more subtle. Just backgroud the td with the word League, if it's a league, and don't touch anything else. Alternatively choose a background or border for Gatherling.
![decks_by_league3](https://user-images.githubusercontent.com/247560/34905791-571ec82a-f860-11e7-8854-e079624b0927.PNG)

**Comment by bakert** [comment]
Another possibility is "Dec League" "Jan League".

**Comment by jgabrielygalan** [comment]
As you mentioned the problems with the width I was thinking on alternatives that don't make things wider. But it's ok for me too.

**Comment by bakert** [comment]
I don't think "Jan League" is wider than "Gatherling" or not by much.

**Comment by bakert** [comment]
<img width="935" alt="captura de pantalla 2018-04-20 a la s 1 59 25 p m" src="https://user-images.githubusercontent.com/1541/39049752-10544836-44a3-11e8-9364-bcfa9b0efcb9.png">

i tried this, it looked weird. I don't think the "I can see the transition between one month and next cleanly" is worth the noise?

**Comment by bakert** [comment]
Reopening for inclusion in backlog.

**Comment by silasary** [comment]
There's no real good solution here.  Closing.
