### ISSUE TITLE
Match White/Blue White/Blue/Black, etc. in remove_colors

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#385]
We match 'White' and 'WU' and 'W/U' but not 'White/Blue'.

**Comment by silasary** [comment]
We should also strip "Penny Dreadful", "pd", and "[pd]" from deck titles.

**Comment by bakert** [comment]
We're do that but we do fail on "[PD] MONO B CONTROL" for reasons I have not yet investigated.

**Comment by bakert** [comment]
Fixed the stripping issue. My regex was looking for opening brackets twice instead of open + close. Doh. Test added.

**Comment by bakert** [comment]
This hasn't come up enough to be worth doing imho.
