### ISSUE TITLE
We hide decklists on the deck page when in an active league run but …

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#3892]
(1) We still show the decklist on mouseover, which
(2) Will break full-page caching of a lot of pages, and
(3) We need to send 403 Forbidden from Download and Buy endpoints if those are visited by not-that-person or logged people.

**Comment by silasary** [comment]
#3887

**Comment by bakert** [comment]
I did (1) and @jgabrielygalan did (3) and (2) we don't care about because we hide from everyone if active and you have to click in to the decklist if you want to see your deck.
