### ISSUE TITLE
We have both Template().substitute and "blah" + "foo" and %-based string interpolation. And we should probaby be using .format()!

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#39]

**Comment by silasary** [comment]
Oh, we're using .format() too!

It's all a big mess of whatever felt better for an individual thing.

**Comment by silasary** [comment]
Templates were useful when I was still trying to work out which fragments to include in messages, and in which order.

But yeah, We need to unify some of that code.

**Comment by bakert** [comment]
Reading around it seems like format is most preferred and the % syntax that I've added everywhere is frowned upon these days.
