### ISSUE TITLE
UNKNOWN BUGGED CARD: Card Name

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#3900]
(starting bot)

**Comment by silasary** [comment]
This is because https://github.com/PennyDreadfulMTG/modo-bugs/issues/244 was formatted incorrectly.

I'll make the modo-bugs script automatically account for people making that specific typo.

**Comment by silasary** [comment]
Fixed in https://github.com/PennyDreadfulMTG/modo-bugs/commit/3ba85447fb0052f5a6901284c18b194ab3f55f4c
