### ISSUE TITLE
Could you please mention Magic The Gathering somewhere in your README or Org description?

### ISSUE THREAD

**Issue by notriddle** [PennyDreadfulMTG/Penny-Dreadful-Tools#3934]
It's only after I noticed you mentioning cards that I realized MTG means "Magic the Gathering". I kept thinking of the horror show.

**Comment by bakert** [comment]
Heh. And I thought you were coming to read about Victorian pulp fiction!

It's true that the site does a terrible job of introducing itself. I'm closing this as we're already tracking that in #1634 but we really should do that sooner rather than later.
