### ISSUE TITLE
Webserver (or something) is grabbing our error codes and serving ugly pages instead of our lovely error pages (on prod only)

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#3947]
Entering an invalid URL in /add/ results in an ugly error page on prod instead of the intended page

Something is noticing the 409 status code and taking over, I think?

Prod:

<img width="1077" alt="captura de pantalla 2018-01-05 a las 3 02 34 p m" src="https://user-images.githubusercontent.com/1541/34633803-75b3a124-f276-11e7-92b5-0e2ed0cb0fda.png">

Dev (and used to work on prod at least for 404s):

<img width="841" alt="captura de pantalla 2018-01-05 a las 3 03 19 p m" src="https://user-images.githubusercontent.com/1541/34615027-40495484-f22b-11e7-9687-c4ac629eb641.png">

**Comment by bakert** [comment]
@silasary might understand this.

**Comment by silasary** [comment]
Fixed.
