### ISSUE TITLE
Visual/sparkline summary of tournaments on /competitions/

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#3991]

**Comment by bakert** [comment]
(1) Colors
~~(2) Aggro/Combo/etc~~
(3) Winning archetype
(4) Winning player
(5) Top 8 archetypes/colors.
(6) Top 8 decks
(7) New cards
(8) Videos

**Comment by bakert** [comment]
Archetypes sparkline is 573032af.

**Comment by bakert** [comment]
I'm kind of unimpresssed with this and unlike most features on the site that get added it hasn't garnered any comments. Possibly because no one visits the competition list page rather than because it's terrible. But I don't find it particularly useful. Possibly rollback, or improve in some way?

**Comment by mmrsad** [comment]
Sparkline is displaying out of order from popup currently.  Chart 3, 9, 2, 1, 1, 2, 3, 6 but popup is 9, 3 ,6, 3, 1, 2, 1
![chart](https://user-images.githubusercontent.com/35934185/35996905-1154cb1c-0cd5-11e8-99a4-101b166bd2f9.png)


Color coded bars and a simple index could go a long way for readability and understanding/comparing at a glance.  
![sparkline](https://user-images.githubusercontent.com/35934185/35996971-51f7b184-0cd5-11e8-9b9f-229bb2268a40.png)  Rough mockup, something like this?

**Comment by bakert** [comment]
Marking this as a bug because it's kind of a mess right now. Although pretty ignorable. Sparklines should also be hidden on mobile in favor of more useful columns probably.

**Comment by bakert** [comment]
I killed this feature in 674b3243. I think it's just not interesting enough to be worth fixing. The thought that pushed me that way was that it's not even really about macro archetypes as the hosers for different combo decks and rdw/other aggro can be quite different anyway. It doesn't tell you how much gy hate you need. So you have to dig in to find out what you're trying to find out anyway.
