### ISSUE TITLE
More than one image at once gives "no image available" when falling back to gatherer images 

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#4]
- More than one image at once gives "no image available" when falling back to mtgsdk images because the SDK only supports single images. We could send each separately or only send the first rather than "no image available"?

**Comment by bakert** [comment]
We now send the first image. If/when we add compositing on the bot side we will also composite Gatherer images. Until then this is the best we can do. Closing.
