### ISSUE TITLE
Elide repeated dates when sorted by date

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#404]
"3 days ago 3 days ago 3 days ago 3 days ago 3 days ago 3 days ago" is a visual chore.

Beware the impact when sorted once we allow js sorting of the page

**Comment by bakert** [comment]
I think we will need to do this in javascript and I think it's still worth doing.

We can probably add a callback to the tablesorter searching function.

Alternatively initial sort could be by "interestingness" or homepage could show a more opinionated view of decks than just "latest" and we would care less that this view looks ugly.

**Comment by bakert** [comment]
I posted about this here:

http://graphicdesign.stackexchange.com/questions/79495/dealing-with-a-lot-of-repetition-in-data-table/79496

I think grouping with an unobtrusive background color makes a lot of sense. Whether it is worth the time/effort to implement that in a sortable table is another question.

**Comment by bakert** [comment]
I did the all-singing all-dancing version of this. I think it's cool. We'll see what others think.

**Comment by silasary** [comment]
It looks nice, but don't do it for record/Top 8.
![record](https://cloud.githubusercontent.com/assets/194254/20046476/429855b2-a4fe-11e6-9a96-43f09828d0d5.PNG)

**Comment by silasary** [comment]
Or name, for that matter
