### ISSUE TITLE
Standardize imports

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#407]
from dateutil import tz

or 

import dateutil

And many other examples.

Let's have a standard.

**Comment by silasary** [comment]
I think it depends on the context, but yeah - There are some functions we import in two different ways, and that's really not good.

**Comment by bakert** [comment]
Here's everything we do:

  12 from shared import configuration
        11 import re
         9 import os
         9 from decksite.view import View
         7 from shared import dtutil
         6 from munch import Munch
         5 import json
         5 from shared.database import sqlescape
         4 import time
         4 from shared.pd_exception import InvalidDataException
         4 from magic import card
         4 from decksite.database import db
         3 from shared.pd_exception import DatabaseException
         3 from magic import mana
         3 from flask import url_for
         3 from decksite.scrapers import decklist
         2 import sys
         2 import pkg_resources
         2 import magic.fetcher_internal as internal
         2 import html
         2 import datetime
         2 import collections
         2 import apsw
         2 from shared.pd_exception import ParseException
         2 from shared.database import Database
         2 from price_grabber import price
         2 from magic.database import db
         2 from magic import oracle
         2 from magic import fetcher
         2 from magic import database
         2 from find import search
         2 from discordbot import command, emoji
         2 from discordbot import command
         2 from decksite.scrapers import tappedout
         2 from decksite.main import APP
         2 from decksite import translation
         2 from decksite import deck_name
         2 from dateutil import tz
         1 import zipfile
         1 import urllib.request
         1 import urllib.parse
         1 import urllib
         1 import unicodedata
         1 import types
         1 import titlecase
         1 import textwrap
         1 import subprocess
         1 import sqlite3
         1 import shutil
         1 import requests
         1 import random
         1 import pystache
         1 import itertools
         1 import importlib
         1 import hashlib
         1 import glob
         1 import discord
         1 import csv
         1 import copy
         1 import asyncio
         1 from typing import List
         1 from shared.pd_exception import OperationalException
         1 from shared.database import sqlescape, sqllikeescape
         1 from shared.database import Database, sqlescape, sqllikeescape
         1 from shared import configuration, dtutil
         1 from shared import configuration, database
         1 from price_grabber import srv_prices
         1 from price_grabber import price_grabber
         1 from magic.fetcher_internal import FetchException, escape
         1 from magic.fetcher_internal import (FetchException, fetch, fetch_json, store,
         1 from magic import oracle, fetcher_internal
         1 from magic import mana, oracle
         1 from magic import image_fetcher, oracle
         1 from magic import fetcher, rotation
         1 from magic import fetcher, fetcher_internal
         1 from magic import card, oracle, fetcher, rotation
         1 from magic import card, mana, oracle
         1 from magic import card, fetcher, oracle, fetcher_internal, image_fetcher
         1 from magic import card, database, fetcher, oracle
         1 from magic import card, database, fetcher, mana
         1 from flask import Flask, request, send_from_directory
         1 from flask import Flask
         1 from find.tokens import BooleanOperator, Criterion, Key, Operator, String
         1 from find.expression import Expression
         1 from email.utils import formatdate
         1 from discordbot import generate_readme as bot_readme
         1 from discordbot import emoji
         1 from discordbot import bot, command
         1 from discordbot import bot
         1 from decksite.views import AddForm, Card, Cards, Competition, Competitions, Deck, Home, People, Person
         1 from decksite.scrapers import tappedout, gatherling
         1 from decksite.data.deck import Deck
         1 from decksite.data import query
         1 from decksite.data import deck, query
         1 from decksite.data import deck, Deck
         1 from decksite.data import deck
         1 from decksite.data import competition, deck
         1 from decksite.data import card as cs, competition as comp, deck, person as ps
         1 from decksite import template
         1 from decksite import main
         1 from bs4 import BeautifulSoup
         1 from .person import Person
         1 from .people import People
         1 from .home import Home
         1 from .deck import Deck
         1 from .competitions import Competitions
         1 from .competition import Competition
         1 from .cards import Cards
         1 from .card import Card
         1 from .add_form import AddForm

**Comment by bakert** [comment]
Most of the advice I read is pro:

```
import x
```

and mildly against

```
from x import y
```

There's also a lot of hate for underscores in module names.

I think we have to allow 

```
from dir.subdir import x
```

otherwise the monolith will haunt us.

**Comment by bakert** [comment]
Our imports break down into these groups:

import pythonmodule [re, time, sys, apsw, ...]
from pythonmodule import Class [typing.List]

import thirdparylib [pkg_resources]

from thirdpartylib import Class [munch.Munch, bs4.BeatitfulSoup]
from thirdpartylib import function [flask.url_for]
from thirdpartylib import Class, module, module [Flash, request, send_from_directory]

from thirdaypartylib import one, two [discordbot.command, discordbot.emjoi]

from dir.subdir import thing as thing2, thing3 as thing4, thing5, thing6 as thing7 [main.py imports that conflict function names]
from dir import module [magic.card, magic.mana, find.search, ...]
from dir import long, list, of, modules
from dir.subdir import module
from dir.subdir import Long, List, Of, Classes [Views, Tokens]
from dir.subdir import Class, function1, function2 [shared.database.Database, shared.database.sqlescape, shared.database.sqllikeescape]
from dir.subdir import function1, function2 [shared.database.sqlescape, shared.database.sqllikeescape]

from dir.subdir import Class [InvalidDataException, shared.database.Database]

from dir.module import function [db]

from .subdir import Class [Views in **init**.py]

Uncategorized

from magic.fetcher_internal import (FetchException, fetch, fetch_json, store,
import magic.fetcher_internal as internal
from email.utils import formatdate
from discordbot import generate_readme as bot_readme
from magic.fetcher_internal import FetchException, escape

**Comment by bakert** [comment]
I think by common usage we've decided that all of these are ok:

import pythonmodule [re, time, sys, apsw, ...]
import thirdparylib [pkg_resources]
from thirdpartylib import function [flask.url_for]
from dir.subdir import module

I think we've also decided that lists coming from the same module are ok which clears:

from thirdaypartylib import one, two [discordbot.command, discordbot.emjoi]
from dir import long, list, of, modules
from dir.subdir import function1, function2 [shared.database.sqlescape, shared.database.sqllikeescape]
from thirdaypartylib import one, two [discordbot.command, discordbot.emjoi]

I'm also certain that I want to allow:

from .subdir import Class [Views in init.py]

because I can't be saying `views.cards.Cards` and `views.deck.Deck` all the time and the mustache renderer wants classes.

For the same reason I want to allow:

from thirdpartylib import Class [munch.Munch, bs4.BeatitfulSoup]

which I suppose implicitly allows:

from dir.subdir import Long, List, Of, Classes [Views, Tokens]
from thirdpartylib import Class, module, module [Flask, request, send_from_directory]
from dir.subdir import function1, function2 [shared.database.sqlescape, shared.database.sqllikeescape]

I'm less clear on:

from pythonmodule import Class [typing.List]
from dir.subdir import thing as thing2, thing3 as thing4, thing5, thing6 as thing7 [main.py imports that conflict function names]
from dir.module import function [db]

Although in the last case I really want shorthand for the database that's not unwieldy.

I guess I'm on the verge of concluding that it's all case-by-case and we should just not do anything too terrible.

**Comment by silasary** [comment]
`from pythonmodule import Class [typing.List]` comes from when I was running around decorating parameters. 
`function(arg1: str, arg2: List[int])  -> List[Class]:` is so much nicer than `function(arg1: str, arg2: typing.List[int])  -> typing.List[module.Class]:`

The second one, I'm not so sure about.

And the third is definitely worthwhile.  Although we might consider making it a property rather than a function.
