### ISSUE TITLE
End of Season Polls for Fun

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4071]

**Comment by silasary** [comment]
elaborate?

**Comment by bakert** [comment]
Favorite card of the season. Favorite deck of the season. Most hated card of the season. Not really a pdm thing it was just suggested in chat and I wanted somewhere to log it to remind me to do it and post it on reddit probs. There was a person in discord who was going to do it but that was >1 week ago so I'll probably just do it.

**Comment by bakert** [comment]
strawpoll.me or surveymonkey type thing.

**Comment by bakert** [comment]
https://www.reddit.com/r/PennyDreadfulMTG/comments/7rc8f4/get_polled_some_polls_about_season_6_season_7_and/
