### ISSUE TITLE
strip, lstrip and rstrip don't do what I thought they did - check all usages are sane.

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#42]
I thought they chopped that exact string off the left/right/both sides. But they treat the string more like a list of characters to chop.

**Comment by silasary** [comment]
No, that's what .strip() is for

Python 😒

**Comment by bakert** [comment]
Ah, crap, I meant strip ... changed title!

I really think "abba".rstrip("ba") should == "ab" not "". But that's not how it works.

**Comment by silasary** [comment]
Ah, right.
Yeah, it treats them as an `[ab]*`.
