### ISSUE TITLE
Bugs wording and consistency

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4224]
On /tournaments/ under Bugs, "Cards with game-breaking bugs should not be played" is ambiguous. It should read "may not be played" and the current cards with game breaking bugs in common play should be added as exceptions or have their label changed. Many of the unplayed gamebreaking bug cards clearly can never be allowed, but the two that are in heavy play seem fine at the players own risk.

**Comment by silasary** [comment]
According to RFC 2119, `SHOULD NOT` is stronger than `MAY NOT`.

**Comment by bakert** [comment]
That is an interesting fact. @mmrsad – are we done here?
