### ISSUE TITLE
Do some archetype wrangling

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4239]
~~This is contingent on the BASE_ARCHETYPES bug being fixed – #4111~~

- [ ] Wave decks should probably be some distinct subcategories of Blink.
- [ ] Devoid cruelty should be its own archetype not lumped into Cruel Control.
- [ ] Make mardu life an archetype and put s6 and s7 decks in it
- [x] Make a dynavolt tower archetype
- [ ] Aggro-Control is a mess of Aggro-Control and (mostly?) Fish decks because I didn't understand the difference between those two things when I started categorizing.

**Comment by BackAlleyG** [comment]
A couple things 
- I made Devoid Cruelty its own archetype but it's still a sub-archetype of cruel control atm. I thinking with about 8 signets and hedron archives it's feels more like a ramp deck than anything else. Other thoughts?
- Not really enough decks (6) atm I feel like to make an archetype with 10 being the normal minimal baseline but could be added in the future if it gets played more.
- tower archetype can be crossed off the list, since you took care of it. 
- Lastly, would this be a good thread for potential archetype renames, etc? Not sure how easy/difficult it is renaming or deleting archetype so may not be necessary to keep track of like this.

**Comment by bakert** [comment]
Yeah this is a good thread to thrash some things out if we want a less synchronous discussion than #code on Discord.

You're right that "Devoid of Cruelty" doesn't really play like cruel control at all. It *did* run counterspells to get as far as the Ultimatum so it's also not *that* different. But it was all about cost reducers, signets and the ultimatum rather than messing around with much in the way of removal and other interaction. It wouldn't be ridiculous to put it under ramp. I'm torn on that one. Maybe the tiebreaker is that people will look under Cruel Control for ultimatum decks and that's what it is more than anything?

Is it Mardu Life that doesn't have enough decks? I still had four as the threshold in my mind when I wrote this list I think but I'm happy to ignore it if it's only at 6 decks. I am down with my own revision of the threshold now PD is bigger and badder than ever :D

Renames are (very) easy in the database but there's no UI for it. I could make one but it should be pretty rare?

**Comment by BackAlleyG** [comment]
Well, we currently have reliving ultimatums over in combo so I don't think it would be too crazy to have cruel ult decks be a bit scattered to some degree and have devoid cruelty in ramp. Overall, it seems like an common issue for certain themes/card-centered decks, (e.g. madness and necro) that span across multiple archetypes. It possibly might be annoying for some but if I wanted to see cruel ult, or other theme decks I usually go to the card's page anyways (though don't really know if this is the normal go to for most) or whatever key card(s) for the general theme and find all the decks for a more general theme there.

  Yeah, I was referencing Mardu life. Something in like the 5-10 range is probably  fine for a minimum, I was just mainly going off what you recently said  in #code on discord
> Number of decks before we create a new archetype should be about ten I think. It was four when I started but there were a lot less players/decks then  

We just have to agree on something for a standard baseline for future sorting and in general.

  Yeah, pretty much all the names are good there was just like one or two minor things that could probably be adjusted. One that I can recall atm is to change "Boros Vehicles" to just "Vehicles" as there's now some non-boros vehicle decks. We could make "boros vehicles" a sub-category of "vehicles" in the future if necessary it but I don't think it's needed as a subarchetype at this point in time. Another one is "treefolk" is pretty small atm with 2 decks (with one being the goldfish version) and stick them with "rofellos ramp" or just "ramp."

**Comment by bakert** [comment]
Sorry I wasn't very clear. By "I am down with my own revision of the threshold" I meant "I think my suggestion of making 10 the threshold is good and we can not bother with a Mardu Life category". In fact, we should probably retire a couple of categories like Mono W Oketra's Monument that only have 4-5 decks.

I forgot about Reliving Ultimatums. That is a pretty good argument for moving Devoid of Cruelty into Ramp. I'm happy if we do that. After thinking about it I agree that it's more important for a deck to sit inside the right macro archetype than it is for key cards to all live in the same part of the tree. Let's do our best to describe the key strategy of the deck and only worry about "siblings" after that.

Go ahead and move the decks out of Treefolk. If you post here the renames and deletions you want I can do them by hand easily until I build some UI :D

**Comment by bakert** [comment]
I think we're in a good spot here. We also have open lines of communication for future wrangling. Closing.
