### ISSUE TITLE
Color bar in decklist should probably be proportional to number of mana symbols not even

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#425]
It might look too noisy but I think it would be cool and we already load the necessary information. Might need inline styles to get the widths right.

**Comment by bakert** [comment]
There's also a reasonable chance this looks dumb, or way too busy.

**Comment by silasary** [comment]
Mock it up. Let's see what it looks like

**Comment by bakert** [comment]
Oh, it's actually pretty cool:

<img width="916" alt="screen shot 2016-11-06 at 6 02 27 pm" src="https://cloud.githubusercontent.com/assets/1541/20040209/37ef9160-a44b-11e6-9a11-56b47f4f4273.png">

I'll see if I can make it fast enough. Ordering colors by color order rules is a pain!

**Comment by bakert** [comment]
09e2b25.
