### ISSUE TITLE
Replace google search with a typeahead that falls back to google search

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4264]
Typeahead should know all card names, all people names, all archetype names and all deck names (santized and unsanitized?)

An endpoint like: http://pairings.channelfireball.com/deck/ajax?command=search_cards&format=&term=Tarmo

And jquery plugins found on http://pairings.channelfireball.com/deck

should be fairly easy to build and although the js loading will affect first page load we can load from cdn and cache in browser indefinitely.

**Comment by silasary** [comment]
This was done
