### ISSUE TITLE
Large day-of-month markers are not as accurate or useful as they might be and sometimes repeat

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4302]
<img width="325" alt="tournaments_ _pennydreadfulmagic_com" src="https://user-images.githubusercontent.com/1541/36314140-dea04952-1301-11e8-8e9b-268d6471036f.png">

**Comment by bakert** [comment]
This might be complicated by localization. It is probably already complicated in that it displays the wrong thing to people in timezones far from EST. Will need a little think probs.

**Comment by silasary** [comment]
This is already wrong for me.  Note that Tuesday falls on the 27th.
![image](https://user-images.githubusercontent.com/194254/36403325-65db0b26-1638-11e8-83fd-00e00d978b88.png)

**Comment by bakert** [comment]
Good point. It's technically wrong in EU too because the start time of US-centric tournaments are midnight-2am in various EU timezones.

Might require a bit more clientiness.

**Comment by bakert** [comment]
OK, we already have the moment.js library to guess the user's timezone.

So we can extend our use of that to do something like this:

```
    <time datetime="2018-10-28T00:00:00.000Z"></time>
    <script>
      console.log(moment($('time').attr('datetime')).tz(moment.tz.guess()).format('ha z'));
    </script>
```

which understands daylight savings changes that are in the future from now and so on.

Then the large number display can be set by the js when it kicks in.

**Comment by bakert** [comment]
df4ffc61.
