### ISSUE TITLE
Write up PD Community Guidelines

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4320]

**Comment by bakert** [comment]
Rough draft:

----

We respect the WotC "Commitment to Each Other".

- Put fun first. Keep it friendly, respectful and fun.
- Welcome everyone. Magic Online first-timers, people coming back to the game for the first time in a long time, children, j_meka … everyone!
- Respect your environment. This means no "bad manners" in Magic Online chat. No unpleasantness in Discord. No going to Discord to talk about how terrible your last opponent was (they are probably there reading what you are saying!)
- Follow the rules. Although Magic Online enforces a lot of the rules for us there are still bugs and other issues that require players to cooperate to resolve. If in doubt talk to the Tournament Organizer or a Discord moderator.

----

Do we need more than the four points from the WotC code? Something about no ban chat? :D

**Comment by silasary** [comment]
"BM" is too heavy on the jargon.  Just say "Bad Manners"

**Comment by bakert** [comment]
I'll spell it out explicitly and include some examples. I thought BM was a more widely known phrase than it is but you're the second one to call it out :D

**Comment by bakert** [comment]
b853e0bf.
