### ISSUE TITLE
Ignore reminder text in o: queries

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#433]
Author of mtg.wtf makes a good point:

https://www.reddit.com/r/magicTCG/comments/59brng/a_better_faster_card_search_scryfall/d988q9r/

**Comment by silasary** [comment]
I think it can be useful, but it should probably be an explicit thing. 

Maybe `+o:"flying"`?  (This would put in on a similar feel as the way `++` unfolds multiple printings on most sites)

**Comment by bakert** [comment]
This wants to be implement with a regex on the oracle text field s/\([^\)]*\)//g. But to do that in SQLite requires an extension. An alternative is to have another column where we denormalize the searchable text. Bit uglier but simpler than adding more infra. Could easily do this in setup.

**Comment by bakert** [comment]
10e9767a.

<img width="683" alt="captura de pantalla 2017-07-24 a las 3 50 43 pm" src="https://user-images.githubusercontent.com/1541/28529528-b2892206-7088-11e7-81ff-58d2e861fa49.png">

<img width="835" alt="captura de pantalla 2017-07-24 a las 3 50 53 pm" src="https://user-images.githubusercontent.com/1541/28529529-b28dfaba-7088-11e7-9e90-6cbe52bd1285.png">
