### ISSUE TITLE
Trimming active league runs after retrieving from the db leads to (even) greater variability in the number of decks loading - can we trim in the SQL instead?

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4338]
This would mean we wouldn't know the number of league runs unless we retrieve it separately but that might be OK. In general I think that "active league players" should be a list somewhere else? On the league page and maybe linked from home.

**Comment by silasary** [comment]
I thought I opened an issue for this when I first shipped the feature.

The current method also means we have three different counts of "number of
active league runs".

It was always intended as a temporary thing, with the assumption that we'd
replace it with something better Soon™
​

**Comment by bakert** [comment]
I think where we are at is good now. We don't trim in the db but we do account for number of active league runs better. Full on "better display" of active league runs may come later if we have a brainwave.
