### ISSUE TITLE
!rulings can use the #rulings anchor on Scryfall

### ISSUE THREAD

**Issue by csuhta** [PennyDreadfulMTG/Penny-Dreadful-Tools#4359]
I noticed that if there are too many rulings to display for a card, the MTGBot will link to Scryfall. You can add the `#rulings` anchor to jump people directly to that portion of the page when they open the link.

Ex:
https://scryfall.com/card/cn2/78
vs 
https://scryfall.com/card/cn2/78#rulings

We use this ID anchor for our own bot, so it won't suddenly change or be removed

<img width="742" alt="45ywvzl1s1" src="https://user-images.githubusercontent.com/769083/36692374-df96507a-1b05-11e8-8db7-0123f0f3ead1.png">

**Comment by bakert** [comment]
b3fc781c.

Thanks for the suggestion!
