### ISSUE TITLE
"Sep 03" is not a very human friendly date

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#436]
Sep 3rd?

**Comment by bakert** [comment]
Here's what we're using right now as you recede into the past:

3 seconds
7 minutes
5 hours
2 days
3 weeks
Sep 03
Mar 29 2016

Here's what Facebook uses for newsfeed posts as you recede into the past:

Just now
56 mins
6 hrs
October 18 at 3:33pm
June 19
December 17, 2015

"November 30" and "November 30, 2015" forms add considerable width to the column making it less likely to 

I'm thinking "Sep 3" and "Sep 3, 2015" might be a slightly more human and acceptable version.

**Comment by bakert** [comment]
8c2582c for the preceding zero change. We probably don't want more than that because it makes the column too wide.

**Comment by silasary** [comment]
I prefer "3rd September", but that might just be a pushback against US date format.

**Comment by bakert** [comment]
The Americans won, you're going to have to accept that. We could localize but I don't think it's worth it.
