### ISSUE TITLE
Merge "Back_Alley" with "Back_Alley_G"

### ISSUE THREAD

**Issue by BackAlleyG** [PennyDreadfulMTG/Penny-Dreadful-Tools#4400]
I fixed my username on goldfish to match my discord/mtgo name for future times but still needs merging. The other one only has goldfish decks but no reason for there to be an excess extra person on the pdm site.

**Comment by bakert** [comment]
@BackAlleyG you need https://pennydreadfulmagic.com/link/

**Comment by BackAlleyG** [comment]
I'm not seeing how to fix it with that link. there's nowhere on the page that i can see where I'm able to add a name or merge names. Am I missing something?

**Comment by bakert** [comment]
<img width="745" alt="captura de pantalla 2018-04-19 a la s 8 38 07 p m" src="https://user-images.githubusercontent.com/1541/39011401-a0055bce-4411-11e8-813d-9bbb29f7d54c.png">

?

Or are you talking about having TWO mtgg usernames?

**Comment by BackAlleyG** [comment]
Originally, my mtggoldfish name was different and then I changed it on mtgg after realizing it but there were a few decks left under the old name. This is what my screen looks like

![image](https://user-images.githubusercontent.com/31076829/39011548-be798b5c-43df-11e8-8f9f-cb5dc676b7e3.png)

**Comment by bakert** [comment]
Got it. That makes sense. And do both accounts now exist on tappedout/mtgg? Ir is everything under Back_Alley_G in all places?

**Comment by BackAlleyG** [comment]
My username is the same across all sites now since updating the mtggoldfish name and I have only had one account for each site.

**Comment by bakert** [comment]
Alright, we got there, I think :D let me know if anything looks weird.
