### ISSUE TITLE
Don't include decks with currently illegal cards in card stats

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#442]
Possibly exclude them from other things too?

Show the no entry sign in the margin on deck list?

**Comment by silasary** [comment]
I felt bad bumping a Season 1 deck to the top of the page, but I felt it was important to actually have a test case for illegal decks.

**Comment by silasary** [comment]
We should hide the whole deck if the deck is illegal?
Hiding part of the deck from that list feels worse than hiding none of it.

**Comment by bakert** [comment]
I think in much the same way that we include tapped out decks even though they may never even have been played our basic philosophy should be inclusive. So if your deck was _ever_ legal then you have a place on the site. (If you were _never_ legal but tagged pd I could go either way – speculation for next season seems to point towards including those too.)

I think our initial views should be "useful". Our primary use case is someone looking for a deck they could play now. So if they are jammed with illegal decks that is bad.

Default sort begin most recent first does a lot of work here. I can see an argument for displaying everything and just indicating which are not currently legal with the no entry sign. Of course as soon as you sort by anything else you'll have a jam of illegal decks alongside legal decks.

(Another use case to think about is a Gatherling or League deck that's illegal because of a one-of sideboard card or a typo.)

The two main ways to control for illegal decks showing up "too much" occur to me:

(1) updated_date > start_of_season
(2) Must be legal

There's probably not much difference between these two in practical terms.

I also think there's an argument for not including non-touranment/league decks in the initial view and hiding them behind a "show me everything" type button.

Potentially every page that shows a decklist contains a UI element that allows you to filter and is set by default to {current season, tournament decks}. This could be persistent or not across the site.

This could apply to card stats, too.

[X] current season
[  ] season 1
[  ] all seasons

[X] tournament decks
[  ] all decks

**Comment by bakert** [comment]
We know we want to be able to restrict all views to current season or even a past season but that's a broader problem than this here, and I think we're happy with recent decks at the top doing most of the work for us here.
