### ISSUE TITLE
Show legality of decks in previous PD seasons

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#443]

**Comment by silasary** [comment]
Depends on #458

**Comment by bakert** [comment]
We did this. Woo!

**Comment by silasary** [comment]
Not quite yet.

**Comment by silasary** [comment]
I want to include the legalities column on the main page.

I have some ideas as to how to do it neatly, and throw together a prototype 24-48 hours from now

**Comment by bakert** [comment]
Is it useful enough to take up precious screen width on the main page? A deck is either legal for the thing I care about or not. It's legality in various other scenarios doesn't interest me.

As long as our focus remains PD legal decks there's only really two modes "legal now" and "legal in the past" and I'd be happiest with that being a toggle rather than a column. We can mark currenlty-illegal decks with the same no entry sign we use on cards in the margin on lists?

**Comment by silasary** [comment]
I did this.
