### ISSUE TITLE
Gatherling scraper seems to make duplicates of some competitions, with no decks

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4443]
I cleaned this up once but it's now present again for APAC tourneys and some others.

    SELECT GROUP_CONCAT(id) FROM competition GROUP BY url HAVING COUNT(*) > 1;

**Comment by bakert** [comment]
This also messes up /admin/prizes because the duplicate APAC tournaments get added as PDS tournaments and prizes get added in.

Gatherling scraper needs fixing to understand that APAC Sundays exist as a first step.

**Comment by jgabrielygalan** [comment]
APAC needs some special casing. In gatherling.py line 45, we are setting the competition series name to "Penny Dreadful Sundays", so it finds the other one (id=4). But in the DB, there are duplicate rows for the APAC tournaments, did you add them by hand? I can't see in the code how it can insert any competition for competition_series.id=7.

**Comment by bakert** [comment]
I did in fact change them by hand. Which caused them to get re-scraped.
