### ISSUE TITLE
Google search CSS changed again, now ugly

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#4454]
![image](https://user-images.githubusercontent.com/194254/37550335-8f691928-29df-11e8-9a80-a03b47539f7d.png)
Firefox, Win10

**Comment by bakert** [comment]
Google changed what they send us again. Ideal fix here is to build the typeahead and skip Google. But we can wrangle the Google stuff if that's too much effort :D

**Comment by silasary** [comment]
Between https://scryfall.com/docs/api/catalogs/card-names and internal data, typeahead seems doable

**Comment by bakert** [comment]
I'm looking forward to typeahead but the CSS wrangling wasn't too hard so it's in c22c1bbb for now.
