### ISSUE TITLE
"Choose one of your recent decks" should be a floaty option not embedded in the form like any other field

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4473]

**Comment by jgabrielygalan** [comment]
What is a "floaty" option?

**Comment by bakert** [comment]
It's not a required form field so at the very least it should be at the top but best of all it should not be in the normal flow of the form at all. Where it sits it feels to me like it's something I'm meant to select. And if I do that I overwrite the decklist I just put in above.

**Comment by bakert** [comment]
So some kind of js thing off to the side or hugging the decklist box in some way. Rather like or integrated with the upload option perhaps.

**Comment by bakert** [comment]
8439f0b2 moves it up in the form and changes the wording to match Gatherling.

I'd still like a "floaty" thing but this will do for now.
