### ISSUE TITLE
pennydreadfulmagic.com intro text says 5 weekly tournaments instead of 6

### ISSUE THREAD

**Issue by zserdely** [PennyDreadfulMTG/Penny-Dreadful-Tools#4549]
> Penny Dreadful. The ultra-budget, 10,000-card Magic Online brewer's paradise with powerful cards, **five** free weekly tournaments, free 24/7 league, prizes, quarterly rotations, and a super friendly community.  
  
The number seems correct in the FAQ right under the intro.

**Comment by bakert** [comment]
Hardcoded, not using dynamic text as most other sites are. Changed to be dynamic in 488b9764.
