### ISSUE TITLE
Some never before legal cards show up on cards page with a imaginary deck listed 

### ISSUE THREAD

**Issue by BackAlleyG** [PennyDreadfulMTG/Penny-Dreadful-Tools#4566]
![image](https://user-images.githubusercontent.com/31076829/38574057-d5d01d5a-3cc5-11e8-856c-a67058853b9b.png)

Not sure what the cause of this is. Birds of paradise of courser of craterhoof behemoth are two examples shown in the picture. Neither have a deck page shown on their card page, at least one that is normally shown. Might be because pdbot occasionally watches other format games as far as I know and they coulb be added from captured game logs maybe. No clue otherwise.

**Comment by bakert** [comment]
Wow, that's weird.

**Comment by silasary** [comment]
It's not from PDBot.  Nothing from PDBot feeds into this DB

**Comment by jgabrielygalan** [comment]
It's a mtgg deck: https://www.mtggoldfish.com/deck/555409#online

**Comment by jgabrielygalan** [comment]
Should we delete this deck from the DB?

**Comment by bakert** [comment]
I guess it will be interesting to see if the mtgg scraper adds it back :P

**Comment by jgabrielygalan** [comment]
I've deleted the deck. Let's see at xx:28 if it's added again.

**Comment by jgabrielygalan** [comment]
It was not readded, so I'm closing this. There was probably a bug in the legality check the first time this deck was scraped or something.
