### ISSUE TITLE
Move logsite into the main repo

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4657]
Lots has been done here already but I'm making a list of outstanding things.

 - [x] /people/ is broken at least with latest MySQL if not completely.
 - [x] `make lint` reports duplicate code between things like the NotFound page of decksite and the NotFound page of logsite. These should probably be shared in some fashion.
 - [x] SETUP contains no instructions on how to get logsite working, including adding a GRANT ALL statement.
 - [x] logsite doesn't have entries in config.json.example (and doesn't use `configuration` at all?)
 - [ ] ~~~`db.DB` is kind of ugly and might be better off behind the db()-style naming that decksite uses.~~~
 - [x] Some names in `db.py` are exempted from being pylint-checked to our standard because I wasn't sure if SQLAlchemy needed those specific case-sensitive names or not. We should check
 - [x] The whole of logsite_migrations is exempted from pylint because it's generated code (right?)  but Codacy will probably still try and check it.
 - [x] Rather than being excluded in the Makefile it would be nice to find a generated-members or extension-pkg-whitelist-style solution for excluding 
 - [ ] ~~~The very broard 'query' is now in generated-members in pylintrc because SQLAlchemy magically adds a query method to some classes. It would be nicer to do this in a more constrained way if possible.~~~

**Comment by silasary** [comment]
/people/ seems to work for me.  Can you provide me with an example?

Logsite does use configuration.  But the only new config it needed to add was `logsite_database`.

The names for `Add`, `Commit`, etc are entirely arbitrary, because I was getting very confused by things, and I found that giving them more obvious names helped identify the difference between several different methods named similarly.  We can safely change them to snake_case, but I'd want to do something else instead.

Codacy should respect the pylint exemption.  Also, I don't think it's working right now.

**Comment by bakert** [comment]
The error for me in /people/ and /stats.json is from a recent MySQL change.

```

sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError)
(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains
nonaggregated column 'pdlogs.match.id' which is not functionally dependent
on columns in GROUP BY clause; this is incompatible with
sql_mode=only_full_group_by") [SQL: 'SELECT `match`.id AS match_id,
`match`.format_id AS match_format_id, `match`.comment AS match_comment,
`match`.start_time AS match_start_time, `match`.end_time AS match_end_time,
`match`.has_unexpected_third_game AS match_has_unexpected_third_game,
`match`.is_league AS match_is_league, `match`.is_tournament AS
match_is_tournament, count(`match`.format_id) AS count_1 \nFROM `match`
\nWHERE EXISTS (SELECT 1 \nFROM match_players, user \nWHERE `match`.id =
match_players.match_id AND user.id = match_players.user_id AND user.id =
%s) GROUP BY `match`.format_id ORDER BY count(`match`.format_id) DESC']
[parameters: (576,)] (Background on this error at: http://sqlalche.me/e/e3q8
)

```

If you Google "contains nonaggregated column mysql" you'll see the details.
Basically MySQL used to (or still does depending on version/settings) let
you get away with SELECTing something that isn't uniquely identified from
the aggregated row by your GROUP BY and now it doesn't. I think we fix this
in SQLAlchemy with `with_elements` to say we don't want the match_id but I
am not a SQLAlchemy scientist. As neither prod nor your machine care this
is probably low pri, until it isn't :D

Toy example:

CREATE TABLE example (x INT, y INT);
SELECT x, y FROM example GROUP BY x;

This used to give you a random value from the ys being aggregated in the y
column with no error, now it gives you an error because it can't know which
value of y from the aggregated rows you "want" in the result set.

I fixed up all the queries in decksite that had the issue (and in my
Fantasy Football game) but the SQLAlchemy layer makes this ein bisschen más
difícil.

2018-04-23 19:23 GMT+02:00 Katelyn Gigante <notifications@github.com>:

**Comment by bakert** [comment]
Still an issue with latest SQLAlchemy. Hopefully they magically fix it for us before it screws us …

**Comment by bakert** [comment]
[bestcoast 3896f062] Include logsite in setup instructions.

**Comment by bakert** [comment]
[bestcoast 14d40c07] Use standard method names in logsite db operations.

**Comment by bakert** [comment]
The only remaining issue here is that logsite fails on /people/ with only_full_groupby on. This is default for latest MySQL but I guess not for MariaDB.

**Comment by bakert** [comment]
Looking into this a bit deeper it seems we have control of the GROUP BY so should be able to fix this ourselves. SQLAlchemy is a lot less magic and a lot more "sql in python" than I assumed.

**Comment by bakert** [comment]
What we are trying to say here is:

```
SELECT f.name, COUNT(*) FROM match_players AS mp INNER JOIN `match` AS m ON mp.match_id = m.id INNER JOIN format AS f ON m.format_id = f.id  WHERE mp.user_id = %s GROUP BY f.id;
```

We just need to find the SQLAlchemy way to say it.

**Comment by bakert** [comment]
27df7bcd.
