### ISSUE TITLE
Only include the normalized color in the deck title if the original author included the color in their deck title

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#466]
I know the objections raised to normalizing titles were mostly philosophical and that we've largely chosen to ignore them but I do think "Ghazi-Glare" => "Selesnya Ghazi-Glare" is unnecessary given the presence of the color indicators.

I was doing that because I didn't want "Mono B Control" => "Control". But if we use the presence of colors in the original title as the arbiter we remove some of the mangling that folks were finding so objectionable.

**Comment by bakert** [comment]
Examples:

"Mono B Control" => "Mono Black Control"
"o look a mountain" => "O Look a Mountain"
"UB" => "Dimir"
"U/B Control" => "Dimir Control"
"Ghazi-Glare" => "Ghazi-Glare"
"Ally Drain" => "Ally Drain"
"Mono G" => "Mono Green"
"Ooey Gooey Madness" => "Ooey Gooey Madness"

**Comment by silasary** [comment]
Definitely an improvement 😄

**Comment by bakert** [comment]
f9a4895.
