### ISSUE TITLE
Work out how to unify decks

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#467]
For people:

They're obviously going to be the same some reasonable amount of the time and going to silasary's page and not seeing all of silasary decks is just silly.

Likewise they are not in lockstep and bakert/bakert99 would ideally be unified too.

Then there's the nightmare scenario where they are identical but don't refer to the same person. Unlikely to matter but possible.

For decks:

If rykerboy puts up his Demonic Rising deck on tappedout to show what he played in the tournament we possibly want to unify these in some way. At the very least they should "point" at one another. And if they are the same 75 it makes sense to only have one page displaying them with two source links?

**Comment by silasary** [comment]
As far as combining decks:
I have a tappedout list for each of my decks.  These are regularly updated as I change things.
At the time of a tournament, the two versions will be identical.  
A week later, the TappedOut version may be different.
If we do combine, we need to do it in a non-permanent way.

**Comment by bakert** [comment]
Unless we treat each retrieval of tapped out as a snapshot that doesn't change. But that seems like a bad idea.

**Comment by silasary** [comment]
That feels like a very bad idea

**Comment by bakert** [comment]
Ok. So temporary "links" only or we just point one at the other and let the viewer work it out.

**Comment by silasary** [comment]
We have unified people. (At least until mtggoldfish users are introduced into the mix)

**Comment by silasary** [comment]
Note that unlike users, we don't actually squash decks, or even hide duplicates on the main page. 
But identical decks know about each other, and appear on each other's pages. (But only if they have competition stats)
A tappedout copy will never show from a league deck, but a league run will appear on a tappedout deck's page.
