### ISSUE TITLE
Validate league decks on input and reject if not valid

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#473]
With MTGO export instructions if it's a formatting issue and deck check/legal cards/bot link if it's a card legality issue.

**Comment by bakert** [comment]
Note: the deck must be able to tell you WHAT is wrong not just that the deck is not legal. This makes our primitive oracle.legal_deck even less suitable than it is for our current uses.

**Comment by silasary** [comment]
#463 has an overhaul of legality checking that will help with that.

**Comment by bakert** [comment]
We do this now.
