### ISSUE TITLE
Perf Audit

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4739]
Something somewhere is giving MySQL an awful lot of work to do. I'm going to do a quick local perf audit with run.py decksite-profiler and see if I can find any smoking gun(s).

**Bad**

 - [x] past season page -> all decks (**17s**,  **13.4s** in mustache rendering, **2.8s in posix.stat**, **1.5s db** in 14 calls)
 - [x] admin archetypes (**15.3s**, **7s in 19 db calls**, **14s in load_similar_decks**) ~~(**28s**, **16s in 55 db queries**, **5.4s in deck.load_cards (13 calls)**, **25s in deck.load_decks**~~)
 - [x] admin people notes (**10s**, **7s deck.load_decks**)

**Not Great**

 - [x] rotation changes (**3.5s**, **2.1s mustache rendering**, 458ms in view.prepare_card)
 - [x] what is penny dreadful? (2.9s, **2.1s for 22 db calls**) 
 - [x] person detail page (2.9s, half db and half `card.__init__`) ~~(5s, **3s in only_played_cards**)~~ ~~(**9.7s**, 7.3s db, 24 queries, **1.3s in card.__init__** 18,227 calls, **1.4s in oracle.load_cards** 1 call, 532ms in Much.__setattr__, 450ms in mustache renderer)~~
 - [x] sign up (2.9s, almost all db, looks like a lot of small queries - 30 in total, compare 14 on decks, 11 on archetypes, 17 on people, 450ms rendering mustache)
 - [x] home/metagame (2.4s, almost all db, **1.8s in deck.load_decks**, 3 calls; 0.5s in card.played_cards) ~~(6.2s, almost all db, **4.1s in card.played_cards**)~~
 - [x] admin prizes (2.5s, **2.3s in deck.load_decks**)
 - [x] retire (2.3s, 800ms on 5 calls to deck.load_decks, 24 database calls)
 - [x] deck check (2s, mostly db, 586ms in deck.load_decks, 29 queries)
 - [x] people (2s, 450ms in pystache renderer)

**Ok**

 - [x] report (1.4s, mostly db, 600ms on 6 calls to deck.load_decks)
 - [x] competition detail page (1.3s for league (200ms for gatherling), 750ms mustache rendering, 200ms Gatherling, deck.load_cards 332ms, oracle.deck_sort called 10,000 times for total 215ms. This probably moves to "not great" category late in a league with current participation levels)
 - [x] records (1.3s, most mustache rendering)
 - [x] cards (1.3s)
 - [x] matches (1.1s)
 - [x] latest decks (0.9s)
 - [x] link accounts (0.9s, almost entirely in 17 db queries)
 - [x] archetypes (0.6s)
 - [x] competitions/competition results (974ms)
 - [x] archetypes detail page (785ms, 605ms in 19 db calls)
 - [x] rotation speculation (705ms)
 - [x] tournament info (538ms)
 - [x] league/league info (506ms)
 - [x] card detail page (471ms)
 - [x] bugs (241ms)
 - [x] leaderboards (180ms)
 - [x] past seasons (174ms)
 - [x] hosting (143ms)
 - [x] resources/external links (142ms)
 - [x] community guidelines (138ms)
 - [x] news (132ms)
 - [x] admin / admin home (131ms)
 - [x] faqs (131ms)
 - [x] admin rotation (130ms)
 - [x] about / what is pennydreadfulmagic.com? (129ms)
~~- [ ] gatherling~~
~~- [ ] discord chat~~

**Comment by bakert** [comment]
Issue on home is calling decksite.card.played_cards() to get the fastest rising/season/etc. tables. Seasonizing this query to the current season makes the homepage much faster and really is the last month at all interesting when a new season just started? We actually want it seasonized.

This query will be slow at /seasons/all/cards/ still but that seems like much less of a concern.

New version takes 2.43s instead of 6.2s. 0.5s in played_cards now.

f0fc411.

**Comment by bakert** [comment]
For person detail page the big issue is "only played cards". I seasonized the cards list and brought this down to 5s. That needed doing anyway.

only_played_cards is the biggest culprit here. I'm not sure if seasonizing would give us the boost we need nor if that's desirable behavior.

**Comment by bakert** [comment]
Seasonized unique cards played to get us down to 2.9s.

**Comment by bakert** [comment]
Loading similar decks (for archetype suggestion) as a one-time operation instead of dec-by-deck saves more than 10s on /admin/archetypes but still takes 13s. 8fa2dde9.

**Comment by bakert** [comment]
Worst offender on past season decks list is now /seasons/7/ because it shows the most decks. While it's possible we want to rejig the display of seasons quite a bit to make them nicer (I can see us changing the banner color to a season-specific color and having all links navigate you within that season, make a nice composite image of that seasons most notable maindeck cards, etc.) it's true that we want to show all the decks of the season in one way or another somewhere.

Options:

(1) Make this faster.
(2) Not care because it's rarely loaded (although will it cause pain from all the web crawlers visiting it anyway?)
(3) Introduce pagination by clicking
(4) Introduce pagination by scrolling

Some disordered thoughts:

- I don't think loading the complete list of decks for the season is a super compelling and frequent requirement but I can imagine wanting to do it. And I can doubly imagine wanting to load all league decks to find the 5-0s with the best OMW and that kind of thing. Or order by record to scan the top N for colors/peoples names.
- However big this list gets clicking  on the header for "record" should (as quickly as possible) show  you the  decks with the best record across the whole resultset. So the query is going to have to be fast in any future scenario. So any time spent on making the query significantly faster is time well spend.
- It's not that useful to have a page of 10,000  decks.
- We don't use every piece of data we generate when showing this list.
- There is some possibility (but definitely not guaranteed)  that this would feel faster, better, more useful in a React component talking to some back end via GraphQL to get exactly what it wants and no more showing 100 or 200 or 25 or however many decklists at a time. With ordering across the whole resultset.
- The entire set of everything shown in this view for not-the-current-season is essentially static but we calculate it on the fly every time. We could write it as HTML or some easily rendered structure once and never do  it again. This would not apply to current season lists and lists of similar decks and other decklists that might get long although we could generate those at write time or asynchronously and feed them in the same way. Something something memcache.

**Comment by bakert** [comment]
I wonder if limiting similar decks to the current season is good or bad. It would improve the performance of deck detail pages and /admin/archetypes but I'm not sure it's a good idea.

**Comment by bakert** [comment]
Ignore the not-very-sensible urls for now but:

`/seasons/7/decks/` takes 1.9s server time to find and render us 500 decks.
`/seasons/7/` takes 11.2s to do the same thing for all 5392 decks of the season which then take an astonishing amount of time to finish with the tabley js (shouldn't it be skipped?)

Although the server time is clearly an issue, it's actual the client behavior that is more worrisome here. I'm going to check that our js skip is working for this kind of table.

**Comment by bakert** [comment]
js skip was only for card tables until now. Extended to deck tables with 9bf19a3e. Time to display table cut down hugely (to about 10s from browser says "do you want to keep waiting" type times) although for everything to be completely done is still 20s or so.

**Comment by bakert** [comment]
```
        self.deck['maindeck'].sort(key=lambda x: oracle.deck_sort(x['card']))
        self.deck['sideboard'].sort(key=lambda x: oracle.deck_sort(x['card']))
```

costs 2.5s and only affects the mouseover in this view. deck_sort gets called 130,000 times which seems like too many times to sort 5392 decks and sideboards.

**Comment by silasary** [comment]
These numbers probably need recalculating again.

**Comment by bakert** [comment]
**Bad**

 - [ ] /seasons/all/ (33.4s, 5s db, 1.6s sorting, 1.1s accessing attributes, 14.3s in prepare_deck and below)
 - [ ] /decks/16717/ (7.7s, 5.6s db, 1.5s in deck.load_cards, 5.1s load_decks_heavy, 6.5s in __init__ of views/deck.py which seems definitely wrong)

**Not Great**

 - [ ] /people/bakert99/ (3.7s, 2s db, 0.5s in Munch)
 - [ ] /competitions/ (3.6s, almost all in `load_decks_heavy`)
 - [ ] / (3.5s, all db)
 - [ ] /signup/ (3.5s, mostly db - 18 queries)
 - [ ] /admin/people/notes (3.4s, 2.9s db)
 - [ ] /archetypes/aggro/ (3.1s, 1.2s db, 1.5s mustache render)
 - [ ] /admin/prizes/ (3.1s, mostly db)
 - [ ] /seasons/all/decks (2.9s)
 - [ ] /about/pd/ (2.2s, db)
 - [ ] /cards/ (2.2s, 1s on 3 db queries, 1s mustache render)

**Ok**

 - [x] /deckcheck/ (2s)
 - [x] /cards/Burst Lightning/ (1.8s)
 - [x] /admin/archetypes/ (1.5s)
 - [x] /rotation/changes/ (1.4s) 
 - [x] /report/ (1.1s)
 - [x] /rotation/speculation (1s)

**Good**

 - [x] /link/ (0.9s, all db)
 - [x] /league/current/ (0.9s) - rendering the tables makes it feel slower tho.
 - [x] /archetypes/ (0.6s)
 - [x] /tournaments/ (0.4s)
 - [x] /competitions/474/ (0.1s) - I'm really not sure how this is so fast but I guess it shows where we should be aiming!
 - [x] /bugs/ (0.1s)
 - [x] /tournaments/leaderboards (0.1s)
 - [x] /seasons/ (0.1s)
 - [x] /resources/ (0.1s)
 - [x] /tournaments/hosting/ (0s, to nearest 100ms)
 - [x] /community/guidelines/ (0s)
 - [x] /admin/ (0s)
 - [x] /faqs/ (0s)
 - [x] /admin/rotation/ (0s)
 - [x] /about/ (0s)

**Comment by bakert** [comment]
#4959 is a bit more up to date version of this.
