### ISSUE TITLE
Combine logsite and decksite into a single Flask instance

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4743]
**Arguments For**

  - Reduce code duplication
  - Simplicity
  - Avoid the need for 'shared_web'
  - Share CSS and other things without copying
  - Better error pages for logsite (rather than redundant worse copies)

**Arguments Against**

  - Logsite is more stable than decksite and combining them will reduce uptime for logsite†

**Notable Things**

  - You can't turn off "duplicate-code" for pylint selectively so I've inserted "logsite duplication" comments into numerous places so that the linter passes, referencing this ticket.

† = Is this true? Seems like it's either the db or the machine as a whole that dies, talking logsite with it. It might be decksite's *fault* but that's an argument for fixing decksite not keeping logsite separate.

**Comment by bakert** [comment]
Ooh, violent revolution :D

**Comment by silasary** [comment]
It was the Correct™️ way.
