### ISSUE TITLE
We know who has active league runs and what their decks are called so provide a nice UI/typeahead when entering results

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#475]
Or even a dropdown.

**Comment by endidymion** [comment]
A dropdown that lets me select a deck from my currently active runs would be phenomenal. Aside from being easier, it would eliminate typos and save me from having to remember what my dumb ass named my deck this time.

**Comment by bakert** [comment]
I made dropdowns for this for now. I think a typeahead is nicer and less error prone but that's a v2 feature.
