### ISSUE TITLE
Seasons dropdown should only have relevant seasons on each page, or have an empty page not a 404

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4788]
Perhaps a different visual treatment of the seasons where there are/are not entries.

**Comment by silasary** [comment]
This would involve querying the other seasons.  Potential perf issue.

**Comment by bakert** [comment]
15eb6a21 puts in "empty page" for archetypes. We already have it for people and cards. I think we're done here. We'll put all seasons on the dropdown but have a sane response if you click a season where (for example) there were no Necro Control decks.
