### ISSUE TITLE
Deck name = B gets normalized to "None" when there are no colored mana symbols in the deck's cards

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#479]

**Comment by bakert** [comment]
Not that anyone should call their deck "B". But they might.

**Comment by silasary** [comment]
Potential deck name: "U B UB Blind Seer shenanigans". (I kinda want to
build it now)

**Comment by bakert** [comment]
I think if you make that deck and name it like that you deserve everything you get :)

**Comment by bakert** [comment]
I think this must have been when there were data issues because I can't repro. Closing.

**Comment by bakert** [comment]
I worked it out. It's when there are no colored mana symbols in the deck. I've been testing with 60 Swamps and 60 Islands quite a lot.

Such a thing is conceivable so we should cope.

**Comment by bakert** [comment]
371af5f adds 'Colorless' for a deck with no colored mana symbols.
