### ISSUE TITLE
Charts are misbehaving

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4795]
The recent change to regenerate if smaller than a certain size seemed to improve things but I've seen a spate of bad ones

Examples:
https://pennydreadfulmagic.com/decks/14219/
https://pennydreadfulmagic.com/charts/cmc/14951-cmc.png

**Comment by silasary** [comment]
Example looks fine to me.

**Comment by bakert** [comment]
So these are still fixing themselves using the new file size checking technology. But they seem to be showing the first time around. Do we check the file size immediately after generation as well as on cached-on-disk load?

**Comment by bakert** [comment]
We are not.

```
    if os.path.exists(path):
        if os.path.getsize(path) > 1024 * 1024 * 8:
            return path
        else:
            logger.warning('Regenerating graph for {deck_id} because the existing one is suspiciously small.'.format(deck_id=deck_id))
```

So the question is do we want to (a):

    - Regenerate on user time if it fails (to a max of 2-3 times I suppose).
    - Show nothing if file size is suspiciously small on first load
    - Be content with  current behavior and show some ugly graphs sometimes that get regenerated when revisited.

**Comment by bakert** [comment]
2436a55
