### ISSUE TITLE
We use `url_for` in Deck but that only works in application context

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#481]
We should probably do it somewhere else.

**Comment by silasary** [comment]
Currently we have an application context whenever we do anything related to
the decksite.  But yeah, it night be neater if we don't need one for the
scrapers to function.

**Comment by bakert** [comment]
Oh, cool. I found out in my test for card legality. I guess "bug" is a bit harsh but we should refactor so it doesn't work like that.

**Comment by bakert** [comment]
I removed it from there and pushed it onto the view.
