### ISSUE TITLE
make test TEST=mana no longer supports testing a single test

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4832]

**Comment by bakert** [comment]
Not sure this actually matters as unit tests now run in 13s

**Comment by silasary** [comment]
`make test magic/mana_test.py` should still work though?

**Comment by bakert** [comment]
doesn't look like it.

**Comment by silasary** [comment]
Hmm.  I honestly don't know enough about the Makefile, to be honest - It doesn't work on Windows.

But I do know that `python3 dev.py test magic/mana_test.py` does work perfectly.

**Comment by bakert** [comment]
21ea24a is the cause. I'll revert it. Although I guess in the long term rolling this functionality into dev.py is the real solution.

I much prefer being able to say:

$ {thing} mana

to:

$ {thing} magic/mana_test.py

not least because I frequently don't know what dir it is in :D

**Comment by bakert** [comment]
I'm going to close this. It will naturally arise again when we delete the Makefile.
