### ISSUE TITLE
Support Commander in deck legality checking

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#489]
Check singleton, deck size, and ensure that all the cards have a color identity that matches or is a subset of the most-colorful legendary creature in the deck. That should be sufficient.

Of course it's completely useless right now so not important.

**Comment by silasary** [comment]
56eeae3283ec3a46bae3c11a55d49b3100b6c5d5

We don't verify Colour Identity, or highlight the commander.  But it does understand enough to say "This looks like a Commander Deck".

**Comment by bakert** [comment]
This seems good enough for now. We can get more radical if we ever need to. Closing.
