### ISSUE TITLE
Clean up the display of legality

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#490]
Now that we have it let's make it beautiful :)

**Comment by bakert** [comment]
Minor thing: cope with the possibility of a deck not being legal in any format.

**Comment by silasary** [comment]
When I originally implemented it, it did.

Has this changed?

**Comment by bakert** [comment]
It doesn't explode or anything It says "Legal in:" and then is blank.

**Comment by bakert** [comment]
Wrapped in our standard **ul** and accounted for no-legal-formats and added to card and put into a shared legal.mustache as of 8989176.

**Comment by silasary** [comment]
Ah. That should be easy enough to fix.
