### ISSUE TITLE
Some formats include all cards by default

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#494]
But we don't know that.

Examples:

Removing Tribal Wars Standard because of Swamp
Removing Tribal Wars Legacy because of Swamp
Removing Tarkir Block because of Swamp
Removing Prismatic because of Swamp
Removing Classic because of Swamp
Removing Freeform because of Swamp
Removing Singleton 100 because of Swamp

**Comment by bakert** [comment]
It's possible that mtgjson is not doing the right thing here compared to what they are doing for Legacy, etc.

**Comment by silasary** [comment]
Tribal Wars and Prismatic have weird deck building requirements.

Checking legality for them would involve a decent amount of heuristics.

**Comment by bakert** [comment]
According the mtgjson the only legal cards in Classic are:

Windseeker Centaur
Nalathni Dragon
Sewers of Estark

I think we can ignore all this nonsense.
