### ISSUE TITLE
Deck entirely composed of Islands shows only as legal in vintage, legacy and pd

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#508]
Should be legal in every format

**Comment by bakert** [comment]
Fixed earlier with other legality issues.

<img width="986" alt="screen shot 2016-11-04 at 8 46 52 pm" src="https://cloud.githubusercontent.com/assets/1541/20021880/d6d6aaca-a2cf-11e6-9f7c-0788c3e98e92.png">

**Comment by silasary** [comment]
Oh God.  We're doing block constructed now?
