### ISSUE TITLE
Do we want to offer mtg goldfish a feed of tournament results?

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#523]

**Comment by silasary** [comment]
That feels like a good idea

**Comment by bakert** [comment]
I asked them via email today. They've never responding to me before but they did fix the first thing I complained about (coincidence or not, you decide!) So we'll see.

**Comment by bakert** [comment]
They have now responded but they didn't mention this part of my email. I'll try them again in a bit. I think this would be good for PD exposure.

**Comment by bakert** [comment]
Pushed it a little bit with the mtgg person. I'm gonna close this on the basis that if they respond with a yes I can open a new ticket.
