### ISSUE TITLE
Denormalizing wins, losses and draws onto deck for league matches is janky

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#526]
But so is having that column be NULL when there are results. If we move to recording tourney matches and not just records this can be fixed by removing those columns. If not we can possibly leave them as NULL and derive in the SELECT?

**Comment by bakert** [comment]
Still janky. We can remove it when we do #516 which I feel we might do soon.

**Comment by silasary** [comment]
Agreed (Hence why I didn't actually close the issue)

**Comment by bakert** [comment]
Now covered by #516
