### ISSUE TITLE
Layout issue with News section

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#5458]
Windows 10, Firefox 62.

![image](https://user-images.githubusercontent.com/194254/46351566-03c0d600-c69b-11e8-891f-811ecee6d063.png)

**Comment by bakert** [comment]
Needs a min-width or wrapping in an &lt;article&gt; tag potentially.

**Comment by bakert** [comment]
bc8f7778
