### ISSUE TITLE
Text size is too small on mobile

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#552]

**Comment by silasary** [comment]
We need an entirely different layout for mobile

**Comment by bakert** [comment]
We have an alternate layout for mobile but mobile resolutions are getting so high that it doesn't actually kick in for things like latest iPhones :P – needs some work.

**Comment by bakert** [comment]
I fixed this. Our mobile layout is not perfect but there are open tasks for that. A lot of things are better including font size.
