### ISSUE TITLE
Person query can be slow and is not preaggregated

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#5564]
```
    SELECT
        p.id,
        LOWER(IFNULL(IFNULL(IFNULL(p.name, p.mtgo_username), p.mtggoldfish_username), p.tappedout_username)) AS name,
        p.mtgo_username,
        p.tappedout_username,
        p.mtggoldfish_username,
        p.discord_id,
        p.elo,
        num_decks,
        wins,
        losses,
        draws,
        perfect_runs,
        tournament_wins,
        tournament_top8s,
        win_percent,
        num_competitions
    FROM
        person AS p
    LEFT JOIN
        (
            SELECT
                d.person_id,
                COUNT(d.id) AS num_decks,
                SUM(wins) AS wins,
                SUM(losses) AS losses,
                SUM(draws) AS draws,
                SUM(CASE WHEN wins >= 5 AND losses = 0 AND d.source_id IN (SELECT id FROM source WHERE name = 'League') THEN 1 ELSE 0 END) AS perfect_runs,
                SUM(CASE WHEN d.finish = 1 THEN 1 ELSE 0 END) AS tournament_wins,
                SUM(CASE WHEN d.finish <= 8 THEN 1 ELSE 0 END) AS tournament_top8s,
                IFNULL(ROUND((SUM(wins) / NULLIF(SUM(wins + losses), 0)) * 100, 1), '') AS win_percent,
                SUM(DISTINCT CASE WHEN d.competition_id IS NOT NULL THEN 1 ELSE 0 END) AS num_competitions
            FROM
                deck AS d
            LEFT JOIN
                deck_cache AS dc ON d.id = dc.deck_id
            
    LEFT JOIN
        (
            SELECT
                `start`.id,
                `start`.code,
                `start`.start_date AS start_date,
                `end`.start_date AS end_date
            FROM
                season AS `start`
            LEFT JOIN
                season AS `end` ON `end`.id = `start`.id + 1
        ) AS season ON season.start_date <= d.created_date AND (season.end_date IS NULL OR season.end_date > d.created_date)

            WHERE
                season.id = 2
            GROUP BY
                d.person_id
        ) AS stats ON p.id = stats.person_id
    WHERE
        p.id = 0 OR p.mtgo_username = 'yandrak13' OR p.discord_id = 0
    GROUP BY
        p.id
    ORDER BY
        `num_decks` DESC, name
```

This mostly takes about 30ms but does show up in slow query reports. Not sure if optimization will help here or if it's a consequence of locking issues/other db activity. Opening a ticket for now to observe.

**Comment by bakert** [comment]
An option here is to denormalize the stats to a person_cache or similar as we do with deck_cache. It would be another thing to update when a match is changed (we already update deck_cache).

Alternatively this could be fully preaggregated as _person and lag reality like archetype stats and cards stats and other things currently do (and may forever?)

It feels weird to be optimizing something that takes 20-30ms on local but it shows up fairly often with 10s as the query perf threshold:

<img width="1348" alt="screen shot 2018-10-24 at 12 53 10" src="https://user-images.githubusercontent.com/1541/47457410-da700300-d78b-11e8-9226-077ba3e9cdea.png">

I might drop the threshold to 5s or less and see if it becomes much more frequent.

**Comment by bakert** [comment]
Checking for queries over 1s this is one of the four frequent offenders so looks like it does need to be either optimized or preaggregated.

**Comment by bakert** [comment]
```
EXPLAIN +------+--------------+------------+--------+----------------------------------+---------+---------+---------------+-------+----------------------------------------------+
| id   | select_type  | table      | type   | possible_keys                    | key     | key_len | ref           | rows  | Extra                                        |
+------+--------------+------------+--------+----------------------------------+---------+---------+---------------+-------+----------------------------------------------+
|    1 | PRIMARY      | p          | index  | PRIMARY,mtgo_username,discord_id | PRIMARY | 4       | NULL          |  2645 | Using where; Using temporary; Using filesort |
|    1 | PRIMARY      | <derived2> | ref    | key0                             | key0    | 5       | decksite.p.id |    10 |                                              |
|    2 | DERIVED      | start      | const  | PRIMARY                          | PRIMARY | 4       | const         |     1 |                                              |
|    2 | DERIVED      | end        | const  | PRIMARY                          | PRIMARY | 4       | const         |     1 |                                              |
|    2 | DERIVED      | d          | ALL    | NULL                             | NULL    | NULL    | NULL          | 24687 | Using where; Using filesort                  |
|    2 | DERIVED      | dc         | eq_ref | deck_id                          | deck_id | 4       | decksite.d.id |     1 |                                              |
|    3 | MATERIALIZED | source     | const  | name                             | name    | 203     | const         |     1 | Using index                                  |
+------+--------------+------------+--------+----------------------------------+---------+---------+---------------+-------+----------------------------------------------+
```

**Comment by bakert** [comment]
Warning from the EXPLAIN seems potentially very relevant:

```
| Warning | 1739 | Cannot use ref access on index 'discord_id' due to type or collation conversion on field 'discord_id'                                                            
```

We have discord_id as a VARCHAR but we're asking MySQL to find a match on an int and this is messing with what indexes can be used to execute the query.

**Comment by silasary** [comment]
discord_id should be a long.

**Comment by bakert** [comment]
I'm changing discord_id to be a BIGINT in 45.sql.

I'll keep this open because I doubt that's sufficient to clear this up but maybe.

**Comment by bakert** [comment]
`load_person` tries to be friendly by letting you pass a discord_id, an mtgo_username or a person_id. Because mtgo_usernames can be numbers this is ambiguous. And it's ambiguous at source in the url. There can in fact even be conflicts and one is coming up for mtgo_username=4423. 

```
mysql> SELECT mtgo_username FROM person WHERE LENGTH(CAST(mtgo_username AS SIGNED)) = LENGTH(mtgo_username);
+---------------+
| mtgo_username |
+---------------+
| 3844          |
| 4423          |
| 4643893       |
| 49547681      |
| r             |
+---------------+
5 rows in set, 2312 warnings (0.00 sec)
```

https://pennydreadfulmagic.com/seasons/all/people/3844/
https://pennydreadfulmagic.com/seasons/all/people/4423/

In such a case the code currently loads the person with that id. So when we reach our 3844th user (not far away - we're on 2779) the "vanity" urls above will stop working, and the pdm bot command for these people's pages too.

We should probably make load_person insist on knowing what kind of identifier you have passed in to make the query more efficient.

**Comment by bakert** [comment]
The fundamental issue for cleaning up the WHERE clause is that /people/4423/ is inherently ambiguous and we need to look into the db to know (a) do we have a person with id=4423 and (b) do we have a person with mtgo_username='4423'. I wonder if we should just introduce a convention for fully-numeric mtgo usernames so that their vanity url is not /people/4423/ but instead /people/_4423/ or similar. The bot can cope with this with a little extra logic and it's the only place apart from human typing that generates a vanity url anyway. Underscore won't work because that's an allowed character in an mtgo username.

Safe, non-alphanumeric characters that are not reserved or have a special meaning in a URL but do not require encoding: $-_.+!*'(),,

**Comment by bakert** [comment]
We have 34 usernames with hyphens, 189 with underscores, 1 with '(' leaving, 1 with ., 1 with '

0 with $+!*)

+ seems like a bad choice because of its use as representing a space in urls sometimes. ) seems terrible if we're excluding (.

So one of:

https://pennydreadfulmagic.com/seasons/all/people/$4423/
https://pennydreadfulmagic.com/seasons/all/people/$/4423/
https://pennydreadfulmagic.com/seasons/all/people/4423/$/
https://pennydreadfulmagic.com/seasons/all/people/4423$/
https://pennydreadfulmagic.com/seasons/all/people/!4423/
https://pennydreadfulmagic.com/seasons/all/people/!/4423/
https://pennydreadfulmagic.com/seasons/all/people/4423/!/
https://pennydreadfulmagic.com/seasons/all/people/4423!/
https://pennydreadfulmagic.com/seasons/all/people/*4423/
https://pennydreadfulmagic.com/seasons/all/people/*/4423/
https://pennydreadfulmagic.com/seasons/all/people/4423/*/
https://pennydreadfulmagic.com/seasons/all/people/4423*/

???

**Comment by bakert** [comment]
I think the dollar looks least weird to me.

Probably https://pennydreadfulmagic.com/seasons/all/people/$4423/

???

**Comment by bakert** [comment]
I guess in the initial case I'm going to screw the four people with numeric usernames by just having their vanity URL cease to function:

```
| 3844          |
| 4423          |
| 4643893       |
| 49547681      |
```

adding in an alternate vanity URL can wait.

**Comment by bakert** [comment]
This same issue also exists with archetypes but Lord I hope there's never an archetype name that's just an integer.

**Comment by adambiltcliffe** [comment]
Alternatively make the normal by-id URL into /people/id/nnnn and leave the vanity URLs as /people/username?

**Comment by adambiltcliffe** [comment]
Unless we ever have a player with the mtgo username 'id', I guess?

**Comment by bakert** [comment]
Even then the trailing part would make it unambiguous. That does seem better.

**Comment by bakert** [comment]
@silasary another issue here is the API thinks it can load via discord_id OR mtgo_username.

It's not possible to be totally unambiguous here. How do you feel about changing the API to have more than two endpoints for each of the currently existing three person-endpoints depending on whether you want to send a Discord snowflake or a Magic Online username?

See https://discordapp.com/developers/docs/reference to understand the next part if you're not already familiar with snowflakes.

Right now the lowest snowflake we have is 65546501476057088 (Dec 2015 as it happens) and the highest username is 49547681 but anything up to 99999999999999999999 (max 20 chars) is a legal MTGO username. Possibly we could bit shift the provided number to lop off the rightmost 21 binary digits and then consider the value a discord_id iff the remaining number is >= 0 and <= number of ms since Jan 1 2015 ("Discord epoch"). This would make the range of conflicting numbers an ever-growing set starting at 2097152 (1ms past Jan 1 2015, 7 digits) and ending at 66135785472000000 (approximately the end of 2019, 17 digits). We could make some assumptions about how soon after Discord epoch the first ever id was and reduce this range considerably. For example treating Feb 1 as the first practical date increases the lower end to 5617011916800000 meaning only some 16 and 17 digit mtgo usernames would conflict.

**Comment by bakert** [comment]
I have glorious-kluge'd this with the new `load_person_by_discord_id_or_mtgo_username` in 98e8402e which should make all WHERE clauses now use a single index to find what they are looking for.

```
def load_person_by_discord_id_or_mtgo_username(person: str) -> Person:
    # It would probably be better if this method did not exist but for now it's required by the API.
    # The problem is that Magic Online usernames can be integers so we cannot be completely unambiguous here.
    # We can make a really good guess, though.
    # See https://discordapp.com/developers/docs/reference#snowflakes
    # Unix timestamp (ms) for 2015-01-01T00:00:00.0000    =       1420070400000
    # Unix timestamp (ms) for 2015-01-01T00:00:00.0001    =       1420070400001
    # Unix timestamp (ms) for 2015-02-01T00:00:00.0000    =       1422748800000
    # Unix timestamp (ms) for 2100-01-01T00:00:00.0000    =       4102444800000
    # Discord timestamp (ms) for 2015-01-01T00:00:00.0000 =                   0
    # Discord timestamp (ms) for 2015-01-01T00:00:00.0001 =                   1
    # Discord timestamp (ms) for 2015-02-01T00:00:00.0000 =          2678400000
    # Min Discord snowflake for 2015-01-01T00:00:00.0000  =                   0 (                                        00000000000000000000000 in binary)
    # Min Discord snowflake for 2015-01-01T00:00:00.0001  =             4194304 (                                        10000000000000000000000 in binary)
    # Min Discord snowflake for 2015-02-01T00:00:00.0000  =   11234023833600000 (         100111111010010100100100000000000000000000000000000000 in binary)
    # Min Discord snowflake for 2100-01-01T00:00:00.0000  = 5625346837708800000 (100111000010001001111110010010100000000000000000000000000000000 in binary)
    # Discord snowflakes created between 2015-01-01T00:00:00.001Z and 2100-01-01T00:00:00.000Z will therefore fall in the range 2097152-5625346837708800000 if created before the year 2100.
    # We use 2015-02-01T00:00:00.000Z (11234023833600000) as the start of the range instead because it greatly reduces the range and we have seen no evidence of Discord snowflakes from before December 28th 2015.
    # This function will fail or (very unlikely) return incorrect results if we ever have a player with a Magic Online username that falls numerically between MIN_DISCORD_ID and MAX_DISCORD_ID.
    MIN_DISCORD_ID =   11234023833600000
    MAX_DISCORD_ID = 5625346837708800000
    if person.isdigit() and int(person) >= MIN_DISCORD_ID and int(person) <= MAX_DISCORD_ID:
        return load_person_by_discord_id(person)
    return load_person_by_mtgo_username(person)
```

We can change the API code if we prefer not to do this madness :D

**Comment by bakert** [comment]
We now have single value WHERE clauses when loading people which should use existing indexes. So now we wait and see if it's faster. If not we can look at preaggregation.

**Comment by bakert** [comment]
This query shows up as having taken >100s six times in June so far out of maybe 215 such reports. Looking at only >100s only shows us what happens when things were going catastrophically wrong, though. We’ll need to drop the threshold to report on whether this is one of our slower queries under normal operation still.

**Comment by bakert** [comment]
Dropped slow_query on prod to 10s. Let’s see.

**Comment by bakert** [comment]
There were no cases of this query being slow from Jun 23-Aug 1 (not sure when I put the threshold back up, however).

However it's a consistent offender at >100s (!) in late August, in September and in October so far. Not sure what to make of that.

**Comment by bakert** [comment]
The query below takes 0.00s on local but nearly 1s on prod. I wonder what that means.

```
SELECT
        p.id,
        LOWER(IFNULL(IFNULL(IFNULL(p.name, p.mtgo_username), p.mtggoldfish_username), p.tappedout_username)) AS name,
        p.mtgo_username,
        p.tappedout_username,
        p.mtggoldfish_username,
        p.discord_id,
        p.elo,
        num_decks,
        wins,
        losses,
        draws,
        perfect_runs,
        tournament_wins,
        tournament_top8s,
        win_percent,
        num_competitions
    FROM
        person AS p
    LEFT JOIN
        (
            SELECT
                d.person_id,
                COUNT(d.id) AS num_decks,
                SUM(wins) AS wins,
                SUM(losses) AS losses,
                SUM(draws) AS draws,
                SUM(CASE WHEN wins >= 5 AND losses = 0 AND d.source_id IN (SELECT id FROM source WHERE name = 'League') THEN 1 ELSE 0 END) AS perfect_runs,
                SUM(CASE WHEN d.finish = 1 THEN 1 ELSE 0 END) AS tournament_wins,
                SUM(CASE WHEN d.finish <= 8 THEN 1 ELSE 0 END) AS tournament_top8s,
                IFNULL(ROUND((SUM(wins) / NULLIF(SUM(wins + losses), 0)) * 100, 1), '') AS win_percent,
                SUM(DISTINCT CASE WHEN d.competition_id IS NOT NULL THEN 1 ELSE 0 END) AS num_competitions
            FROM
                deck AS d
            LEFT JOIN
                deck_cache AS dc ON d.id = dc.deck_id
            
    LEFT JOIN
        (
            SELECT
                `start`.id,
                `start`.code,
                `start`.start_date AS start_date,
                `end`.start_date AS end_date
            FROM
                season AS `start`
            LEFT JOIN
                season AS `end` ON `end`.id = `start`.id + 1
        ) AS season ON season.start_date <= d.created_date AND (season.end_date IS NULL OR season.end_date > d.created_date)

            WHERE
                TRUE
            GROUP BY
                d.person_id
        ) AS stats ON p.id = stats.person_id
    WHERE
        p.mtgo_username = 'draconeous'
    GROUP BY
        p.id
    ORDER BY
        `num_decks` DESC, name
```

**Comment by bakert** [comment]
EXPLAIN local:

```
+------+-----------------+------------+--------+---------------+---------------+---------+---------------+------+-------------+
| id   | select_type     | table      | type   | possible_keys | key           | key_len | ref           | rows | Extra       |
+------+-----------------+------------+--------+---------------+---------------+---------+---------------+------+-------------+
|    1 | PRIMARY         | p          | const  | mtgo_username | mtgo_username | 203     | const         | 1    |             |
|    1 | PRIMARY         | <derived2> | ref    | key0          | key0          | 5       | const         | 0    |             |
|    2 | LATERAL DERIVED | d          | ref    | person_id     | person_id     | 4       | const         | 7    |             |
|    2 | LATERAL DERIVED | dc         | eq_ref | deck_id       | deck_id       | 4       | decksite.d.id | 1    |             |
|    2 | LATERAL DERIVED | start      | ALL    | NULL          | NULL          | NULL    | NULL          | 12   | Using where |
|    2 | LATERAL DERIVED | end        | eq_ref | PRIMARY       | PRIMARY       | 4       | func          | 1    | Using where |
|    3 | MATERIALIZED    | source     | const  | name          | name          | 203     | const         | 1    | Using index |
+------+-----------------+------------+--------+---------------+---------------+---------+---------------+------+-------------+
7 rows in set (0.01 sec)
```

**Comment by bakert** [comment]
EXPLAIN prod:

```
+------+--------------+------------+--------+---------------+---------------+---------+---------------+-------+----------------+
| id   | select_type  | table      | type   | possible_keys | key           | key_len | ref           | rows  | Extra          |
+------+--------------+------------+--------+---------------+---------------+---------+---------------+-------+----------------+
|    1 | PRIMARY      | p          | const  | mtgo_username | mtgo_username | 203     | const         |     1 |                |
|    1 | PRIMARY      | <derived2> | ref    | key0          | key0          | 5       | const         |    10 |                |
|    2 | DERIVED      | d          | ALL    | NULL          | NULL          | NULL    | NULL          | 45713 | Using filesort |
|    2 | DERIVED      | dc         | eq_ref | deck_id       | deck_id       | 4       | decksite.d.id |     1 |                |
|    2 | DERIVED      | start      | ALL    | NULL          | NULL          | NULL    | NULL          |    12 | Using where    |
|    2 | DERIVED      | end        | eq_ref | PRIMARY       | PRIMARY       | 4       | func          |     1 | Using where    |
|    3 | MATERIALIZED | source     | const  | name          | name          | 203     | const         |     1 | Using index    |
+------+--------------+------------+--------+---------------+---------------+---------+---------------+-------+----------------+
7 rows in set (0.01 sec)
```

**Comment by bakert** [comment]
Versions differ slightly. 10.4.6-MariaDB on local, 10.2.16-MariaDB on prod.

**Comment by bakert** [comment]
CREATE TABLE is exactly identical for deck on prod and local.

I ran `ANALYZE TABLE deck` and `ANALYZE TABLE person` and now local behaves as badly as prod and has the same EXPLAIN output. WTF!

**Comment by bakert** [comment]
Funnily enough if I use a WHERE clause of `p.id = 2525` instead of `p.mtgo_username = 'draconeous'` then I get the same EXPLAIN on local as on prod. The query is then also 50x slower (0.01s  => 0.49s).

**Comment by bakert** [comment]
This leads to the absurd situation where replacing the WHERE clause `p.id = 2525` with `p.mtgo_username = (SELECT mtgo_username FROM person WHERE id = 2525)` makes things massively faster. But only on local, prod remains stubbornly slow with any version.

**Comment by bakert** [comment]
Converting the subquery to a JOIN makes things faster at the expense of not returning an "empty" row when the person has no decks (for that season).

Omitting the season join when selecting everything (`WHERE TRUE`) gives a 1s => 0.3s speedup on prod.

**Comment by bakert** [comment]
Measuring this is really difficult. I'm getting variability from 0.45s -> 5s for the same query run a few seconds later. On local I get very repeatable results but everything is fast there!

**Comment by bakert** [comment]
OK I think the only thing I can do is optimize the `p.id = ?` query on local and then ship that to prod and hope it helps.

```
SELECT
    p.id,
    LOWER(IFNULL(IFNULL(IFNULL(p.name, p.mtgo_username), p.mtggoldfish_username), p.tappedout_username)) AS name,
    p.mtgo_username,
    p.tappedout_username,
    p.mtggoldfish_username,
    p.discord_id,
    p.elo,
    p.locale,
    num_decks,
    wins,
    losses,
    draws,
    perfect_runs,
    tournament_wins,
    tournament_top8s,
    win_percent,
    num_competitions
FROM
    person AS p
LEFT JOIN
    (
        SELECT
            d.person_id,
            COUNT(d.id) AS num_decks,
            SUM(wins) AS wins,
            SUM(losses) AS losses,
            SUM(draws) AS draws,
            SUM(CASE WHEN wins >= 5 AND losses = 0 AND d.source_id IN (SELECT id FROM source WHERE name = 'League') THEN 1 ELSE 0 END) AS perfect_runs,
            SUM(CASE WHEN d.finish = 1 THEN 1 ELSE 0 END) AS tournament_wins,
            SUM(CASE WHEN d.finish <= 8 THEN 1 ELSE 0 END) AS tournament_top8s,
            IFNULL(ROUND((SUM(wins) / NULLIF(SUM(wins + losses), 0)) * 100, 1), '') AS win_percent,
            SUM(DISTINCT CASE WHEN d.competition_id IS NOT NULL THEN 1 ELSE 0 END) AS num_competitions
        FROM
            deck AS d
        LEFT JOIN
            deck_cache AS dc ON d.id = dc.deck_id
        
LEFT JOIN
    (
        SELECT
            `start`.id,
            `start`.code,
            `start`.start_date AS start_date,
            `end`.start_date AS end_date
        FROM
            season AS `start`
        LEFT JOIN
            season AS `end` ON `end`.id = `start`.id + 1
    ) AS season ON season.start_date <= d.created_date AND (season.end_date IS NULL OR season.end_date > d.created_date)

        WHERE
            TRUE
        GROUP BY
            d.person_id
    ) AS stats ON p.id = stats.person_id
WHERE
    p.id = 1
GROUP BY
    p.id
ORDER BY
    `num_decks` DESC, name
```

*Improvements*

- Changing the subquery into JOINs has no effect when retrieving all results but gives a 50x speedup when selecting for a single person. This means we need to make another very inexpensive query to make sure we have the people without decks as well as those with.
- Removing the season join gives a 3x speedup when selecting everything. 
- Denormalizing season_id onto deck_cache doesn't seem to help compared to the season join which surprises me.

So I'm going to elide the season join when season_id is None, and do the subquery removal. Looking at git log I can see the subquery was introduced solely to make people without decks show up in the resultset. We can do that faster with a little more code/a super cheap query.

**Comment by bakert** [comment]
d01c30d3.
