### ISSUE TITLE
Sort legality list in some fashion

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#558]
On both card and deck pages.

**Comment by silasary** [comment]
I assume this refers to the list of legal formats?

**Comment by silasary** [comment]
Right now, it's generated by the SQL order, which is influenced by the order they're inserted, which is influenced by... The alphabetical order of the first card legal in that format?

**Comment by bakert** [comment]
We have 5 and up seasons of PD to accommodate that most sites do not. But here's a quick survey of order elsewhere.

Scryfall:

<img width="320" alt="captura de pantalla 2017-07-19 a las 5 09 30 am" src="https://user-images.githubusercontent.com/1541/28350363-6c49b81a-6c40-11e7-9b1f-fb1b855abc66.png">

magiccards.info:

<img width="231" alt="captura de pantalla 2017-07-19 a las 5 10 06 am" src="https://user-images.githubusercontent.com/1541/28350382-83e92e92-6c40-11e7-8b5d-4ba2bfc082a4.png">

Magidex:
 
<img width="176" alt="captura de pantalla 2017-07-19 a las 5 08 53 am" src="https://user-images.githubusercontent.com/1541/28350341-5661c272-6c40-11e7-9270-726a4c9e6951.png">

combodeck.net:

<img width="307" alt="captura de pantalla 2017-07-19 a las 5 08 33 am" src="https://user-images.githubusercontent.com/1541/28350339-4b25983e-6c40-11e7-88ed-812c0103a0d9.png">

mtg-hunter:

<img width="187" alt="captura de pantalla 2017-07-19 a las 5 11 05 am" src="https://user-images.githubusercontent.com/1541/28350402-a8eb059e-6c40-11e7-8737-d72a32166497.png">

I think the scryfall version probably gives the most clarity.

But we are not a card search site. And we have additional past PD formats to account for. Maybe some kind of colored off/on graphic (with a middling color for restricted) for both PD formats and other formats?

**Comment by bakert** [comment]
One possible order is:

Penny 
Old Pennies
Vintage
Legacy
Modern
Standard
Block(s)
Commander

This has the advantage of putting blocks near the end which in the case of some cards will be multiple entries. Reversing everything from Vintage-Block probably makes more sense but front loads the less-interesting block information.

**Comment by bakert** [comment]
1850fe5c.
