### ISSUE TITLE
We use a very old version of jquery - upgrading has issues

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#5583]
Apparently jquery-latest was deprecated and frozen in about 2014. This is what happens when you work for an organization that rolls its own version of everything for four and a half years. The real way to CDN the latest jquery is:

```
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
```

They don't use a "latest" option for the same reason cdnjs don't offer one - long-lived expires headers and breaking changes in the release make for bad friends.

We can't just straight switch over because at the very least it messes up our loading spinners/table visibility thing. Will need a pass over the js and some fixes.

**Comment by bakert** [comment]
What happens with latest and tables is that the table header row shows first for a split second causing unsightly jumping around of the content. Why is anyone's guess :)

**Comment by bakert** [comment]
The problem here is that under 3.1.1 the internals of footable fire *after* the code underneath the footable initialization. It's either async or firing more than once under 3.1.1.

The problem is not seen in 2.4.0 (last 2.x.x version) and is seen in 3.0.0 so it's something that was changed for 3.0.0.

**Comment by bakert** [comment]
I tried the JQMIGRATE plugin, which is sweet, but it didn't show any relevant warnings.

**Comment by bakert** [comment]
We could go to 2.4.0 today I think but this wonkiness is going to keep us from going to latest until it is handled.

**Comment by bakert** [comment]
Also the menu doesn't work. It doesn't show anything except the chevron.

**Comment by bakert** [comment]
Fixed the menu by using full latest not slim. Still got that flash of the headers tho.

**Comment by bakert** [comment]
Setting a min-height and min-width of the current height and width prior to attaching footable is enough to prevent the jumping around.

**Comment by bakert** [comment]
We can mitigate the flash on our "normal" tables by moving the setting of visible into a block like this:

```
).on(
        "ready.ft.table", () => {
            $(selector).not(".very-large").css({ "visibility": "visible"});
            $("div.loading").addClass("loaded");
        }
    )
```

instead of just putting it after the footable setup.

However the upgrade *also* makes the react table load with more flashes especially upon clicking next/previous page.

**Comment by bakert** [comment]
I think integrating react loading, latest jquery and footable just isn't going to work.

As footable is the main problem, brings dubious benefit, and affects performance I'm going to remove it from the app.

The consequence of this is that data tables will horizontal-scroll instead of having that "+" symbol on the right that allows you to see the rest of the data.

**Comment by bakert** [comment]
17bfd509 removes footable

**Comment by bakert** [comment]
We no longer get ugly flashes when loading now. Upgrade is in 17bfd509 too. Closing.

**Comment by silasary** [comment]
Conventional wisdom says never combine React and JQuery. 
We should start migrating everything to React components and remove JQuery altogether
