### ISSUE TITLE
Form help text programatically from list of commands

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#56]
As more commands get added they should automatically appear in help.

At one extreme of this kind of approach is docopt (see http://docopt.org/) which is, let's be honest, amazing.

A simple solution would be to have a command-making class or function that expects a name and a string description and we use that for all commands.

**Comment by silasary** [comment]
Yeah, That's been on my list for a while.  The current command handler has reached my limit of "How much functional code I'm willing to squash into a `switch` statement"

**Comment by bakert** [comment]
@silasary did this.
