### ISSUE TITLE
Show some sort of confidence measure for archetype predictions

### ISSUE THREAD

**Issue by adambiltcliffe** [PennyDreadfulMTG/Penny-Dreadful-Tools#5674]
If a deck is 100% identical to an existing deck, it shouldn't really require much thought to confirm the predicted archetype is the right one, but it would be good to see in the queue which are the decks where it was only 80% similar (or whatever) so you know which ones to pay attention to.

**Comment by adambiltcliffe** [comment]
The easiest way to do this requires adding a column to the db which is filled in when the prediction is made (but would then be useless for the rest of time) - how do we feel about doing that?

**Comment by bakert** [comment]
I'd put it in a separate table. Doesn't sound too awful.

**Comment by adambiltcliffe** [comment]
I think this is done, but leaving it open until I actually see some archetypes in the queue with similarity measures displayed
