### ISSUE TITLE
Think about logging

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#573]
Now that we have important data we don't want to lose we should log enough that failures are investigatable.

**Comment by bakert** [comment]
Specifically it would have been useful to have something in the log for Ahab reporting two results but them not showing up in the db.

**Comment by bakert** [comment]
@silasary Where do stdout and stderr go during execution of decksite? Do we store them? Do we have any other logging facility?

**Comment by silasary** [comment]
They're available via systemd-journald.

**Comment by bakert** [comment]
`journalctl -f -u pddecksite.service`
