### ISSUE TITLE
Graying out behavior is not clear enough

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#574]
Example: sort by time and there just happens to be two 5-0 records followed by a deck that hasn't played a match yet or a tapped out deck. The second 5-0 record is not clear enough.

Either only gray out for 3/4/5+ repeats in a row or add a background color or confine to columns other than record.

**Comment by silasary** [comment]
I think we should just not apply .repeat on records.

**Comment by bakert** [comment]
This was with a much lighter font for .repeat, I think. Where we are at is not perfect but I don't think there's anything to fuss about here.
