### ISSUE TITLE
Consider refactoring rules to store a card for each entry

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#5783]
This is a more normalized representation and would allow easier querying by card. Also prevents creating a rule that includes and excludes the same card at the db level.

rule (id int primary key auto_increment, archetype_id int, foreign key (archetype_id) references archetype (id) ON UPDATE CASCADE ON DELETE CASCADE)
rule_card (rule_id, card varchar(190), include/exclude boolean, primary key (rule_id, card))

**Comment by adambiltcliffe** [comment]
Apart from including card in the primary key (which now you mention it probably is a good idea), how is this different to what we have?

**Comment by bakert** [comment]
Oh I think I misunderstood. I was thinking because I could get "Cruel Ultimatu/m" in there that we were storing a blob of text. But it's not that it's just that we're not checking that real cards are represented we are still breaking apart into separate entries and storing separately. I already logged that so ignore this. Closing.
