### ISSUE TITLE
Cache bust upon release.

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#583]
Probably using ?<timestamp> querystring on css and js files.

**Comment by silasary** [comment]
I can just turn off caching on the CDN, if we're going to do that.

But I'd rather keep it on, if at all possible.

**Comment by silasary** [comment]
One option is to put the git commit hash as a querystring.  
That way it'll still have the advantages of caching when the files haven't changed, but you won't need to wait the two hours for cache to expire. (If we want to be impatient about that)

**Comment by bakert** [comment]
Yeah, that's what I meant. Time stamp of release not literally the time now
:)

Commit hash also works. Commit hash of last mod to file even better not
sure how easy that is.

**Comment by bakert** [comment]
I added ?v=<commithash> to the static resources.
