### ISSUE TITLE
New command !flavor {card} which fetches the flavor text of a card

### ISSUE THREAD

**Issue by Pierakor** [PennyDreadfulMTG/Penny-Dreadful-Tools#5914]
Perhaps also interesting would be getting a random flavor text?
!randomflavor {set|format} 
which gives the flavor text of a random card in the specified set or format

**Comment by bakert** [comment]
We do not currently store flavor text although it is available in the scryfall data as `flavor_text`. It is per-printing information – we would store it in a new table or in the printings table.

I quite like:

`!flavor {cardname}` – gives the latest flavor text for a particular card.
`!flavor` – gives a random flavor text. We'd probably have to provide reverse-lookup else this might be maddening.

Doing per-set flavor text would probably come a distant second to enabling the same thing for images and would use whatever mechanism we implement there.
