### ISSUE TITLE
Add predefined categories and the `is:` search term.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#598]
MCI supports things like `is:reserved`, `is:promo`, `is:funny` and `is:reprint`.

We want to support more useful categories, like `is:gainland`, `is:painland`, `is:fetch`.

These could be implemented by having a list of expansions.
ie: `is:gainland` => `(t:land o:"When ~ enters the battlefield, you gain" o:"life")`

Suggested in discord by @Volvary

**Comment by bakert** [comment]
I wonder if these are just better specified as lists of specific names. I guess it depends if "is:fetchland" should get only the 10 famous fetchlands or any land that fetches another land including those not yet printed.

**Comment by silasary** [comment]
I think the answer to that might depend on the term in question. 

And even if we were hardcoding fetchlands, I'd want it to at least include the 5 mirage "Slow Fetches" as well, because as PD players, we probably care about them more than the normal ones.

For now, I'd say just search, and hit all matching cards.  If people end up complaining about a specific cycle, we can just change that search term to a `(A or B or C [or...])` to hardcode the cycle.

**Comment by silasary** [comment]
Worst comes to worst, `(Flood Plain OR Bad River OR Rocky Tar Pit OR Mountain Valley OR Grasslands OR Flooded Strand OR Polluted Delta OR Bloodstained Mire OR Wooded Foothills OR Windswept Heath OR Misty Rainforest OR Verdant Catacombs OR Marsh Flats OR Arid Mesa OR Scalding Tarn)` might be unwieldy for a human, but it's not a problem for the SQL.

But I'd rather not do that unless we need to
