### ISSUE TITLE
Ability to request specific printing of a card

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#6]
- [bottle gomes|mrd] <-- support some syntax (possibly this) for getting the specific version of an image.

**Comment by bakert** [comment]
I don't think this matters enough to do it. bluebones supports this because it's an important facility when you're making proxies but it's not really relevant here except for "I really love the art on X version of Y card". It did come up once. We can reopen if we feel there's an actual need.
