### ISSUE TITLE
Potentially delete/redownload old images

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#61]
Between new card images coming out (in better quality), and card combos that will never be used again, it might be worth deleting some of the older images that are accruing in the cache.

Let's think about ways to do that.

**Comment by bakert** [comment]
I have 332M of images on my laptop so gawd knows what the server has.

**Comment by bakert** [comment]
Would it be too extreme to include a `!clearimagecache` command that just deletes all .jpg files in the images directory? We could do `!clearimagecache {name}` and rm _{name}_.jpg but the broader version seems cleaner and just as useful?

Related question: do we really gain that much by caching images? Might as well be faster where it applies, I suppose.

**Comment by silasary** [comment]
`!clearcache` sounds like a good idea.

**Comment by bakert** [comment]
Added `!clearimagecache` in af2ddce. clearcache is a much nicer name but is ambiguous. Maybe if we expand it to clear all caches we can give it the nicer name :)
