### ISSUE TITLE
Provide non-intrusive reminders when league is ending soon

### ISSUE THREAD

**Issue by tsutton** [PennyDreadfulMTG/Penny-Dreadful-Tools#6221]
Probably do this via a little extra text in the league status bar at the bottom of pdm, and via discord by having the bot post a reminder like it does for upcoming tournaments.

**Comment by bakert** [comment]
@tsutton removed you as assignee but if you're still on this feel free to reassign.

**Comment by tsutton** [comment]
This is kinda done - it is merged and seemed to have worked the first time, but it didn't work the second time, so it needs some debugging. I'll leave it unassigned for now, as I'm working on another thing at the moment.

**Comment by tsutton** [comment]
This seems to have worked basically as intended for June league. The reminders came not exactly when scheduled  - 9 hour 50 minutes being the biggest offender, the others were 4 min 43 second and 29 min 56 second - so I assume the bot was busy at those times. Closing.
