### ISSUE TITLE
Typo on legality line of /decks/<id>/

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#636]
"Deckname is currently Penny Dreadul legal." (Missing the F in Dreadful)

**Comment by bakert** [comment]
Fixed in c05b89e.

**Comment by bakert** [comment]
Hm. Or not. http://ci.katelyngigante.com/job/Penny%20Dreadful/job/Penny-Dreadful-Tools/job/PR-637/1/console doesn't like my push.

**Comment by silasary** [comment]
Jenkins had a random bug.  Re-ran the job and it worked fine.
