### ISSUE TITLE
Prices db does not have backups

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#640]
Possibly we should move this to the same server as everything else (which has backups? maybe?)

But definitely we should back it up one way or another.

**Comment by silasary** [comment]
Yeah.  I've got the price fetcher running on my server, and I plan on switching the datasource to the new endpoint the day after Rotation.

**Comment by silasary** [comment]
This is done?

**Comment by bakert** [comment]
Not by me! If the server has backups, or if we've decided we don't care about preserving history.
