### ISSUE TITLE
PRAGMA writable_schema = 1 is not valid mysql SQL

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#662]
It's only valid for SQLite but we say it to the new MySQL stuff.

Actually we seem to be trying to say quite a lot of MySQL-illegal things to MySQL so maybe I've misunderstood how far along this stuff is.

**Comment by silasary** [comment]
Only the decksite database is mysql legal.
The cards database is unfortunately still sqlite. (Because it would involve completely tearing Fuzzy out,  and I didn't have time to find a mysql equivalent at the time)

**Comment by bakert** [comment]
We're not using MySQL for this stuff yet. Use ".sqlite" in the name of your magic_database in your config.json to avoid this problem and continue using SQLite for cards db.
