### ISSUE TITLE
Clicking on test failures details for PR #665 gives a 404

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#667]
http://ci.katelyngigante.com/blue/organizations/jenkins/Penny%20Dreadful%2FPenny-Dreadful-Tools/detail/pricefix/1/

**Comment by bakert** [comment]
http://ci.katelyngigante.com/blue/organizations/jenkins/Penny%20Dreadful%2FPenny-Dreadful-Tools/detail/PR-665/1/

**Comment by bakert** [comment]
Real links: http://ci.katelyngigante.com/job/Penny%20Dreadful/job/Penny-Dreadful-Tools/job/pricefix/2/warnings48Result/
http://ci.katelyngigante.com/job/Penny%20Dreadful/job/Penny-Dreadful-Tools/job/pricefix/1/

Too much escaping of path?

**Comment by silasary** [comment]
I've removed the offending Jenkins plugin.
