### ISSUE TITLE
debugger running on live site

### ISSUE THREAD

**Issue by brunobriante** [PennyDreadfulMTG/Penny-Dreadful-Tools#686]
I don't know if this is the right place to talk about this as in my view this is a security related issue but i didn't found a more private place to send this.

The site right now is exposing the werkzeug when a exception occurs (which for me occurred on http://pennydreadfulmagic.com/league/, a link that is shown on the login page as "league announcements"). Sure the PIN is active but even their own docs warn multiple times about the risk of enabling it on a production environment.

Is this a bug or a known "shippable" issue? In the later case is ok to do PR with support for a env settings disabling it on production?

**Comment by bakert** [comment]
This is one for @silasary to decide on. With the PIN stuff I wonder how big the risk really is here.

**Comment by bakert** [comment]
ac87089 at least prevents /league/ from showing it by fixing the 404 page.

**Comment by silasary** [comment]
It's known (and has been incredibly useful).

With the 404 page fixed, I think this is an acceptable risk.

**Comment by bakert** [comment]
Sounds ok to me.
