### ISSUE TITLE
Some images cannot be fetched from any source and it crashes the bot

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#700]
I think maybe if we fix the scryfall http version not supported issue it would work? Not clear.

Trying to get first choice image for 1996 World Champion, Proposal
Storing http://magic.bluebones.net/proxies/?c=1996+world+champion%7cproposal in /Users/bakert/.Penny-Dreadful-Discord-Bot/-----world-champion_proposal.jpg
Trying to get second choice image for 1996 World Champion, Proposal
Storing http://magic.bluebones.net/proxies/index2.php?c=1996+world+champion%7cproposal in /Users/bakert/.Penny-Dreadful-Discord-Bot/-----world-champion_proposal.jpg
Error: HTTP Error 404: Not Found
Storing http://api.scryfall.com/cards/named?exact=1996 World Champion&format=image in /Users/bakert/.Penny-Dreadful-Discord-Bot/-----world-champion_proposal.jpg
Error: HTTP Error 505: HTTP Version Not Supported
Trying to get MCI image for -----world-champion_proposal
Storing http://magiccards.info/scans/en/pcel/1.jpg in /Users/bakert/.Penny-Dreadful-Discord-Bot/-----world-champion_proposal.jpg
Error: HTTP Error 404: Not Found
Trying to get fallback image for -----world-champion_proposal
Storing None in /Users/bakert/.Penny-Dreadful-Discord-Bot/-----world-champion_proposal.jpg

**Comment by silasary** [comment]
Ah, the cards that aren't on Gatherer...

**Comment by bakert** [comment]
scryfall actually has (some of? all of?) them but I get `Error: HTTP Error 505: HTTP Version Not Supported` using http OR https. I also get it when using curl. But not when using a browser. I'll try setting User-Agent.

**Comment by bakert** [comment]
Ok, it's not user-agent and explicitly using http1.0 or http1.1 with curl fails with the same message.

**Comment by bakert** [comment]
Ok, this curl command works from the commandline:

`curl -L -v 'https://api.scryfall.com/cards/named?exact=1996%20World%20Champion&format=image'`

Now to reproduce in the code. (The two crucial things were (1) replacing spaces with %20 and (2) -L to follow the resulting 302.

**Comment by bakert** [comment]
OK we were not calling fetcher_internal.escape on the scryfall

It's true that scryfall fallback will only produce a single image when we want a group so for the full fix we should add compositing on the bot side. But this fixes the crash.

30c0ade.
