### ISSUE TITLE
can't sign up for league play

### ISSUE THREAD

**Issue by swab148** [PennyDreadfulMTG/Penny-Dreadful-Tools#7073]
when i try to sign up for league, it just says "internal server error" and now i can't play pd pls halp
![Screenshot from 2020-02-24 00-32-46](https://user-images.githubusercontent.com/61404353/75132703-9c476400-569d-11ea-8adb-8f318c3b9538.png)

**Comment by swab148** [comment]
nvm, a

**Comment by bakert** [comment]
@swab148 im glad you were able to get in. But can you share what you were entering that didn’t work? I’d like to fix it so it gives a useful error message in future. Thanks!

**Comment by bakert** [comment]
![image](https://user-images.githubusercontent.com/1541/75141317-9c208600-56e8-11ea-96ee-7dbda5c7619e.png)

Looks like we don't cope with trailing digits.

**Comment by bakert** [comment]
Input was:

```4 Footlight Fiend
4 Scorch Spitter
4 Shock
4 Orcish Hellraiser
4 Cavalcade of Calamity
2 Hellrider
2 Jaya, Venerated Firemage
4 Goblin Fireslinger 
4 Burst Lightning
4 Incinerate
4 Skewer the Critics
20 Mountain

3 Unchained Berserker 3
3 Combust 3
4 Lava Coil 2
2 Scouring Sands 2
3 Tibalt, Rakish Instigator 3```
