### ISSUE TITLE
gh.pennydreadfulmagic.com – 500 error at /.git/config

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#7178]
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Reported on github_tools by logged_out

InternalServerError 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Stack Trace:

Python traceback

  File "/home/discord/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/discord/.pyenv/versions/3.8.2/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)

Exception_hash: 15c4ac9d81725488a0e577b38f62ab01229a08cf

Request Data

Request Method: GET
Path: /.git/config?
Cookies: ImmutableMultiDict([])
Endpoint: None
View Args: None
Person: logged_out
Referrer: None
Request Data: {}
Host: localhost:5002
Accept-Encoding: gzip
Cf-Ipcountry: RU
X-Forwarded-For: 185.153.196.226, 172.68.132.85
Cf-Ray: 57f4dbb95c763278-SJC
X-Forwarded-Proto: https
Cf-Visitor: {"scheme":"https"}
User-Agent: python-requests/2.23.0
Accept: */*
Cf-Connecting-Ip: 185.153.196.226
Cdn-Loop: cloudflare
X-Forwarded-Host: gh.pennydreadfulmagic.com
X-Forwarded-Server: gh.pennydreadfulmagic.com
Connection: Keep-Alive
Labels: github_tools; InternalServerError

**Comment by bakert** [comment]
This is on the gh.pennydreadfulmagic.com server. Gives a 502 from cloudflare. Not sure I understand it.

**Comment by silasary** [comment]
odd.

**Comment by bakert** [comment]
I don't know what this was but at the very least I have stopped receiving notifications about it.
