### ISSUE TITLE
If a tournament had 8 people in it making top 8 doesn't deserve a star or a number in a circle

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#728]
We should make it contingent on tournament size how we decorate.

**Comment by bakert** [comment]
Also decks finish 6-8 in this tournament are NOT showing the circle for some reason. But 5th is.

**Comment by silasary** [comment]
When we scrape gatherling, we consolidate all TOP4=3, and TOP8=5.
```
elif img == TOP_4:
    d['finish'] = 3
elif img == TOP_8:
    d['finish'] = 5
else:
    d['finish'] = ranks.get(d['mtgo_username'], None)
```

In a regular tournament, it means we have `1,2,3,3,5,5,5,5,9,10,11,...`
In a tournament where playoffs don't have a top 8, we have `1,2,3,3,5,6,7,...`.  This means the person who came naturally 5th gets the ⑧, while the people 6-8 won't.

**Comment by bakert** [comment]
This is frustratingly close to being right. I *think* I might just not care as it's a one-of that may never be repeated and the display is not too awful. Anyone should feel free to reopen if they feel strongly.
