### ISSUE TITLE
Bot should ignore [numbers] [simbols]

### ISSUE THREAD

**Issue by ghost** [PennyDreadfulMTG/Penny-Dreadful-Tools#7442]
The bot answers "No matches." when you write code in the chat like [0] or [...]. There are only a few cards with something other than characters so it would be nice to ignore searches with only number or only symbols, and include cards like '_____' as exceptions.

**Comment by silasary** [comment]
We ignore any query less than three characters for this very reason.  Can you give me an example of a message that was triggering it?

**Comment by ghost** [comment]
[...], [012] Although this doesn't appear as often as I thought so it doesn't really matter.

**Comment by bakert** [comment]
Probably wontfix?
