### ISSUE TITLE
League Signup does not support Emoji

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#758]
See #746.

shared.pd_exception.DatabaseException: Failed to execute `INSERT INTO deck ( created_date, updated_date, person_id, source_id, url, identifier, name, competition_id, archetype_id, resource_uri, featured_card, score, thumbnail_url, small_thumbnail_url, wins, losses, draws, finish ) VALUES ( IFNULL(%s, UNIX_TIMESTAMP()), UNIX_TIMESTAMP(), %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s )` because of `(1366, "Incorrect string value: '\\xF0\\x9F\\x98\\xB1' for column 'name' at row 1")`

**Comment by bakert** [comment]
This works fine on local and 😱 is stored correctly in the db for the Amoncursed! deck. Something about cloudflare-nginx is causing the problem? Not clear. The HTTP headers are correct.

**Comment by bakert** [comment]
I think, actually, that it's the mysql configuration on the server that is the issue. But I'm going to override it with SET NAMES in 9578d26. I'll leave this open til I can test on the server: http://pennydreadfulmagic.com/decks/1614/

**Comment by bakert** [comment]
All is well.
