### ISSUE TITLE
Every discord command can be use by any person on the Discord.

### ISSUE THREAD

**Issue by kzcheng** [PennyDreadfulMTG/Penny-Dreadful-Tools#7620]
The check for if a Discord User is admin does not work, so every Discord command can be used by anyone.

This currently includes the command `!restart` and `!rotate`.

**Comment by kzcheng** [comment]
See #7505.

**Comment by kzcheng** [comment]
It seems the line `@commands.check(commands.is_owner())` in `restartbot.py` and `rotate.py` does not function correctly.

**Comment by silasary** [comment]
Duplicate of #7505
