### ISSUE TITLE
If someone fetches a new card via the !spoiler command, we should import that data into the db

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#769]
Scryfall adds data long before mtgjson, and !spoiler fetches cards from Scryfall's API.

Often during spoiler season, people try to call new cards using the normal `[cardname]` syntax, and this confuses the bot.

We should attempt to partially mitigate this by adding scryfall cards to the DB when explicitly fetched.

(We shouldn't make any attempt to persist this data past a db reset though)

**Comment by silasary** [comment]
Not high priority, but it would be nice to have before spoiler season.

**Comment by bakert** [comment]
@silasary you did this, right?

**Comment by silasary** [comment]
7722fc908a6704dd018827f32a6bdbdc08f9fba6
