### ISSUE TITLE
How does one change their MTGO name on PD website?

### ISSUE THREAD

**Issue by People30044** [PennyDreadfulMTG/Penny-Dreadful-Tools#7919]

**Comment by bakert** [comment]
@People30044 if you ping a mod on the discord or put the details in this ticket we can unlink your Discord account or alias two different mtgo names. https://pennydreadfulmagic.com/discord/

**Comment by People30044** [comment]
@bakert Thanks for responding,is it possible we could alias two different mtgo names?  Or  change the current name People30034 to people30044.  thank you for the help!

**Comment by bakert** [comment]
I can do that but I can only do it once people30044 has at least one league
or tournament match. Ping me here when you have one in the books!

**Comment by People30044** [comment]
I cant do that. My mtgo username is people30044 but my PD username is people30034. so the bot doesnt regonise me when i go into a match

**Comment by bakert** [comment]
I see. I have unlinked your discord account from people30034. Feel free to sign up to the league as people30044 and link your discord.

**Comment by People30044** [comment]
Fixed it thanks!
