### ISSUE TITLE
 Convert gatherling scraper to use the JSON API to avoid breaking changes in HTML due to Gatherling improvements 

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#8400]
As I improve Gatherling, the scraper is going to have to be rewritten anyway.   We should use this as an opportunity to drop the html scraping and use the API instead.

Literally everything you need for an event:
https://gatherling.com/api.php?action=recent_events 

~~Corrections (Gatherling Username -> MTGO Username):~~
~~https://gatherling.com/api.php?action=whois&name=<gatherling_username>~~
MTGO Usernames are now in the Players attribute

**Comment by bakert** [comment]
We did this.
