### ISSUE TITLE
Zero Byte uploads

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#9]
- As of Sep 26th we are still uploading zero byte files sometimes despite the checks we have -- what's going on?

**Comment by bakert** [comment]
A consistent repro case is to issue:

!random
!random
!random

in quick succession.

**Comment by silasary** [comment]
I've created a bug report upstream: Rapptz/discord.py#343

**Comment by silasary** [comment]
I don't think it's that simple. I've managed to call it four times in a row with no issues

Or had the second one fail.

**Comment by bakert** [comment]
Empirically 2e47ed3 seems to make this a bit better.

I wasn't able to get a zero byte image if I paused for 10s before each send but at 1s pause I still saw it occasionally. Pausing (with time.sleep) did seem to make things a bit better.

Seems rare enough after 2e47ed3 that maybe we can ignore? Time will show.

**Comment by bakert** [comment]
This still happens with a reasonable amount of regularity and it seems like a Discord bug. Not sure if we can workaround any better than we are. Given the joy I had on the emoji issue I'm not that encouraged to report to Discord but that was a much more obscure thing whereas this is a little more mainstream.

**Comment by silasary** [comment]
There is one possible workaround, but it will be a pain:
- Upon uploading an image, attempt to download it.
- If redownloaded image is empty, delete message and try again.

Note that this will increase processing time and bandwidth usage (although
probably not enough to matter)

**Comment by bakert** [comment]
Nice idea. Looks like the message reports back the size of the image so if that is trustworthy we can check without having to download.

I've added code that does that in 356bd79 but I'll leave this open until I see it do its thing.

**Comment by bakert** [comment]
I was able to test by spamming `!random 3` in private message to the bot. In all but one case in several hundred messages did the single retry fail. I saw the delete-and-repost action about 1 in 10 times. I'm gonna call this fixed. We can up retries to 2-infinity if we continue to see it enough to be worth it.
