### ISSUE TITLE
mtgg are a bit sloppy with reversed cards – we should do a quick check before rotation that we're not going to miss anything.

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#920]
Some examples:

Fetching https://www.mtggoldfish.com/index/PRM#online (Last Modified=Mon, 26 Jun 2017 18:53:52 GMT)
Bogus name Promo Theme Deck: Shadowmoor Sealed Deck Event Pack (promo theme deck: shadowmoor sealed deck event pack) found.
Bogus name Ludevic's Abomination (ludevic's abomination) found.
Bogus name Tovolar's Magehunter (tovolar's magehunter) found.
Bogus name Insidious Mist (insidious mist) found.
Bogus name Breaking (breaking) found.
Bogus name Entering (entering) found.
Bogus name Howlpack Alpha (howlpack alpha) found.
Bogus name Death (death) found.
Bogus name Life (life) found.
Bogus name Fire (fire) found.
Bogus name Ice (ice) found.
Bogus name Archdemon of Greed (archdemon of greed) found.
Fetching https://www.mtggoldfish.com/index/PRM_F#online (Last Modified=Mon, 26 Jun 2017 18:53:55 GMT)
Bogus name Entering (entering) found.
Bogus name Insidious Mist (insidious mist) found.
Bogus name Breaking (breaking) found.
Bogus name Death (death) found.
Bogus name Life (life) found.
Bogus name Ice (ice) found.
Bogus name Fire (fire) found.

**Comment by silasary** [comment]
The legality checker does not care, and will treat these cards as though they were valid.

If one of them makes it through, the checks at https://github.com/PennyDreadfulMTG/Penny-Dreadful-Tools/blob/master/magic/multiverse.py#L236-L240 will kick in and let us know.

**Comment by bakert** [comment]
I'm more worried that they have missing cards than that we will include a bogus card. They are definitively missing some MTGO cards (from CN2 and in treasure chests online) although none are 1c thankfully.

**Comment by bakert** [comment]
I spot-checked a bunch of these and the real card was also listed on the same page so I'm going to not worry.
