### ISSUE TITLE
Some cards have no legalities

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#924]
Noticed with Prismatic Geoscope. Probably an mtgjson bug. Prevents the proper running of the rotation page because it flips out when we try to set its pd legality.

**Comment by bakert** [comment]
Same for Grip of Phyresis.

**Comment by bakert** [comment]
There are 330 more cases of "layout" and "imageName" (17,232) in the mtgjson data than there is of "legalities" (16,902).

**Comment by silasary** [comment]
Fixed in mtgjson master, but not yet released.

**Comment by bakert** [comment]
Fixed in mtgjson 3.10.0
