### ISSUE TITLE
Oracle is a bit of a mess

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#99]
Unit tests have to instantiate Oracle which then visits the internet. That seems a bit messy.

We also have to pass oracle as a param to cards_from_queries and cards_from_query.

This could be solved by having Oracle be a singleton rather than a sort-of singleton that's a member variable on bot and gets passed around.

Or we could separate the version checking and updating from simple initialization.

There's various answers all of which are probably better than what we have now.

There's an argument that Oracle can be just a module with no class, too, as it really doesn't remember much (card_ids when doing setup).

There's an argument that setup and search are two different responsibilities and don't belong together.

Most of this probably applies to Database too.

**Comment by silasary** [comment]
The unit tests need a working database to do anything anyway.
So I don't have too much of a problem with that.

**Comment by silasary** [comment]
Fixed by #151
